cmake_minimum_required(VERSION 3.30)
get_filename_component(repository "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(work "${CMAKE_CURRENT_BINARY_DIR}/app-composition-tests")
set(source "${work}/source")
set(binary "${work}/build")
file(MAKE_DIRECTORY "${source}/config/engine" "${source}/apps/sample" "${source}/apps/second")
set(header "name,description,version,enabled,windows,linux,macos\n")
file(WRITE "${source}/config/engine/projects.csv" "${header}sample,,,1,1,1,1\nsecond,,,1,1,1,1\n")
file(WRITE "${source}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.30)
project(AppCompositionFixture LANGUAGES CXX)
set(GYO_BUILD_UI_EDITOR OFF)
include("${GYO_TEST_REPOSITORY}/cmake/GyoApps.cmake")
include("${GYO_TEST_REPOSITORY}/cmake/GyoAppPackaging.cmake")
gyo_configure_apps()
gyo_resolve_components(${GYO_REQUESTED_COMPONENTS})
# A tool may create SDL3 even when none of the selected apps require it.
add_library(SDL3-shared SHARED unused_sdl.cpp)
set_target_properties(SDL3-shared PROPERTIES
    OUTPUT_NAME UnusedToolSDL
    WINDOWS_EXPORT_ALL_SYMBOLS ON)
file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/unused-sdl-$<CONFIG>.txt"
    CONTENT "$<TARGET_FILE:SDL3-shared>")
foreach(GYO_CURRENT_APP IN LISTS GYO_ACTIVE_APPS)
    add_subdirectory("apps/${GYO_CURRENT_APP}")
endforeach()
gyo_finalize_app_packages()
file(WRITE "${CMAKE_BINARY_DIR}/selection.txt" "${GYO_ACTIVE_APPS}")
file(WRITE "${CMAKE_BINARY_DIR}/components.txt" "${GYO_REQUESTED_COMPONENTS}")
]=])
file(WRITE "${source}/unused_sdl.cpp" "int unused_tool_sdl() { return 1; }\n")
set(app_template [=[
gyo_app_requirements()
if(GYO_APP_DISCOVERY)
    return()
endif()
add_executable(@app@ main.cpp)
gyo_register_app_package(TARGET @app@ STARTUP_ARGS --smoke-test
    STARTUP_ENVIRONMENT "GYO_FIXTURE=present" STARTUP_TIMEOUT 10)
]=])
foreach(app sample second)
    string(CONFIGURE "${app_template}" app_cmake @ONLY)
    file(WRITE "${source}/apps/${app}/CMakeLists.txt" "${app_cmake}")
    file(WRITE "${source}/apps/${app}/main.cpp" "#include <cstdlib>\nint main() { return std::getenv(\"GYO_FIXTURE\") ? 0 : 7; }\n")
endforeach()
set(generator_args "")
if(GENERATOR)
    list(APPEND generator_args -G "${GENERATOR}")
endif()
if(MAKE_PROGRAM)
    list(APPEND generator_args "-DCMAKE_MAKE_PROGRAM=${MAKE_PROGRAM}")
endif()
if(PLATFORM)
    list(APPEND generator_args -A "${PLATFORM}")
endif()
if(CXX_COMPILER)
    list(APPEND generator_args "-DCMAKE_CXX_COMPILER=${CXX_COMPILER}")
endif()

function(run expected fragment)
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 90)
    if(expected AND NOT result EQUAL 0)
        message(FATAL_ERROR "Command failed (${result}): ${ARGN}\n${stdout}\n${stderr}")
    elseif(NOT expected AND result EQUAL 0)
        message(FATAL_ERROR "Invalid composition succeeded: ${ARGN}")
    endif()
    if(NOT fragment STREQUAL "")
        string(FIND "${stdout}\n${stderr}" "${fragment}" position)
        if(position LESS 0)
            message(FATAL_ERROR "Expected '${fragment}': ${stdout}\n${stderr}")
        endif()
    endif()
endfunction()

run(TRUE "" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" ${generator_args}
    "-DGYO_TEST_REPOSITORY=${repository}" -DGYO_APPS=AUTO -DGYO_RENDER_DEVICE=NONE -DCMAKE_BUILD_TYPE=Debug)
run(TRUE "" "${CMAKE_COMMAND}" --build "${binary}" --config Debug --parallel 2)
file(READ "${binary}/unused-sdl-Debug.txt" unused_sdl)
if(NOT EXISTS "${unused_sdl}")
    message(FATAL_ERROR "Unused SDL3 fixture was not built: ${unused_sdl}")
endif()
run(TRUE "" "${CMAKE_COMMAND}" --install "${binary}" --config Debug --prefix "${work}/stage")
file(GLOB_RECURSE installed_sdl LIST_DIRECTORIES FALSE "${work}/stage/*UnusedToolSDL*")
if(installed_sdl)
    message(FATAL_ERROR "Neutral app packages installed a tool-only SDL3 dependency: ${installed_sdl}")
endif()
foreach(app sample second)
    file(READ "${work}/stage/share/gyo/apps/${app}/manifest.json" manifest)
    string(JSON identity GET "${manifest}" app)
    string(JSON executable GET "${manifest}" executable)
    string(JSON startup GET "${manifest}" checks 0 name)
    string(JSON dependency_count LENGTH "${manifest}" runtime_dependencies)
    if(NOT dependency_count EQUAL 0)
        message(FATAL_ERROR "Neutral app ${app} acquired tool runtime dependencies: ${manifest}")
    endif()
    if(NOT "${identity}" STREQUAL "${app}" OR NOT "${startup}" STREQUAL "startup")
        message(FATAL_ERROR "Package identity or startup check is missing")
    endif()
    run(TRUE "" "${CMAKE_COMMAND}" -E env GYO_FIXTURE=present "${work}/stage/${executable}" --smoke-test)
endforeach()

# CSV-only selection changes regenerate the build and remove old targets.
file(WRITE "${source}/config/engine/projects.csv" "${header}sample,,,0,1,1,1\nsecond,,,1,1,1,1\n")
run(TRUE "" "${CMAKE_COMMAND}" --build "${binary}" --config Debug)
file(READ "${binary}/selection.txt" selected)
if(NOT selected STREQUAL second)
    message(FATAL_ERROR "CSV-only edit did not update selected apps: ${selected}")
endif()
run(FALSE "" "${CMAKE_COMMAND}" --build "${binary}" --config Debug --target sample)
run(FALSE "disabled" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -DGYO_APPS=sample)
run(TRUE "" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -DGYO_APPS=)
file(READ "${binary}/components.txt" components)
if(NOT components STREQUAL "")
    message(FATAL_ERROR "Empty selection retained consumer requirements")
endif()

# An app cannot silently disappear when its package/startup declaration is absent.
file(WRITE "${source}/apps/second/CMakeLists.txt"
    "gyo_app_requirements()\nif(GYO_APP_DISCOVERY)\nreturn()\nendif()\nadd_executable(second main.cpp)\n")
run(FALSE "must call gyo_register_app_package" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -DGYO_APPS=second)
file(WRITE "${source}/apps/second/CMakeLists.txt"
    "gyo_app_requirements(COMPONENTS SDL_GPU)\nif(GYO_APP_DISCOVERY)\nreturn()\nendif()\n")
run(FALSE "SDL_GPU requirement" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -DGYO_APPS=second)
file(WRITE "${source}/apps/second/CMakeLists.txt"
    "gyo_app_requirements(COMPONENTS UNKNOWN)\nif(GYO_APP_DISCOVERY)\nreturn()\nendif()\n")
run(FALSE "Unknown GYO component" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -DGYO_APPS=second)
run(FALSE "was removed" "${CMAKE_COMMAND}" -S "${source}" -B "${work}/legacy" ${generator_args}
    "-DGYO_TEST_REPOSITORY=${repository}" -DGYO_BUILD_RUNTIME=OFF)

message(STATUS "App composition: independent targets, installed startup, runtime isolation, CSV regeneration and fail-fast contracts passed")
