cmake_minimum_required(VERSION 3.30)
get_filename_component(repository "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(work "${CMAKE_CURRENT_BINARY_DIR}/app-packaging-tests")
set(source "${work}/source")
file(MAKE_DIRECTORY "${source}")

# Exercise the actual public helpers without a compiler or build. Only the
# unrelated install and DLL-deployment side effects are replaced in this fixture.
file(WRITE "${source}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.30)
project(AppPackagingFixture NONE)
include("${GYO_TEST_REPOSITORY}/cmake/GyoAppPackaging.cmake")
function(install)
endfunction()
function(gyo_copy_runtime_dlls)
endfunction()
add_executable(packaging_fixture IMPORTED GLOBAL)
set_target_properties(packaging_fixture PROPERTIES
    IMPORTED_LOCATION "${CMAKE_CURRENT_SOURCE_DIR}/fixture-executable")
set(GYO_CURRENT_APP sample)

# Architecture inputs model the target toolchain, including builds whose host
# processor differs from the selected compiler or macOS architecture.
set(CMAKE_SYSTEM_NAME "${TEST_SYSTEM}")
set(CMAKE_SYSTEM_PROCESSOR "${TEST_PROCESSOR}")
set(CMAKE_SIZEOF_VOID_P 8)
set(APPLE FALSE)
if(TEST_SYSTEM STREQUAL "Darwin")
    set(APPLE TRUE)
endif()
set(MSVC FALSE)
unset(MSVC_CXX_ARCHITECTURE_ID)
unset(CMAKE_CXX_COMPILER_ARCHITECTURE_ID)
unset(CMAKE_CXX_COMPILER_ID)
set(CMAKE_OSX_ARCHITECTURES "${TEST_OSX_ARCHS}")
if(TEST_MSVC_ARCH)
    set(MSVC TRUE)
    set(CMAKE_CXX_COMPILER_ID MSVC)
    set(MSVC_CXX_ARCHITECTURE_ID "${TEST_MSVC_ARCH}")
    set(CMAKE_CXX_COMPILER_ARCHITECTURE_ID "${TEST_MSVC_ARCH}")
    if(TEST_MSVC_ARCH STREQUAL "x86")
        set(CMAKE_SIZEOF_VOID_P 4)
    endif()
endif()

if(TEST_MODE STREQUAL "startup-zero")
    gyo_register_app_package(TARGET packaging_fixture STARTUP_TIMEOUT 0)
elseif(TEST_MODE STREQUAL "check-zero")
    gyo_register_app_package(TARGET packaging_fixture)
    gyo_add_app_package_check(NAME zero COMMAND "@EXECUTABLE@" TIMEOUT 0)
else()
    gyo_register_app_package(TARGET packaging_fixture
        STARTUP_ARGS "one two" "semi;colon" "" "tail" ""
        STARTUP_ENVIRONMENT "VALUE=one;two" "EMPTY="
        STARTUP_TIMEOUT 7 REQUIRED_FILES "bin/data;set.json")
    gyo_add_app_package_check(NAME direct
        COMMAND "@EXECUTABLE@" "one two" "semi;colon" "" "tail" ""
        ENVIRONMENT "VALUE=one;two" "EMPTY=" TIMEOUT 11)
    gyo_add_app_package_check(NAME maximum COMMAND "@EXECUTABLE@" TIMEOUT 3600)
endif()
get_property(manifest GLOBAL PROPERTY GYO_APP_sample_PACKAGE)
file(WRITE "${CMAKE_BINARY_DIR}/review-manifest.json" "${manifest}\n")
]=])

set(generator_args "")
if(GENERATOR)
    list(APPEND generator_args -G "${GENERATOR}")
endif()
if(MAKE_PROGRAM)
    list(APPEND generator_args "-DCMAKE_MAKE_PROGRAM=${MAKE_PROGRAM}")
endif()
if(PLATFORM)
    list(APPEND generator_args -A "${PLATFORM}")
endif()

function(expect_equal actual expected context)
    if(NOT "${actual}" STREQUAL "${expected}")
        message(FATAL_ERROR "${context}: expected '${expected}', got '${actual}'")
    endif()
endfunction()

function(run_fixture name success system processor expected_platform)
    set(binary "${work}/${name}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${binary}"
        ${generator_args} "-DGYO_TEST_REPOSITORY=${repository}"
        "-DTEST_SYSTEM=${system}" "-DTEST_PROCESSOR=${processor}" ${ARGN}
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    if(NOT success)
        if(result EQUAL 0)
            message(FATAL_ERROR "Invalid package fixture '${name}' was accepted")
        endif()
        string(TOLOWER "${stdout}\n${stderr}" diagnostic)
        string(FIND "${diagnostic}" "${expected_platform}" found)
        if(found EQUAL -1)
            message(FATAL_ERROR
                "Fixture '${name}' did not report '${expected_platform}': ${stdout}\n${stderr}")
        endif()
        return()
    endif()
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Package fixture '${name}' failed: ${stdout}\n${stderr}")
    endif()
    file(READ "${binary}/review-manifest.json" manifest)
    string(JSON platform GET "${manifest}" platform)
    expect_equal("${platform}" "${expected_platform}" "${name}/target platform")

    # Compare each argument separately: treating the command as a CMake list
    # here would hide the very semicolon/empty-argument regression being tested.
    foreach(check RANGE 0 1)
        string(JSON count LENGTH "${manifest}" checks ${check} command)
        expect_equal("${count}" 6 "${name}/check ${check} argv count")
        string(JSON executable GET "${manifest}" checks ${check} command 0)
        string(JSON spaced GET "${manifest}" checks ${check} command 1)
        string(JSON semicolon GET "${manifest}" checks ${check} command 2)
        string(JSON empty GET "${manifest}" checks ${check} command 3)
        string(JSON tail GET "${manifest}" checks ${check} command 4)
        string(JSON trailing_empty GET "${manifest}" checks ${check} command 5)
        expect_equal("${executable}" "@EXECUTABLE@" "${name}/check ${check} executable")
        expect_equal("${spaced}" "one two" "${name}/check ${check} spaced argument")
        expect_equal("${semicolon}" "semi;colon" "${name}/check ${check} semicolon argument")
        expect_equal("${empty}" "" "${name}/check ${check} empty argument")
        expect_equal("${tail}" tail "${name}/check ${check} tail argument")
        expect_equal("${trailing_empty}" "" "${name}/check ${check} trailing empty argument")
        string(JSON environment_count LENGTH "${manifest}" checks ${check} environment)
        expect_equal("${environment_count}" 2 "${name}/check ${check} environment count")
        string(JSON value GET "${manifest}" checks ${check} environment 0)
        string(JSON empty_value GET "${manifest}" checks ${check} environment 1)
        expect_equal("${value}" "VALUE=one;two" "${name}/check ${check} semicolon environment")
        expect_equal("${empty_value}" "EMPTY=" "${name}/check ${check} empty environment")
    endforeach()
    string(JSON required_count LENGTH "${manifest}" required_files)
    expect_equal("${required_count}" 2 "${name}/required path count")
    string(JSON required_path GET "${manifest}" required_files 1)
    expect_equal("${required_path}" "bin/data;set.json" "${name}/semicolon path")
    string(JSON startup_timeout GET "${manifest}" checks 0 timeout)
    string(JSON direct_timeout GET "${manifest}" checks 1 timeout)
    string(JSON maximum_timeout GET "${manifest}" checks 2 timeout)
    expect_equal("${startup_timeout}" 7 "${name}/startup timeout")
    expect_equal("${direct_timeout}" 11 "${name}/direct timeout")
    expect_equal("${maximum_timeout}" 3600 "${name}/maximum timeout")
endfunction()

run_fixture(windows_x64 TRUE Windows AMD64 windows-x64 -DTEST_MSVC_ARCH=x64)
run_fixture(windows_cross_host TRUE Windows ARM64 windows-x64 -DTEST_MSVC_ARCH=x64)
run_fixture(linux_x64 TRUE Linux x86_64 linux-x64)
run_fixture(macos_arm64 TRUE Darwin arm64 macos-arm64)
run_fixture(macos_explicit_arm64 TRUE Darwin x86_64 macos-arm64 -DTEST_OSX_ARCHS=arm64)

run_fixture(windows_x86 FALSE Windows AMD64 "no package platform" -DTEST_MSVC_ARCH=x86)
run_fixture(linux_arm64 FALSE Linux aarch64 "no package platform")
run_fixture(macos_x64 FALSE Darwin x86_64 "no package platform" -DTEST_OSX_ARCHS=x86_64)
run_fixture(macos_universal FALSE Darwin arm64 "no package platform" "-DTEST_OSX_ARCHS=arm64\;x86_64")
run_fixture(startup_zero FALSE Linux x86_64 timeout -DTEST_MODE=startup-zero)
run_fixture(check_zero FALSE Linux x86_64 timeout -DTEST_MODE=check-zero)
message(STATUS "App packaging: argument fidelity, timeouts and target architecture cases passed")
