cmake_minimum_required(VERSION 3.30)
get_filename_component(repository "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(work "${CMAKE_CURRENT_BINARY_DIR}/app-tooling-tests")
set(source "${work}/source")
set(binary "${work}/build")
# Every invocation creates new sources: the first product test must have no
# optional tooling files, even after an earlier successful CTest run.
string(RANDOM LENGTH 10 ALPHABET 0123456789abcdef suffix)
set(source "${work}/source-${suffix}")
set(binary "${work}/build-${suffix}")
file(MAKE_DIRECTORY "${source}/apps/plain" "${source}/config/engine")
file(WRITE "${source}/config/engine/projects.csv"
    "name,description,version,enabled,windows,linux,macos\nplain,Ordinary product,,1,1,1,1\n")
file(WRITE "${source}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.30)
project(AppToolingFixture LANGUAGES CXX)
option(BUILD_TESTING "Quality checks" OFF)
option(GYO_ENABLE_PACKAGING "Engineering package checks" OFF)
if(BUILD_TESTING)
    include(CTest)
endif()
# Neither axis needs an interpreter or a test framework for this tiny app.
# Calling find_package would fail even if either happened to be installed.
function(find_package package)
    if(package MATCHES "[Pp]ython|doctest")
        message(FATAL_ERROR "Unexpected optional dependency lookup: ${package}")
    endif()
    _find_package(${ARGV})
endfunction()
set(GYO_BUILD_UI_EDITOR OFF)
include("${GYO_TEST_REPOSITORY}/cmake/GyoApps.cmake")
include("${GYO_TEST_REPOSITORY}/cmake/GyoAppProject.cmake")
include("${GYO_TEST_REPOSITORY}/cmake/GyoAppPackaging.cmake")
gyo_configure_apps()
gyo_resolve_components(${GYO_REQUESTED_COMPONENTS})
foreach(GYO_CURRENT_APP IN LISTS GYO_ACTIVE_APPS)
    add_subdirectory("apps/${GYO_CURRENT_APP}")
endforeach()
gyo_finalize_app_installation()
gyo_finalize_app_packages()
]=])
file(WRITE "${source}/apps/plain/CMakeLists.txt" [=[
gyo_app_requirements()
if(GYO_APP_DISCOVERY)
    return()
endif()
gyo_app_project()
gyo_app_add_executable(entry MAIN OUT_TARGET application SOURCES main.cpp)
file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/main-$<CONFIG>.txt" CONTENT "$<TARGET_FILE_NAME:${application}>")
]=])
file(WRITE "${source}/apps/plain/main.cpp" [=[
#include <gyo/AppConfig.hpp>
#include <string_view>
int main() { return std::string_view(Gyo::AppConfig::Id) == "plain" ? 0 : 3; }
]=])
set(generator_args "")
if(GENERATOR)
    list(APPEND generator_args -G "${GENERATOR}")
endif()
if(MAKE_PROGRAM)
    list(APPEND generator_args "-DCMAKE_MAKE_PROGRAM=${MAKE_PROGRAM}")
endif()
if(PLATFORM)
    list(APPEND generator_args -A "${PLATFORM}")
endif()
if(CXX_COMPILER)
    list(APPEND generator_args "-DCMAKE_CXX_COMPILER=${CXX_COMPILER}")
endif()
function(run expected fragment)
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 90)
    if(expected AND NOT result EQUAL 0)
        message(FATAL_ERROR "Command failed (${result}): ${ARGN}\n${stdout}\n${stderr}")
    elseif(NOT expected AND result EQUAL 0)
        message(FATAL_ERROR "Expected tooling failure did not occur: ${ARGN}")
    endif()
    if(NOT "${fragment}" STREQUAL "" AND NOT "${stdout}\n${stderr}" MATCHES "${fragment}")
        message(FATAL_ERROR "Expected '${fragment}':\n${stdout}\n${stderr}")
    endif()
endfunction()
function(install_product name expect_manifest)
    set(stage "${work}/${name}-${suffix}")
    run(TRUE "" "${CMAKE_COMMAND}" --build "${binary}" --config Debug --parallel 2)
    run(TRUE "" "${CMAKE_COMMAND}" --install "${binary}" --config Debug --prefix "${stage}")
    file(READ "${binary}/main-Debug.txt" executable)
    run(TRUE "" "${stage}/bin/${executable}")
    if(expect_manifest)
        file(READ "${stage}/share/gyo/apps/plain/manifest.json" manifest)
        string(JSON app GET "${manifest}" app)
        string(JSON startup GET "${manifest}" checks 0 name)
        if(NOT app STREQUAL "plain" OR NOT startup STREQUAL "startup")
            message(FATAL_ERROR "Package-only hook did not declare this app's startup")
        endif()
    elseif(EXISTS "${stage}/share/gyo/apps/plain/manifest.json")
        message(FATAL_ERROR "Ordinary product installation acquired a QA package manifest")
    endif()
endfunction()

# First configure: only product CMake and source exist, no flags enable QA.
foreach(directory tests ci packaging)
    if(EXISTS "${source}/apps/plain/${directory}")
        message(FATAL_ERROR "The absent-tooling fixture was not physically empty")
    endif()
endforeach()
run(TRUE "" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" ${generator_args}
    "-DGYO_TEST_REPOSITORY=${repository}" -DCMAKE_BUILD_TYPE=Debug)
file(STRINGS "${binary}/CMakeCache.txt" axes REGEX "^(BUILD_TESTING|GYO_ENABLE_PACKAGING):BOOL=")
list(SORT axes)
if(NOT "${axes}" STREQUAL "BUILD_TESTING:BOOL=OFF;GYO_ENABLE_PACKAGING:BOOL=OFF")
    message(FATAL_ERROR "Product mode enabled optional tooling by default: ${axes}")
endif()
install_product(absent FALSE)

# Invalid optional files cannot prevent product configure/build/run/install.
file(MAKE_DIRECTORY "${source}/apps/plain/tests" "${source}/apps/plain/packaging" "${source}/apps/plain/ci")
file(WRITE "${source}/apps/plain/tests/Tests.cmake" "message(FATAL_ERROR \"test hook visited\")\n")
file(WRITE "${source}/apps/plain/packaging/Package.cmake" "message(FATAL_ERROR \"package hook visited\")\n")
file(WRITE "${source}/apps/plain/ci/invalid.py" "invalid optional Python file\n")
run(TRUE "" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}")
install_product(broken_ignored FALSE)
run(FALSE "test hook visited" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -DBUILD_TESTING=ON)
run(FALSE "package hook visited" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}"
    -DBUILD_TESTING=OFF -DGYO_ENABLE_PACKAGING=ON)

# Test-only mode loads a real QA source while the invalid packaging hook stays unread.
file(WRITE "${source}/apps/plain/tests/Tests.cmake" [=[
gyo_app_get_target(entry OUT_TARGET product)
if(NOT TARGET "${product}")
    message(FATAL_ERROR "Deferred test hook cannot retrieve the product target")
endif()
gyo_app_add_executable(quality OUT_TARGET check SOURCES tests/quality.cpp)
gyo_app_add_test(NAME quality COMMAND ${check})
file(WRITE "${CMAKE_BINARY_DIR}/test-hook-visited.txt" "yes")
]=])
file(WRITE "${source}/apps/plain/tests/quality.cpp" "int main() { return 0; }\n")
run(TRUE "" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}"
    -DBUILD_TESTING=ON -DGYO_ENABLE_PACKAGING=OFF)
install_product(test_only FALSE)
run(TRUE "" "${CMAKE_CTEST_COMMAND}" --test-dir "${binary}" -C Debug --output-on-failure --no-tests=error)
if(NOT EXISTS "${binary}/test-hook-visited.txt")
    message(FATAL_ERROR "Test-only mode ignored its quality hook")
endif()

# Package-only mode has no QA source at all and cannot read the broken test hook.
file(REMOVE "${source}/apps/plain/tests/quality.cpp")
file(WRITE "${source}/apps/plain/tests/Tests.cmake" "message(FATAL_ERROR \"test hook visited\")\n")
file(WRITE "${source}/apps/plain/packaging/Package.cmake" [=[
gyo_app_get_target(entry OUT_TARGET product)
gyo_register_app_package(STARTUP_ARGS --startup)
file(WRITE "${CMAKE_BINARY_DIR}/package-hook-visited.txt" "yes")
]=])
run(TRUE "" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}"
    -DBUILD_TESTING=OFF -DGYO_ENABLE_PACKAGING=ON)
install_product(package_only TRUE)
if(NOT EXISTS "${binary}/package-hook-visited.txt")
    message(FATAL_ERROR "Package-only mode ignored its engineering hook")
endif()
run(FALSE "" "${CMAKE_COMMAND}" --build "${binary}" --config Debug --target gyo_plain-quality)
message(STATUS "App tooling: physically absent QA, ignored broken hooks, product install/run, and independent test/package axes passed")
