cmake_minimum_required(VERSION 3.30)
get_filename_component(repository "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
include("${repository}/cmake/GyoComponents.cmake")

set(CMAKE_SYSTEM_NAME Windows)
set(GYO_RENDER_DEVICE AUTO)
set(GYO_GPU_DRIVER AUTO)
set(GYO_SHADER_BUNDLE AUTO)
set(GYO_BUILD_SDL_GPU_BACKEND OFF)
set(GYO_BUILD_SDL_IMAGE_LOADER OFF)
set(GYO_BUILD_SDL_TTF_ADAPTER OFF)
set(GYO_BUILD_UFBX_LOADER OFF)

# SDL's own cache contains SDL_GPU=ON after the first configure. Component
# identifiers must remain literal strings when a build reconfigures later.
foreach(component IN LISTS GYO_KNOWN_COMPONENTS)
    set(${component} ON CACHE BOOL "Upstream option collision fixture" FORCE)
endforeach()

if(DEFINED GYO_COMPONENT_TEST_CASE)
    if(GYO_COMPONENT_TEST_CASE STREQUAL "gpu-none")
        set(GYO_RENDER_DEVICE NONE)
        set(GYO_ACTIVE_APPS test_game)
        gyo_resolve_components(SDL_GPU)
    elseif(GYO_COMPONENT_TEST_CASE STREQUAL "unknown")
        gyo_resolve_components(NOT_A_COMPONENT)
    else()
        message(FATAL_ERROR "Unknown component test case")
    endif()
    return()
endif()

function(expect_equal actual expected context)
    if(NOT "${actual}" STREQUAL "${expected}")
        message(FATAL_ERROR "${context}: expected '${expected}', got '${actual}'")
    endif()
endfunction()

function(expect_components context expected sdl3)
    foreach(component IN LISTS GYO_KNOWN_COMPONENTS)
        set(wanted OFF)
        if(component IN_LIST expected)
            set(wanted ON)
        endif()
        expect_equal("${GYO_ENABLE_${component}}" "${wanted}" "${context}/${component}")
    endforeach()
    expect_equal("${GYO_ENABLE_SDL3}" "${sdl3}" "${context}/SDL3")
endfunction()

function(expect_failure case expected_message)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DGYO_COMPONENT_TEST_CASE=${case}"
        -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 15)
    if(result EQUAL 0)
        message(FATAL_ERROR "Invalid component case '${case}' was accepted")
    endif()
    string(FIND "${stdout}\n${stderr}" "${expected_message}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR
            "Component case '${case}' did not report '${expected_message}':\n${stdout}\n${stderr}")
    endif()
endfunction()

# Repeated calls deliberately share one process and caller scope, with no
# cleanup of effective outputs between calls. Requests must fully replace them.
gyo_resolve_components()
expect_components(empty "" OFF)
expect_equal("${GYO_SHADER_FORMATS}" "" "Empty shader formats")

gyo_resolve_components(SDL_PLATFORM)
expect_components(platform SDL_PLATFORM ON)
gyo_resolve_components(SDL_RENDERER)
expect_components(renderer "SDL_RENDERER;SDL_PLATFORM" ON)
gyo_resolve_components(SDL_GPU)
expect_components(gpu "SDL_GPU;SDL_PLATFORM" ON)
expect_equal("${GYO_SHADER_FORMATS}" "dxil;spirv" "GPU policy survives upstream cache collision")
expect_equal("${GYO_DEFAULT_GPU_DRIVER}" auto "Default GPU driver")

gyo_resolve_components(SDL_INPUT)
expect_components(input "SDL_INPUT;SDL_PLATFORM" ON)
expect_equal("${GYO_SHADER_FORMATS}" "" "Removing GPU clears shader formats")
gyo_resolve_components(SDL_IMAGE)
expect_components(image SDL_IMAGE ON)
gyo_resolve_components(SDL_TTF)
expect_components(text SDL_TTF ON)
gyo_resolve_components(UFBX)
expect_components(ufbx UFBX OFF)
gyo_resolve_components(IMGUI)
expect_components(imgui IMGUI ON)

gyo_resolve_components(SDL_GPU SDL_INPUT SDL_IMAGE SDL_TTF UFBX)
expect_components(game "SDL_GPU;SDL_INPUT;SDL_IMAGE;SDL_TTF;UFBX;SDL_PLATFORM" ON)
gyo_resolve_components(SDL_RENDERER SDL_IMAGE SDL_TTF IMGUI)
expect_components(editor "SDL_RENDERER;SDL_IMAGE;SDL_TTF;IMGUI;SDL_PLATFORM" ON)
expect_equal("${GYO_SHADER_FORMATS}" "" "Editor does not retain game shader requirements")
gyo_resolve_components(SDL_RENDERER)
expect_components(runtime "SDL_RENDERER;SDL_PLATFORM" ON)
gyo_resolve_components()
expect_components(cleared "" OFF)

# Explicit module options compose with app requests, without becoming sticky
# effective flags when those options are disabled on a later resolve.
set(GYO_BUILD_SDL_GPU_BACKEND ON)
set(GYO_BUILD_SDL_IMAGE_LOADER ON)
set(GYO_BUILD_SDL_TTF_ADAPTER ON)
set(GYO_BUILD_UFBX_LOADER ON)
gyo_resolve_components()
expect_components(options "SDL_GPU;SDL_IMAGE;SDL_TTF;UFBX;SDL_PLATFORM" ON)
set(GYO_BUILD_SDL_GPU_BACKEND OFF)
set(GYO_BUILD_SDL_IMAGE_LOADER OFF)
set(GYO_BUILD_SDL_TTF_ADAPTER OFF)
set(GYO_BUILD_UFBX_LOADER OFF)
gyo_resolve_components()
expect_components(options_cleared "" OFF)

set(GYO_RENDER_DEVICE SDL_GPU)
set(GYO_GPU_DRIVER VULKAN)
set(GYO_SHADER_BUNDLE SPIRV)
gyo_resolve_components()
expect_components(explicit_device "SDL_GPU;SDL_PLATFORM" ON)
expect_equal("${GYO_SHADER_FORMATS}" spirv "Explicit shader format")
expect_equal("${GYO_DEFAULT_GPU_DRIVER}" vulkan "Explicit GPU driver")
set(GYO_RENDER_DEVICE NONE)
set(GYO_GPU_DRIVER AUTO)
set(GYO_SHADER_BUNDLE AUTO)
gyo_resolve_components()
expect_components(device_cleared "" OFF)
expect_equal("${GYO_SHADER_FORMATS}" "" "NONE clears shader formats")

expect_failure(gpu-none "SDL_GPU requirement")
expect_failure(unknown "Unknown GYO component 'NOT_A_COMPONENT'")
message(STATUS "Components: all capabilities, cache collisions, repeat resolution, tool isolation and errors passed")
