cmake_minimum_required(VERSION 3.30)
foreach(required ROOT WORK C_COMPILER CXX_COMPILER NINJA)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
set(source "${WORK}/parent-source")
set(binary "${WORK}/parent-build")
file(MAKE_DIRECTORY "${source}")
file(WRITE "${source}/CMakeLists.txt" "cmake_minimum_required(VERSION 3.30)\nproject(HostSelectionParent NONE)\ninclude(\"${ROOT}/cmake/GyoShaders.cmake\")\n_gyo_require_shader_tool(command dependency)\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -G Ninja
    "-DCMAKE_MAKE_PROGRAM:FILEPATH=${NINJA}"
    "-DCMAKE_C_COMPILER:FILEPATH=${C_COMPILER}"
    "-DCMAKE_CXX_COMPILER:FILEPATH=${CXX_COMPILER}"
    RESULT_VARIABLE configured OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT configured EQUAL 0)
    message(FATAL_ERROR "Native parent configure failed: ${output}\n${error}")
endif()
file(READ "${binary}/gyo_shader_host_tools-prefix/tmp/gyo_shader_host_tools-cfgcmd.txt" command)
string(REGEX REPLACE "^cmd='(.*)'[\r\n]*$" "\\1" command "${command}")
set(selected_arguments)
foreach(argument IN LISTS command)
    if(argument MATCHES "^-DCMAKE_(C_COMPILER|CXX_COMPILER|MAKE_PROGRAM):FILEPATH=")
        list(APPEND selected_arguments "${argument}")
    endif()
endforeach()
list(LENGTH selected_arguments count)
if(NOT count EQUAL 3)
    message(FATAL_ERROR "The generated native host command did not preserve both compilers and Ninja: ${command}")
endif()
if(USES_MSVC AND "$ENV{INCLUDE}" STREQUAL "")
    message(STATUS "SKIP: native Ninja compiler probe requires an initialized MSVC developer environment")
    return()
endif()
# Execute the real generated tool-selection arguments against a tiny child.
# Conflicting environment hints reproduce a common IDE versus shell mismatch.
set(ENV{CC} "${WORK}/nonexistent-environment-c-compiler")
set(ENV{CXX} "${WORK}/nonexistent-environment-cxx-compiler")
set(child_source "${WORK}/child-source")
set(child_binary "${WORK}/child-build")
file(MAKE_DIRECTORY "${child_source}")
file(WRITE "${child_source}/CMakeLists.txt" "cmake_minimum_required(VERSION 3.30)\nproject(HostSelectionChild C CXX)\nfile(WRITE \"\${CMAKE_BINARY_DIR}/selected-tools.txt\" \"\${CMAKE_C_COMPILER}\n\${CMAKE_CXX_COMPILER}\n\${CMAKE_MAKE_PROGRAM}\n\")\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${child_source}" -B "${child_binary}" -G Ninja
    ${selected_arguments}
    RESULT_VARIABLE child_result OUTPUT_VARIABLE child_output ERROR_VARIABLE child_error)
if(NOT child_result EQUAL 0)
    message(FATAL_ERROR "Explicit native tool selection failed against conflicting environment hints: ${child_output}\n${child_error}")
endif()
file(STRINGS "${child_binary}/selected-tools.txt" actual_tools)
foreach(pair "0;${C_COMPILER}" "1;${CXX_COMPILER}" "2;${NINJA}")
    list(GET pair 0 index)
    list(GET pair 1 expected)
    list(GET actual_tools ${index} actual)
    cmake_path(NORMAL_PATH expected)
    cmake_path(NORMAL_PATH actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Native tool changed: expected ${expected}, got ${actual}")
    endif()
endforeach()
message(STATUS "Native host preserved the selected C/CXX compilers and Ninja despite conflicting CC/CXX")
