if(NOT EDITOR OR NOT WORK)
    message(FATAL_ERROR "EDITOR and WORK are required")
endif()
file(MAKE_DIRECTORY "${WORK}/root" "${WORK}/single" "${WORK}/working")
file(WRITE "${WORK}/root/content.json" "{\"version\":1,\"catalogs\":[\"fonts.json\",\"extra.json\"],\"shader_bundles\":[]}")
file(WRITE "${WORK}/root/fonts.json" "{\"version\":1,\"assets\":[{\"id\":\"font.default\",\"type\":\"font\",\"path\":\"font.bin\"}]}")
file(WRITE "${WORK}/root/extra.json" "{\"version\":1,\"assets\":[{\"id\":\"font.second\",\"type\":\"font\",\"path\":\"font.bin\"}]}")
file(WRITE "${WORK}/root/font.bin" "owned fake font")
file(READ "${CMAKE_CURRENT_LIST_DIR}/fixtures/minimal.ui.json" document)
string(REPLACE "\"default\": \"font.default\"" "\"default\": \"font.default\", \"second\": \"font.second\"" multi_document "${document}")
file(WRITE "${WORK}/multi.json" "${multi_document}")
file(WRITE "${WORK}/single.json" "${document}")
file(COPY "${WORK}/root/fonts.json" DESTINATION "${WORK}/single")
file(WRITE "${WORK}/single/asset_catalog.json" "{\"version\":1,\"assets\":[]}")
function(check expected label)
    execute_process(COMMAND "${EDITOR}" ${ARGN}
        WORKING_DIRECTORY "${WORK}/working" RESULT_VARIABLE actual
        OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
    if(NOT actual STREQUAL "${expected}")
        message(FATAL_ERROR "${label}: expected ${expected}, got ${actual}\n${output}\n${error}")
    endif()
endfunction()
check(0 multi_catalog --validate "${WORK}/multi.json" --asset-root "${WORK}/root")
check(4 partial_catalog --validate "${WORK}/multi.json" --asset-catalog "${WORK}/root/fonts.json")
check(0 explicit_catalog --validate "${WORK}/single.json" --asset-catalog "${WORK}/single/fonts.json")
check(0 explicit_root --validate "${WORK}/single.json" --asset-catalog "${WORK}/single/fonts.json" --asset-root "${WORK}/root")
check(3 no_fallback --validate "${WORK}/single.json" --asset-root "${WORK}/single")
file(WRITE "${WORK}/root/content.json" "broken manifest")
check(3 malformed_manifest --validate "${WORK}/single.json" --asset-root "${WORK}/root")
check(0 explicit_ignores_manifest --validate "${WORK}/single.json" --asset-root "${WORK}/root" --asset-catalog "${WORK}/root/fonts.json")
