// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: runtime_v1.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The local IPC host decodes this into product data. Match never sees protobuf,
// sessions, endpoints, or wire envelopes.
type Ready struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ArenaId               string                 `protobuf:"bytes,1,opt,name=arena_id,json=arenaId,proto3" json:"arena_id,omitempty"`
	ArenaVersion          uint32                 `protobuf:"varint,2,opt,name=arena_version,json=arenaVersion,proto3" json:"arena_version,omitempty"`
	TickRate              uint32                 `protobuf:"varint,3,opt,name=tick_rate,json=tickRate,proto3" json:"tick_rate,omitempty"`
	SnapshotIntervalTicks uint32                 `protobuf:"varint,4,opt,name=snapshot_interval_ticks,json=snapshotIntervalTicks,proto3" json:"snapshot_interval_ticks,omitempty"`
	MaxPlayers            uint32                 `protobuf:"varint,5,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_runtime_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Ready) GetArenaId() string {
	if x != nil {
		return x.ArenaId
	}
	return ""
}

func (x *Ready) GetArenaVersion() uint32 {
	if x != nil {
		return x.ArenaVersion
	}
	return 0
}

func (x *Ready) GetTickRate() uint32 {
	if x != nil {
		return x.TickRate
	}
	return 0
}

func (x *Ready) GetSnapshotIntervalTicks() uint32 {
	if x != nil {
		return x.SnapshotIntervalTicks
	}
	return 0
}

func (x *Ready) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

type PlayerJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoin) Reset() {
	*x = PlayerJoin{}
	mi := &file_runtime_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoin) ProtoMessage() {}

func (x *PlayerJoin) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoin.ProtoReflect.Descriptor instead.
func (*PlayerJoin) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerJoin) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type PlayerLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeave) Reset() {
	*x = PlayerLeave{}
	mi := &file_runtime_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeave) ProtoMessage() {}

func (x *PlayerLeave) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeave.ProtoReflect.Descriptor instead.
func (*PlayerLeave) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerLeave) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type PlayerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	InputSequence uint64                 `protobuf:"varint,2,opt,name=input_sequence,json=inputSequence,proto3" json:"input_sequence,omitempty"`
	ClientTick    uint64                 `protobuf:"varint,3,opt,name=client_tick,json=clientTick,proto3" json:"client_tick,omitempty"`
	MoveForward   float32                `protobuf:"fixed32,4,opt,name=move_forward,json=moveForward,proto3" json:"move_forward,omitempty"`
	MoveRight     float32                `protobuf:"fixed32,5,opt,name=move_right,json=moveRight,proto3" json:"move_right,omitempty"`
	Yaw           float32                `protobuf:"fixed32,6,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch         float32                `protobuf:"fixed32,7,opt,name=pitch,proto3" json:"pitch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_runtime_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerInput) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerInput) GetInputSequence() uint64 {
	if x != nil {
		return x.InputSequence
	}
	return 0
}

func (x *PlayerInput) GetClientTick() uint64 {
	if x != nil {
		return x.ClientTick
	}
	return 0
}

func (x *PlayerInput) GetMoveForward() float32 {
	if x != nil {
		return x.MoveForward
	}
	return 0
}

func (x *PlayerInput) GetMoveRight() float32 {
	if x != nil {
		return x.MoveRight
	}
	return 0
}

func (x *PlayerInput) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *PlayerInput) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

type JoinResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResult) Reset() {
	*x = JoinResult{}
	mi := &file_runtime_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResult) ProtoMessage() {}

func (x *JoinResult) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResult.ProtoReflect.Descriptor instead.
func (*JoinResult) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{4}
}

func (x *JoinResult) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *JoinResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *JoinResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PlayerState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PlayerId          uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X                 float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                 float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z                 float32                `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	Yaw               float32                `protobuf:"fixed32,5,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch             float32                `protobuf:"fixed32,6,opt,name=pitch,proto3" json:"pitch,omitempty"`
	LastInputSequence uint64                 `protobuf:"varint,7,opt,name=last_input_sequence,json=lastInputSequence,proto3" json:"last_input_sequence,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_runtime_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerState) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerState) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerState) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *PlayerState) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *PlayerState) GetLastInputSequence() uint64 {
	if x != nil {
		return x.LastInputSequence
	}
	return 0
}

type WorldSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Players       []*PlayerState         `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldSnapshot) Reset() {
	*x = WorldSnapshot{}
	mi := &file_runtime_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldSnapshot) ProtoMessage() {}

func (x *WorldSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldSnapshot.ProtoReflect.Descriptor instead.
func (*WorldSnapshot) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{6}
}

func (x *WorldSnapshot) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *WorldSnapshot) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

type RuntimeError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeError) Reset() {
	*x = RuntimeError{}
	mi := &file_runtime_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeError) ProtoMessage() {}

func (x *RuntimeError) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeError.ProtoReflect.Descriptor instead.
func (*RuntimeError) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{7}
}

func (x *RuntimeError) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *RuntimeError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RuntimeError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RuntimeEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*RuntimeEnvelope_Ready
	//	*RuntimeEnvelope_Join
	//	*RuntimeEnvelope_Leave
	//	*RuntimeEnvelope_Input
	//	*RuntimeEnvelope_JoinResult
	//	*RuntimeEnvelope_Error
	//	*RuntimeEnvelope_Snapshot
	Message       isRuntimeEnvelope_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeEnvelope) Reset() {
	*x = RuntimeEnvelope{}
	mi := &file_runtime_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEnvelope) ProtoMessage() {}

func (x *RuntimeEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEnvelope.ProtoReflect.Descriptor instead.
func (*RuntimeEnvelope) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{8}
}

func (x *RuntimeEnvelope) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *RuntimeEnvelope) GetMessage() isRuntimeEnvelope_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RuntimeEnvelope) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetJoin() *PlayerJoin {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetLeave() *PlayerLeave {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Leave); ok {
			return x.Leave
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetInput() *PlayerInput {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetJoinResult() *JoinResult {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_JoinResult); ok {
			return x.JoinResult
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetError() *RuntimeError {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetSnapshot() *WorldSnapshot {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

type isRuntimeEnvelope_Message interface {
	isRuntimeEnvelope_Message()
}

type RuntimeEnvelope_Ready struct {
	Ready *Ready `protobuf:"bytes,10,opt,name=ready,proto3,oneof"`
}

type RuntimeEnvelope_Join struct {
	Join *PlayerJoin `protobuf:"bytes,11,opt,name=join,proto3,oneof"`
}

type RuntimeEnvelope_Leave struct {
	Leave *PlayerLeave `protobuf:"bytes,12,opt,name=leave,proto3,oneof"`
}

type RuntimeEnvelope_Input struct {
	Input *PlayerInput `protobuf:"bytes,13,opt,name=input,proto3,oneof"`
}

type RuntimeEnvelope_JoinResult struct {
	JoinResult *JoinResult `protobuf:"bytes,14,opt,name=join_result,json=joinResult,proto3,oneof"`
}

type RuntimeEnvelope_Error struct {
	Error *RuntimeError `protobuf:"bytes,15,opt,name=error,proto3,oneof"`
}

type RuntimeEnvelope_Snapshot struct {
	Snapshot *WorldSnapshot `protobuf:"bytes,16,opt,name=snapshot,proto3,oneof"`
}

func (*RuntimeEnvelope_Ready) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Join) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Leave) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Input) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_JoinResult) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Error) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Snapshot) isRuntimeEnvelope_Message() {}

var File_runtime_v1_proto protoreflect.FileDescriptor

const file_runtime_v1_proto_rawDesc = "" +
	"\n" +
	"\x10runtime_v1.proto\x12\x19object_fps_pvp.runtime.v1\"\xbd\x01\n" +
	"\x05Ready\x12\x19\n" +
	"\barena_id\x18\x01 \x01(\tR\aarenaId\x12#\n" +
	"\rarena_version\x18\x02 \x01(\rR\farenaVersion\x12\x1b\n" +
	"\ttick_rate\x18\x03 \x01(\rR\btickRate\x126\n" +
	"\x17snapshot_interval_ticks\x18\x04 \x01(\rR\x15snapshotIntervalTicks\x12\x1f\n" +
	"\vmax_players\x18\x05 \x01(\rR\n" +
	"maxPlayers\")\n" +
	"\n" +
	"PlayerJoin\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\"*\n" +
	"\vPlayerLeave\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\"\xdc\x01\n" +
	"\vPlayerInput\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12%\n" +
	"\x0einput_sequence\x18\x02 \x01(\x04R\rinputSequence\x12\x1f\n" +
	"\vclient_tick\x18\x03 \x01(\x04R\n" +
	"clientTick\x12!\n" +
	"\fmove_forward\x18\x04 \x01(\x02R\vmoveForward\x12\x1d\n" +
	"\n" +
	"move_right\x18\x05 \x01(\x02R\tmoveRight\x12\x10\n" +
	"\x03yaw\x18\x06 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\a \x01(\x02R\x05pitch\"]\n" +
	"\n" +
	"JoinResult\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xac\x01\n" +
	"\vPlayerState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x02R\x01z\x12\x10\n" +
	"\x03yaw\x18\x05 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x06 \x01(\x02R\x05pitch\x12.\n" +
	"\x13last_input_sequence\x18\a \x01(\x04R\x11lastInputSequence\"e\n" +
	"\rWorldSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12@\n" +
	"\aplayers\x18\x02 \x03(\v2&.object_fps_pvp.runtime.v1.PlayerStateR\aplayers\"Y\n" +
	"\fRuntimeError\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x91\x04\n" +
	"\x0fRuntimeEnvelope\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x128\n" +
	"\x05ready\x18\n" +
	" \x01(\v2 .object_fps_pvp.runtime.v1.ReadyH\x00R\x05ready\x12;\n" +
	"\x04join\x18\v \x01(\v2%.object_fps_pvp.runtime.v1.PlayerJoinH\x00R\x04join\x12>\n" +
	"\x05leave\x18\f \x01(\v2&.object_fps_pvp.runtime.v1.PlayerLeaveH\x00R\x05leave\x12>\n" +
	"\x05input\x18\r \x01(\v2&.object_fps_pvp.runtime.v1.PlayerInputH\x00R\x05input\x12H\n" +
	"\vjoin_result\x18\x0e \x01(\v2%.object_fps_pvp.runtime.v1.JoinResultH\x00R\n" +
	"joinResult\x12?\n" +
	"\x05error\x18\x0f \x01(\v2'.object_fps_pvp.runtime.v1.RuntimeErrorH\x00R\x05error\x12F\n" +
	"\bsnapshot\x18\x10 \x01(\v2(.object_fps_pvp.runtime.v1.WorldSnapshotH\x00R\bsnapshotB\t\n" +
	"\amessageB-Z+gyo.local/object_fps_pvp/protocol/runtimev1b\x06proto3"

var (
	file_runtime_v1_proto_rawDescOnce sync.Once
	file_runtime_v1_proto_rawDescData []byte
)

func file_runtime_v1_proto_rawDescGZIP() []byte {
	file_runtime_v1_proto_rawDescOnce.Do(func() {
		file_runtime_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_proto_rawDesc), len(file_runtime_v1_proto_rawDesc)))
	})
	return file_runtime_v1_proto_rawDescData
}

var file_runtime_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_runtime_v1_proto_goTypes = []any{
	(*Ready)(nil),           // 0: object_fps_pvp.runtime.v1.Ready
	(*PlayerJoin)(nil),      // 1: object_fps_pvp.runtime.v1.PlayerJoin
	(*PlayerLeave)(nil),     // 2: object_fps_pvp.runtime.v1.PlayerLeave
	(*PlayerInput)(nil),     // 3: object_fps_pvp.runtime.v1.PlayerInput
	(*JoinResult)(nil),      // 4: object_fps_pvp.runtime.v1.JoinResult
	(*PlayerState)(nil),     // 5: object_fps_pvp.runtime.v1.PlayerState
	(*WorldSnapshot)(nil),   // 6: object_fps_pvp.runtime.v1.WorldSnapshot
	(*RuntimeError)(nil),    // 7: object_fps_pvp.runtime.v1.RuntimeError
	(*RuntimeEnvelope)(nil), // 8: object_fps_pvp.runtime.v1.RuntimeEnvelope
}
var file_runtime_v1_proto_depIdxs = []int32{
	5, // 0: object_fps_pvp.runtime.v1.WorldSnapshot.players:type_name -> object_fps_pvp.runtime.v1.PlayerState
	0, // 1: object_fps_pvp.runtime.v1.RuntimeEnvelope.ready:type_name -> object_fps_pvp.runtime.v1.Ready
	1, // 2: object_fps_pvp.runtime.v1.RuntimeEnvelope.join:type_name -> object_fps_pvp.runtime.v1.PlayerJoin
	2, // 3: object_fps_pvp.runtime.v1.RuntimeEnvelope.leave:type_name -> object_fps_pvp.runtime.v1.PlayerLeave
	3, // 4: object_fps_pvp.runtime.v1.RuntimeEnvelope.input:type_name -> object_fps_pvp.runtime.v1.PlayerInput
	4, // 5: object_fps_pvp.runtime.v1.RuntimeEnvelope.join_result:type_name -> object_fps_pvp.runtime.v1.JoinResult
	7, // 6: object_fps_pvp.runtime.v1.RuntimeEnvelope.error:type_name -> object_fps_pvp.runtime.v1.RuntimeError
	6, // 7: object_fps_pvp.runtime.v1.RuntimeEnvelope.snapshot:type_name -> object_fps_pvp.runtime.v1.WorldSnapshot
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_runtime_v1_proto_init() }
func file_runtime_v1_proto_init() {
	if File_runtime_v1_proto != nil {
		return
	}
	file_runtime_v1_proto_msgTypes[8].OneofWrappers = []any{
		(*RuntimeEnvelope_Ready)(nil),
		(*RuntimeEnvelope_Join)(nil),
		(*RuntimeEnvelope_Leave)(nil),
		(*RuntimeEnvelope_Input)(nil),
		(*RuntimeEnvelope_JoinResult)(nil),
		(*RuntimeEnvelope_Error)(nil),
		(*RuntimeEnvelope_Snapshot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_proto_rawDesc), len(file_runtime_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_runtime_v1_proto_goTypes,
		DependencyIndexes: file_runtime_v1_proto_depIdxs,
		MessageInfos:      file_runtime_v1_proto_msgTypes,
	}.Build()
	File_runtime_v1_proto = out.File
	file_runtime_v1_proto_goTypes = nil
	file_runtime_v1_proto_depIdxs = nil
}
