cmake_minimum_required(VERSION 3.30)
get_filename_component(repository "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
include("${repository}/build/cmake/GyoAcceptance.cmake")
set(manifest [=[{"executables":{"editor.main":{"path":"bin/editor"}}}]=])
if(DEFINED TOKEN)
    set(check "{\"command\":[\"${TOKEN}\"],\"platforms\":[\"${PLATFORM}\"]}")
    _gyo_acceptance_check_tokens("${check}" editor "${manifest}" linux-x64)
    return()
endif()
foreach(token "@EXECUTABLE:windows_only@" "@PROBE:windows_only@")
    set(check "{\"command\":[\"${token}\"],\"platforms\":[\"windows-x64\"]}")
    _gyo_acceptance_check_tokens("${check}" editor "${manifest}" linux-x64)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DTOKEN=${token}" -DPLATFORM=linux-x64
        -P "${CMAKE_CURRENT_LIST_FILE}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 15)
    if(result EQUAL 0 OR NOT "${out}${err}" MATCHES "role is not registered")
        message(FATAL_ERROR "Current platform accepted an absent role: ${token}: ${out}${err}")
    endif()
endforeach()
set(check [=[{"command":["@EXECUTABLE:main@"],"platforms":["linux-x64"]}]=])
_gyo_acceptance_check_tokens("${check}" editor "${manifest}" linux-x64)
execute_process(COMMAND "${CMAKE_COMMAND}" -DTOKEN=@EXECUTABLE@ -DPLATFORM=windows-x64
    -P "${CMAKE_CURRENT_LIST_FILE}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 15)
if(result EQUAL 0 OR NOT "${out}${err}" MATCHES "Unknown acceptance token")
    message(FATAL_ERROR "Foreign-platform token syntax escaped validation: ${out}${err}")
endif()
message(STATUS "Acceptance tokens: platform-specific roles and universal syntax checks passed")
