cmake_minimum_required(VERSION 3.30)
# A synthetic app declares a Go service: the helper registers the role, the
# explicit host target, label-only Go tests and the gyo-build.json record.
# Pass -DGO_EXECUTABLE=<go> to also build the host target with a real Go.
get_filename_component(repository "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
string(RANDOM LENGTH 8 ALPHABET abcdef0123456789 run_id)
set(work "${CMAKE_CURRENT_BINARY_DIR}/go-service-${run_id}")
set(source "${work}/source")
set(binary "${work}/binary")
file(MAKE_DIRECTORY "${source}/apps/sample/cmd/service" "${source}/apps/plain" "${source}/shared")
file(WRITE "${source}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.30)
project(GoServiceFixture NONE)
set(GYO_REPOSITORY_ROOT "${CMAKE_CURRENT_SOURCE_DIR}")
set(GYO_OUTPUT_ROOT "${CMAKE_CURRENT_BINARY_DIR}/products")
set(BUILD_TESTING ON)
enable_testing()
include("${GYO_TEST_REPOSITORY}/build/cmake/GyoAppProject.cmake")
# Registry columns windows,linux,macos; a Go service owner must support Linux.
set(sample_platforms 1,1,0)
if(TEST_CASE STREQUAL "linux_disabled")
    set(sample_platforms 1,0,1)
endif()
set(registry "${CMAKE_CURRENT_BINARY_DIR}/projects.csv")
file(WRITE "${registry}" "name,description,version,enabled,windows,linux,macos\nsample,,,1,${sample_platforms}\nplain,,,1,1,1,1\n")
gyo_read_app_registry("${registry}" GYO_APP_REGISTRY_DATA)
gyo_register_go_module(OWNER engine DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/shared")
if(TEST_CASE STREQUAL "outside_app")
    gyo_app_add_go_service(gateway PACKAGE ./cmd/service PLATFORMS linux-x64)
endif()
foreach(GYO_CURRENT_APP sample plain)
    add_subdirectory("apps/${GYO_CURRENT_APP}")
endforeach()
gyo_go_build_record(modules services)
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/record.json" "{\"go_modules\":${modules},\"go_services\":${services}}\n")
]=])
set(project_json "{\"version\":1,\"display_name\":\"Fixture\",\"components\":[]}\n")
foreach(app sample plain)
    file(WRITE "${source}/apps/${app}/project.json" "${project_json}")
endforeach()
file(WRITE "${source}/apps/sample/CMakeLists.txt" [=[
gyo_app_project()
set(platforms linux-x64 windows-x64)
set(package ./cmd/service)
if(TEST_CASE STREQUAL "unknown_platform")
    set(platforms linux-x64 solaris-sparc)
elseif(TEST_CASE STREQUAL "unregistered_platform")
    set(platforms linux-x64 macos-arm64)
elseif(TEST_CASE STREQUAL "duplicate_platform")
    set(platforms linux-x64 linux-x64)
elseif(TEST_CASE STREQUAL "escaping_package")
    set(package ./../cmd)
elseif(TEST_CASE STREQUAL "absolute_package")
    set(package /cmd/service)
endif()
gyo_app_add_go_service(gateway PACKAGE ${package} PLATFORMS ${platforms} OUT_TARGET gateway)
if(NOT gateway STREQUAL "gyo_sample-gateway" OR NOT TARGET gyo_sample-gateway)
    message(FATAL_ERROR "Unexpected Go service target: ${gateway}")
endif()
gyo_get_app_target(sample gateway lookup)
if(NOT lookup STREQUAL gateway)
    message(FATAL_ERROR "Go service role was not registered")
endif()
if(TEST_CASE STREQUAL "duplicate_role")
    gyo_app_add_go_service(gateway PACKAGE ./cmd/service PLATFORMS linux-x64)
endif()
]=])
# An app without a go.mod cannot declare a Go service; a plain app records nothing.
file(WRITE "${source}/apps/plain/CMakeLists.txt" [=[
gyo_app_project()
if(TEST_CASE STREQUAL "missing_module")
    gyo_app_add_go_service(gateway PACKAGE ./cmd PLATFORMS linux-x64)
endif()
]=])
file(WRITE "${source}/apps/sample/go.mod" "module example.invalid/sample\n\ngo 1.21\n")
file(WRITE "${source}/apps/sample/cmd/service/main.go" "package main\n\nfunc main() {}\n")
file(WRITE "${source}/shared/go.mod" "module example.invalid/shared\n\ngo 1.21\n")

set(configure_args "-DGYO_TEST_REPOSITORY=${repository}")
if(GENERATOR)
    list(APPEND configure_args -G "${GENERATOR}")
endif()
if(MAKE_PROGRAM)
    list(APPEND configure_args "-DCMAKE_MAKE_PROGRAM=${MAKE_PROGRAM}")
endif()
if(GO_EXECUTABLE)
    list(APPEND configure_args "-DGYO_GO_EXECUTABLE=${GO_EXECUTABLE}")
endif()

function(run success fragment)
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 180)
    if(success AND NOT result EQUAL 0)
        message(FATAL_ERROR "Fixture command failed (${result}): ${ARGN}\n${stdout}\n${stderr}")
    elseif(NOT success AND result EQUAL 0)
        message(FATAL_ERROR "Invalid fixture unexpectedly succeeded: ${ARGN}")
    endif()
    if(NOT fragment STREQUAL "")
        # CMake wraps long diagnostics, so compare with collapsed whitespace.
        string(REGEX REPLACE "[ \t\r\n]+" " " flattened "${stdout} ${stderr}")
        string(FIND "${flattened}" "${fragment}" position)
        if(position LESS 0)
            message(FATAL_ERROR "Expected '${fragment}': ${stdout}\n${stderr}")
        endif()
    endif()
    set(output "${stdout}" PARENT_SCOPE)
endfunction()

run(TRUE "" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" ${configure_args} -DTEST_CASE=valid)
file(READ "${binary}/record.json" record)
string(JSON module_count LENGTH "${record}" go_modules)
string(JSON engine_owner GET "${record}" go_modules 0 owner)
string(JSON engine_path GET "${record}" go_modules 0 path)
string(JSON app_owner GET "${record}" go_modules 1 owner)
string(JSON app_path GET "${record}" go_modules 1 path)
if(NOT module_count EQUAL 2 OR NOT engine_owner STREQUAL engine OR NOT engine_path STREQUAL shared
    OR NOT app_owner STREQUAL sample OR NOT app_path STREQUAL apps/sample)
    message(FATAL_ERROR "Unexpected Go module record: ${record}")
endif()
string(JSON service_count LENGTH "${record}" go_services)
string(JSON service GET "${record}" go_services 0)
string(JSON service_owner GET "${service}" owner)
string(JSON service_role GET "${service}" role)
string(JSON service_module GET "${service}" module)
string(JSON service_package GET "${service}" package)
string(JSON platform_count LENGTH "${service}" platforms)
string(JSON first_platform GET "${service}" platforms 0)
string(JSON second_platform GET "${service}" platforms 1)
if(NOT service_count EQUAL 1 OR NOT service_owner STREQUAL sample OR NOT service_role STREQUAL gateway
    OR NOT service_module STREQUAL apps/sample OR NOT service_package STREQUAL ./cmd/service
    OR NOT platform_count EQUAL 2 OR NOT first_platform STREQUAL linux-x64 OR NOT second_platform STREQUAL windows-x64)
    message(FATAL_ERROR "Unexpected Go service record: ${record}")
endif()

# Only the product module gets CTest checks, all under the dedicated label;
# the cpu|shader test presets therefore never require Go.
run(TRUE "" "${CMAKE_CTEST_COMMAND}" --test-dir "${binary}" -N -L go)
set(expected sample.go.vet sample.go.test)
if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    list(APPEND expected sample.go.race)
endif()
string(REGEX MATCHALL "Test +#[0-9]+: [^\n]+" listed "${output}")
list(TRANSFORM listed REPLACE "Test +#[0-9]+: " "")
if(NOT listed STREQUAL expected)
    message(FATAL_ERROR "Unexpected Go tests '${listed}', expected '${expected}'")
endif()
run(TRUE "" "${CMAKE_CTEST_COMMAND}" --test-dir "${binary}" -N -LE go)
if(NOT output MATCHES "Total Tests: 0")
    message(FATAL_ERROR "Go tests must carry only the go label: ${output}")
endif()

if(GO_EXECUTABLE)
    run(TRUE "" "${CMAKE_COMMAND}" --build "${binary}" --target gyo_sample-gateway)
    if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
        set(suffix .exe)
    endif()
    if(NOT EXISTS "${binary}/products/_services/sample/bin/gyo_sample-gateway${suffix}")
        message(FATAL_ERROR "The host Go service build was not staged under _services/<app>/bin")
    endif()
    run(TRUE "" "${CMAKE_CTEST_COMMAND}" --test-dir "${binary}" -L go --output-on-failure)
endif()

foreach(case "unknown_platform|Unknown or duplicate Go service platform"
             "duplicate_platform|Unknown or duplicate Go service platform"
             "unregistered_platform|platform 'macos-arm64' is not enabled for the app in the registry"
             "linux_disabled|requires its app to be Linux-enabled in the registry"
             "escaping_package|module-relative ./ path"
             "absolute_package|module-relative ./ path"
             "duplicate_role|Duplicate app target role"
             "missing_module|has no go.mod"
             "outside_app|Call gyo_app_project()")
    string(REPLACE "|" ";" fields "${case}")
    list(GET fields 0 name)
    list(GET fields 1 fragment)
    run(FALSE "${fragment}" "${CMAKE_COMMAND}" -S "${source}" -B "${work}/${name}" ${configure_args} -DTEST_CASE=${name})
endforeach()
file(REMOVE_RECURSE "${work}")
