cmake_minimum_required(VERSION 3.30)
get_filename_component(repository "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
set(work "${CMAKE_CURRENT_BINARY_DIR}/project-composition")
set(source "${work}/source")
set(binary "${work}/binary")
file(MAKE_DIRECTORY "${source}/engine/config" "${source}/apps/first"
    "${source}/apps/second" "${source}/apps/unregistered" "${source}/build")
# Assetless games still synchronize an empty content set through shared build
# support; the copied source root deliberately contains no CI or test code.
file(COPY "${repository}/build/assemble_runtime.py" "${repository}/build/content_contract.py"
    DESTINATION "${source}/build")
set(header "name,description,version,enabled,windows,linux,macos\n")
set(registry "${source}/engine/config/projects.csv")
file(WRITE "${registry}" "${header}first,,,1,1,1,1\nsecond,,,1,1,1,1\n")
file(WRITE "${source}/apps/unregistered/CMakeLists.txt" "message(FATAL_ERROR \"Unregistered app was inspected\")\n")
file(WRITE "${source}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.30)
project(ProjectCompositionFixture LANGUAGES CXX)
set(GYO_REPOSITORY_ROOT "${CMAKE_CURRENT_SOURCE_DIR}")
set(GYO_OUTPUT_ROOT "${CMAKE_CURRENT_BINARY_DIR}/products")
set(GYO_BUILD_UI_EDITOR "${WITH_TOOL}")
set(BUILD_TESTING OFF)
set(GYO_ENABLE_PACKAGING ON)
include("${GYO_TEST_REPOSITORY}/build/cmake/GyoApps.cmake")
include("${GYO_TEST_REPOSITORY}/build/cmake/GyoAppProject.cmake")
include("${GYO_TEST_REPOSITORY}/build/cmake/GyoPackaging.cmake")
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/configured.txt" "")
gyo_configure_apps()
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/selection.txt" "${GYO_ACTIVE_APPS}")
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/requirements.txt" "${GYO_REQUESTED_COMPONENTS}")
foreach(GYO_CURRENT_APP IN LISTS GYO_ACTIVE_APPS)
    add_subdirectory("apps/${GYO_CURRENT_APP}")
endforeach()
if(WITH_TOOL)
    add_executable(fixture_editor tools/ui_editor/main.cpp)
    gyo_install_product_target(TARGET fixture_editor PRODUCT toolchain KIND toolchain ROLE ui_editor)
endif()
gyo_finalize_product_packages()
]=])
set(project_json "{\"version\":1,\"display_name\":\"Fixture game\",\"components\":[]}\n")
set(app_cmake [=[
file(APPEND "${PROJECT_BINARY_DIR}/configured.txt" "${GYO_CURRENT_APP}\n")
gyo_app_project()
gyo_app_add_library(domain OUT_TARGET domain SOURCES domain.cpp)
gyo_app_add_executable(main MAIN OUT_TARGET app SOURCES main.cpp LIBRARIES ${domain})
gyo_get_app_target("${GYO_CURRENT_APP}" domain lookup)
if(NOT lookup STREQUAL domain)
    message(FATAL_ERROR "Independent support could not locate the game domain")
endif()
get_target_property(includes ${domain} INTERFACE_INCLUDE_DIRECTORIES)
if("${GYO_APP_GENERATED_INCLUDE_DIR}" IN_LIST includes)
    message(FATAL_ERROR "Generated game identity leaked through public includes")
endif()
file(GENERATE OUTPUT "${PROJECT_BINARY_DIR}/${GYO_CURRENT_APP}-$<CONFIG>.txt" CONTENT "$<TARGET_FILE:${app}>")
]=])
foreach(app first second)
    file(WRITE "${source}/apps/${app}/project.json" "${project_json}")
    file(WRITE "${source}/apps/${app}/CMakeLists.txt" "${app_cmake}")
    file(WRITE "${source}/apps/${app}/domain.cpp"
        "#include <gyo/AppConfig.hpp>\nconst char* identity() { return Gyo::AppConfig::Id; }\n")
    file(WRITE "${source}/apps/${app}/main.cpp"
        "#include <gyo/AppConfig.hpp>\n#include <iostream>\nconst char* identity();\nint main() { std::cout << identity() << ' ' << Gyo::AppConfig::Assets; }\n")
endforeach()

set(configure_args "-DGYO_TEST_REPOSITORY=${repository}" -DCMAKE_BUILD_TYPE=Debug)
foreach(pair GENERATOR MAKE_PROGRAM PLATFORM CXX_COMPILER)
    if(${pair})
        if(pair STREQUAL "GENERATOR")
            list(APPEND configure_args -G "${GENERATOR}")
        elseif(pair STREQUAL "PLATFORM")
            list(APPEND configure_args -A "${PLATFORM}")
        elseif(pair STREQUAL "MAKE_PROGRAM")
            list(APPEND configure_args "-DCMAKE_MAKE_PROGRAM=${MAKE_PROGRAM}")
        else()
            list(APPEND configure_args "-DCMAKE_CXX_COMPILER=${CXX_COMPILER}")
        endif()
    endif()
endforeach()

function(run success fragment)
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 90)
    if(success AND NOT result EQUAL 0)
        message(FATAL_ERROR "Fixture command failed: ${ARGN}\n${stdout}\n${stderr}")
    elseif(NOT success AND result EQUAL 0)
        message(FATAL_ERROR "Invalid fixture unexpectedly succeeded: ${ARGN}")
    endif()
    if(NOT fragment STREQUAL "")
        string(FIND "${stdout}\n${stderr}" "${fragment}" position)
        if(position LESS 0)
            message(FATAL_ERROR "Expected '${fragment}': ${stdout}\n${stderr}")
        endif()
    endif()
endfunction()

run(TRUE "" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" ${configure_args} -DGYO_APPS=AUTO -DWITH_TOOL=OFF)
file(READ "${binary}/configured.txt" configured)
if(NOT configured STREQUAL "first\nsecond\n")
    message(FATAL_ERROR "App CMake ran more than once or selected an unregistered directory: ${configured}")
endif()
run(TRUE "" "${CMAKE_COMMAND}" --build "${binary}" --config Debug --parallel 2)
foreach(app first second)
    file(READ "${binary}/${app}-Debug.txt" executable)
    run(TRUE "${app} assets/${app}" "${executable}")
    set(stage "${work}/stage-${app}")
    run(TRUE "" "${CMAKE_COMMAND}" --install "${binary}" --config Debug --component "${app}" --prefix "${stage}")
    file(READ "${stage}/share/gyo/products/${app}/manifest.json" manifest)
    string(JSON version GET "${manifest}" schema_version)
    string(JSON identity GET "${manifest}" product)
    string(JSON checks LENGTH "${manifest}" checks)
    if(NOT version EQUAL 2 OR NOT identity STREQUAL app OR NOT checks EQUAL 0)
        message(FATAL_ERROR "Copied game acquired the wrong package contract: ${manifest}")
    endif()
    file(GLOB installed "${stage}/bin/*")
    list(LENGTH installed count)
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "Game package includes another product or support code: ${installed}")
    endif()
endforeach()

# A compilation error in any selected game fails the complete graph.
file(READ "${source}/apps/second/main.cpp" original_main)
file(WRITE "${source}/apps/second/main.cpp" "#error selected game compilation failure\n")
run(FALSE "selected game compilation failure" "${CMAKE_COMMAND}" --build "${binary}" --config Debug)
file(WRITE "${source}/apps/second/main.cpp" "${original_main}")

# CSV edits regenerate selection without directory discovery or stale targets.
file(WRITE "${registry}" "${header}first,,,0,1,1,1\nsecond,,,1,1,1,1\n")
run(TRUE "" "${CMAKE_COMMAND}" --build "${binary}" --config Debug)
file(READ "${binary}/selection.txt" selected)
if(NOT selected STREQUAL second)
    message(FATAL_ERROR "CSV-only edit did not update selection: ${selected}")
endif()
run(FALSE "" "${CMAKE_COMMAND}" --build "${binary}" --config Debug --target gyo_first)
run(FALSE "disabled" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -DGYO_APPS=first)

# Invalid metadata is rejected before a game executes arbitrary CMake.
file(WRITE "${source}/apps/second/project.json" "{\"version\":1,\"components\":[\"UNKNOWN\"]}")
run(FALSE "Unknown GYO component" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -DGYO_APPS=second)
file(WRITE "${source}/apps/second/project.json" "${project_json}")

# The fixed toolchain needs no games. Its acceptance contract stays outside tool code.
file(MAKE_DIRECTORY "${source}/tools/ui_editor")
file(WRITE "${source}/tools/ui_editor/project.json" "${project_json}")
file(WRITE "${source}/tools/ui_editor/main.cpp" "int main() { return 0; }\n")
file(MAKE_DIRECTORY "${source}/build/acceptance/ui_editor")
file(WRITE "${source}/build/acceptance/ui_editor/checks.json" [=[
{"version":1,"checks":[{"name":"editor_cli","command":["@EXECUTABLE@"],"environment":[],"profiles":["quick","release"],"platforms":["windows-x64","linux-x64","macos-arm64"],"gpu":false,"timeout":10}]}
]=])
file(WRITE "${registry}" "${header}")
file(RENAME "${source}/apps" "${source}/unused-apps")
run(TRUE "" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -DGYO_APPS=AUTO -DWITH_TOOL=ON)
run(TRUE "" "${CMAKE_COMMAND}" --build "${binary}" --config Debug)
run(TRUE "" "${CMAKE_COMMAND}" --install "${binary}" --config Debug --component toolchain --prefix "${work}/stage-toolchain")
file(READ "${work}/stage-toolchain/share/gyo/products/toolchain/manifest.json" manifest)
string(JSON kind GET "${manifest}" kind)
string(JSON tool GET "${manifest}" executables ui_editor)
if(NOT kind STREQUAL toolchain OR tool STREQUAL "")
    message(FATAL_ERROR "No-app build did not produce a toolchain: ${manifest}")
endif()
file(RENAME "${source}/unused-apps" "${source}/apps")
message(STATUS "Project composition: single-pass CMake, copied identities, isolated packages and no-app toolchain passed")
