cmake_minimum_required(VERSION 3.30)
get_filename_component(repository "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
string(RANDOM LENGTH 8 ALPHABET abcdef0123456789 run_id)
set(work "${CMAKE_CURRENT_BINARY_DIR}/project-composition-${run_id}")
set(source "${work}/source")
set(binary "${work}/binary")
file(MAKE_DIRECTORY "${source}/engine/config" "${source}/apps/first"
    "${source}/apps/second" "${source}/apps/unregistered" "${source}/build")
# Assetless games still synchronize an empty content set through shared build
# support; the copied source root deliberately contains no CI or test code.
file(COPY "${repository}/build/assemble_runtime.py" "${repository}/build/content_contract.py"
    DESTINATION "${source}/build")
set(header "name,description,version,enabled,windows,linux,macos\n")
set(registry "${source}/engine/config/projects.csv")
file(WRITE "${registry}" "${header}first,,,1,1,1,1\nsecond,,,1,1,1,1\n")
file(WRITE "${source}/apps/unregistered/CMakeLists.txt" "message(FATAL_ERROR \"Unregistered app was inspected\")\n")
file(WRITE "${source}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.30)
project(ProjectCompositionFixture LANGUAGES CXX)
set(GYO_REPOSITORY_ROOT "${CMAKE_CURRENT_SOURCE_DIR}")
set(GYO_OUTPUT_ROOT "${CMAKE_CURRENT_BINARY_DIR}/products")

set(BUILD_TESTING OFF)
set(GYO_ENABLE_PACKAGING ON)
include("${GYO_TEST_REPOSITORY}/build/cmake/GyoApps.cmake")
include("${GYO_TEST_REPOSITORY}/build/cmake/GyoTools.cmake")
include("${GYO_TEST_REPOSITORY}/build/cmake/GyoAppProject.cmake")
include("${GYO_TEST_REPOSITORY}/build/cmake/GyoPackaging.cmake")
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/configured.txt" "")
gyo_configure_apps()
gyo_configure_tools()
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/selection.txt" "${GYO_ACTIVE_APPS}")
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/requirements.txt" "${GYO_REQUESTED_COMPONENTS}")
foreach(GYO_CURRENT_APP IN LISTS GYO_ACTIVE_APPS)
    add_subdirectory("apps/${GYO_CURRENT_APP}")
endforeach()
if(TEST_MIXED_APP_CONFIG)
    add_executable(mixed_config apps/first/main.cpp)
    gyo_use_app_config(mixed_config first)
    gyo_use_app_config(mixed_config second)
endif()
foreach(GYO_CURRENT_TOOL IN LISTS GYO_ACTIVE_TOOLS)
    get_property(GYO_TOOL_VARIANT GLOBAL PROPERTY GYO_TOOL_${GYO_CURRENT_TOOL}_VARIANT)
    add_subdirectory("tools/${GYO_CURRENT_TOOL}")
endforeach()
gyo_finalize_product_packages()
]=])
set(project_json "{\"version\":1,\"display_name\":\"Fixture game\",\"components\":[]}\n")
set(app_cmake [=[
file(APPEND "${PROJECT_BINARY_DIR}/configured.txt" "${GYO_CURRENT_APP}\n")
gyo_app_project()
gyo_app_add_library(domain OUT_TARGET domain SOURCES domain.cpp)
gyo_app_add_executable(main MAIN OUT_TARGET app SOURCES main.cpp LIBRARIES ${domain})
gyo_get_app_target("${GYO_CURRENT_APP}" domain lookup)
if(NOT lookup STREQUAL domain)
    message(FATAL_ERROR "Independent support could not locate the game domain")
endif()
get_target_property(includes ${domain} INTERFACE_INCLUDE_DIRECTORIES)
if("${GYO_APP_GENERATED_INCLUDE_DIR}" IN_LIST includes)
    message(FATAL_ERROR "Generated game identity leaked through public includes")
endif()
file(GENERATE OUTPUT "${PROJECT_BINARY_DIR}/${GYO_CURRENT_APP}-$<CONFIG>.txt" CONTENT "$<TARGET_FILE:${app}>")
]=])
foreach(app first second)
    file(WRITE "${source}/apps/${app}/project.json" "${project_json}")
    file(WRITE "${source}/apps/${app}/CMakeLists.txt" "${app_cmake}")
    file(WRITE "${source}/apps/${app}/domain.cpp"
        "#include <gyo/AppConfig.hpp>\nconst char* identity() { return Gyo::AppConfig::Id; }\n")
    file(WRITE "${source}/apps/${app}/main.cpp"
        "#include <gyo/AppConfig.hpp>\n#include <iostream>\nconst char* identity();\nint main() { std::cout << identity() << ' ' << Gyo::AppConfig::Assets; }\n")
endforeach()

set(configure_args "-DGYO_TEST_REPOSITORY=${repository}" -DCMAKE_BUILD_TYPE=Debug)
foreach(pair GENERATOR MAKE_PROGRAM PLATFORM CXX_COMPILER)
    if(${pair})
        if(pair STREQUAL "GENERATOR")
            list(APPEND configure_args -G "${GENERATOR}")
        elseif(pair STREQUAL "PLATFORM")
            list(APPEND configure_args -A "${PLATFORM}")
        elseif(pair STREQUAL "MAKE_PROGRAM")
            list(APPEND configure_args "-DCMAKE_MAKE_PROGRAM=${MAKE_PROGRAM}")
        else()
            list(APPEND configure_args "-DCMAKE_CXX_COMPILER=${CXX_COMPILER}")
        endif()
    endif()
endforeach()

function(run success fragment)
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 180)
    if(success AND NOT result EQUAL 0)
        message(FATAL_ERROR "Fixture command failed (${result}): ${ARGN}\n${stdout}\n${stderr}")
    elseif(NOT success AND result EQUAL 0)
        message(FATAL_ERROR "Invalid fixture unexpectedly succeeded: ${ARGN}")
    endif()
    if(NOT fragment STREQUAL "")
        string(FIND "${stdout}\n${stderr}" "${fragment}" position)
        if(position LESS 0)
            message(FATAL_ERROR "Expected '${fragment}': ${stdout}\n${stderr}")
        endif()
    endif()
endfunction()

run(TRUE "" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" ${configure_args} -DGYO_APPS=AUTO -DGYO_TOOLS=)
file(READ "${binary}/configured.txt" configured)
if(NOT configured STREQUAL "first\nsecond\n")
    message(FATAL_ERROR "App CMake ran more than once or selected an unregistered directory: ${configured}")
endif()
run(TRUE "" "${CMAKE_COMMAND}" --build "${binary}" --config Debug --parallel 2)
foreach(app first second)
    file(READ "${binary}/${app}-Debug.txt" executable)
    run(TRUE "${app} assets/${app}" "${executable}")
    set(stage "${work}/stage-${app}")
    run(TRUE "" "${CMAKE_COMMAND}" --install "${binary}" --config Debug --component "${app}" --prefix "${stage}")
    file(READ "${stage}/share/gyo/products/${app}/manifest.json" manifest)
    string(JSON version GET "${manifest}" schema_version)
    string(JSON identity GET "${manifest}" product)
    string(JSON checks LENGTH "${manifest}" checks)
    if(NOT version EQUAL 3 OR NOT identity STREQUAL app OR NOT checks EQUAL 0)
        message(FATAL_ERROR "Copied game acquired the wrong package contract: ${manifest}")
    endif()
    file(GLOB installed "${stage}/bin/*")
    list(LENGTH installed count)
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "Game package includes another product or support code: ${installed}")
    endif()
endforeach()

# A compilation error in any selected game fails the complete graph.
file(READ "${source}/apps/second/main.cpp" original_main)
file(WRITE "${source}/apps/second/main.cpp" "#error selected game compilation failure\n")
run(FALSE "selected game compilation failure" "${CMAKE_COMMAND}" --build "${binary}" --config Debug)
file(WRITE "${source}/apps/second/main.cpp" "${original_main}")

# CSV edits regenerate selection without directory discovery or stale targets.
file(WRITE "${registry}" "${header}first,,,0,1,1,1\nsecond,,,1,1,1,1\n")
run(TRUE "" "${CMAKE_COMMAND}" --build "${binary}" --config Debug)
file(READ "${binary}/selection.txt" selected)
if(NOT selected STREQUAL second)
    message(FATAL_ERROR "CSV-only edit did not update selection: ${selected}")
endif()
run(FALSE "" "${CMAKE_COMMAND}" --build "${binary}" --config Debug --target gyo_first)
run(FALSE "disabled" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -DGYO_APPS=first)

# Invalid metadata is rejected before a game executes arbitrary CMake.
file(WRITE "${source}/apps/second/project.json" "{\"version\":1,\"components\":[\"UNKNOWN\"]}")
run(FALSE "Unknown GYO component" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -DGYO_APPS=second)
file(WRITE "${source}/apps/second/project.json" "${project_json}")

# Two unrelated tools compose without app sources or concrete central branches.
set(tool_header "name,description,version,enabled,default,release,windows,linux,macos\n")
file(WRITE "${source}/engine/config/tools.csv" "${tool_header}canvas,,,1,1,1,1,1,1\npacker,,,1,1,1,1,1,1\n")
foreach(tool canvas packer)
    file(MAKE_DIRECTORY "${source}/tools/${tool}" "${source}/build/acceptance/${tool}")
    file(WRITE "${source}/tools/${tool}/project.json" [=[
{"version":1,"default_variant":"normal","requires_apps":{},"variants":{"normal":{"components":[],"packageable":true}}}
]=])
    file(WRITE "${source}/tools/${tool}/main.cpp" "int main() { return 0; }\n")
    file(WRITE "${source}/tools/${tool}/CMakeLists.txt" [=[
add_executable(${GYO_CURRENT_TOOL} main.cpp)
if(NOT TEST_UNREGISTERED_TOOL)
    gyo_tool_install_target(TARGET ${GYO_CURRENT_TOOL} ROLE main)
endif()
if(TEST_DUPLICATE_ROLE)
    gyo_tool_install_target(TARGET ${GYO_CURRENT_TOOL} ROLE main)
endif()
if(TEST_OUTPUT_COLLISION)
    set_target_properties(${GYO_CURRENT_TOOL} PROPERTIES OUTPUT_NAME shared-output)
endif()
]=])
    file(WRITE "${source}/build/acceptance/${tool}/checks.json" [=[
{"version":1,"checks":[{"name":"startup","command":["@EXECUTABLE:main@"],"environment":[],"profiles":["quick","release"],"platforms":["windows-x64","linux-x64","macos-arm64"],"gpu":false,"timeout":10}]}
]=])
endforeach()
# An app config is private and cannot be mixed with another app on one target.
file(WRITE "${registry}" "${header}first,,,1,1,1,1\nsecond,,,1,1,1,1\n")
run(FALSE "multiple app configurations" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -DGYO_APPS=AUTO -DTEST_MIXED_APP_CONFIG=ON)
file(WRITE "${registry}" "${header}")
file(RENAME "${source}/apps" "${source}/unused-apps")
run(TRUE "" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -DGYO_APPS=AUTO -DGYO_TOOLS=AUTO -DTEST_MIXED_APP_CONFIG=OFF)
run(TRUE "" "${CMAKE_COMMAND}" --build "${binary}" --config Debug)
run(TRUE "" "${CMAKE_COMMAND}" --install "${binary}" --config Debug --component toolchain --prefix "${work}/stage-toolchain")
file(READ "${work}/stage-toolchain/share/gyo/products/toolchain/manifest.json" manifest)
string(JSON kind GET "${manifest}" kind)
string(JSON count LENGTH "${manifest}" executables)
string(JSON tool GET "${manifest}" executables packer.main owner)
string(JSON checks LENGTH "${manifest}" checks)
if(NOT kind STREQUAL toolchain OR NOT count EQUAL 2 OR NOT tool STREQUAL packer OR NOT checks EQUAL 2)
    message(FATAL_ERROR "No-app multi-tool build did not produce independent contracts: ${manifest}")
endif()
file(WRITE "${source}/tools/packer/main.cpp" "#error selected tool compilation failure\n")
run(FALSE "selected tool compilation failure" "${CMAKE_COMMAND}" --build "${binary}" --config Debug)
file(WRITE "${source}/tools/packer/main.cpp" "int main() { return 0; }\n")
run(FALSE "Duplicate tool role" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -DTEST_DUPLICATE_ROLE=ON)
run(FALSE "did not register" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -DTEST_DUPLICATE_ROLE=OFF -DTEST_UNREGISTERED_TOOL=ON)
run(TRUE "" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -DTEST_UNREGISTERED_TOOL=OFF -DTEST_OUTPUT_COLLISION=ON)
run(FALSE "" "${CMAKE_COMMAND}" --build "${binary}" --config Debug)
run(FALSE "output collision" "${CMAKE_COMMAND}" --install "${binary}" --config Debug --component toolchain --prefix "${work}/collision-stage")
run(TRUE "" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -DTEST_OUTPUT_COLLISION=OFF -DGYO_TOOLS=canvas)
run(TRUE "" "${CMAKE_COMMAND}" --build "${binary}" --config Debug)
run(TRUE "" "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -DGYO_TOOLS=)
run(TRUE "" "${CMAKE_COMMAND}" --build "${binary}" --config Debug)
run(FALSE "" "${CMAKE_COMMAND}" --build "${binary}" --config Debug --target canvas)
file(RENAME "${source}/unused-apps" "${source}/apps")
message(STATUS "Project composition: app isolation, zero/one/multiple tools, contract ownership and failure propagation passed")
