cmake_minimum_required(VERSION 3.30)

# Test the real policy without a compiler, SDK, dependency fetch or GPU.
# Child processes isolate CACHE entries and include_guard(GLOBAL).
get_filename_component(_repository "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)

if(DEFINED GYO_POLICY_TEST_CASE)
    set(GYO_REQUIRE_SDL_GPU ON)
    set(GYO_BUILD_SDL_GPU_BACKEND OFF)
    set(GYO_RENDER_DEVICE AUTO)
    set(GYO_GPU_DRIVER AUTO)
    set(GYO_SHADER_BUNDLE AUTO)
    set(CMAKE_SYSTEM_NAME Windows)
    # Deliberately different from the target: decisions must use target OS.
    set(CMAKE_HOST_SYSTEM_NAME Linux)
    set(_expected_enabled ON)
    set(_expected_formats "dxil;spirv")
    set(_expected_driver auto)

    if(GYO_POLICY_TEST_CASE STREQUAL "auto-linux")
        set(CMAKE_SYSTEM_NAME Linux)
        set(CMAKE_HOST_SYSTEM_NAME Windows)
        set(_expected_formats spirv)
    elseif(GYO_POLICY_TEST_CASE STREQUAL "auto-macos")
        set(CMAKE_SYSTEM_NAME Darwin)
        set(CMAKE_HOST_SYSTEM_NAME Windows)
        set(_expected_formats metallib)
    elseif(GYO_POLICY_TEST_CASE STREQUAL "explicit-vulkan")
        set(GYO_GPU_DRIVER VULKAN)
        set(GYO_SHADER_BUNDLE SPIRV)
        set(_expected_formats spirv)
        set(_expected_driver vulkan)
    elseif(GYO_POLICY_TEST_CASE STREQUAL "cpu-none")
        set(CMAKE_SYSTEM_NAME Generic)
        set(GYO_REQUIRE_SDL_GPU OFF)
        set(GYO_RENDER_DEVICE NONE)
        set(_expected_enabled OFF)
        set(_expected_formats "")
    elseif(GYO_POLICY_TEST_CASE STREQUAL "cpu-auto")
        set(CMAKE_SYSTEM_NAME Generic)
        set(GYO_REQUIRE_SDL_GPU OFF)
        set(_expected_enabled OFF)
        set(_expected_formats "")
    elseif(GYO_POLICY_TEST_CASE STREQUAL "reject-driver-format")
        set(GYO_GPU_DRIVER VULKAN)
        set(GYO_SHADER_BUNDLE DXIL)
    elseif(GYO_POLICY_TEST_CASE STREQUAL "reject-target-driver")
        set(CMAKE_SYSTEM_NAME Darwin)
        set(GYO_GPU_DRIVER VULKAN)
    elseif(GYO_POLICY_TEST_CASE STREQUAL "reject-target-format")
        set(GYO_SHADER_BUNDLE METALLIB)
    elseif(GYO_POLICY_TEST_CASE STREQUAL "reject-none-backend")
        set(GYO_RENDER_DEVICE NONE)
        set(GYO_BUILD_SDL_GPU_BACKEND ON)
    elseif(GYO_POLICY_TEST_CASE STREQUAL "reject-none-required")
        set(GYO_RENDER_DEVICE NONE)
    elseif(GYO_POLICY_TEST_CASE STREQUAL "reject-device-driver-confusion")
        set(GYO_RENDER_DEVICE D3D12)
    elseif(GYO_POLICY_TEST_CASE STREQUAL "reject-empty-bundle")
        set(GYO_SHADER_BUNDLE "")
    elseif(NOT GYO_POLICY_TEST_CASE STREQUAL "auto-windows")
        message(FATAL_ERROR "Unknown policy case: ${GYO_POLICY_TEST_CASE}")
    endif()

    include("${_repository}/build/cmake/GyoRenderOptions.cmake")
    if(NOT "${GYO_ENABLE_SDL_GPU}" STREQUAL "${_expected_enabled}")
        message(FATAL_ERROR "Expected SDL_GPU=${_expected_enabled}, got ${GYO_ENABLE_SDL_GPU}")
    endif()
    if(NOT "${GYO_SHADER_FORMATS}" STREQUAL "${_expected_formats}")
        message(FATAL_ERROR "Expected formats=${_expected_formats}, got ${GYO_SHADER_FORMATS}")
    endif()
    if(NOT "${GYO_DEFAULT_GPU_DRIVER}" STREQUAL "${_expected_driver}")
        message(FATAL_ERROR "Expected driver=${_expected_driver}, got ${GYO_DEFAULT_GPU_DRIVER}")
    endif()
    message(STATUS "Policy case passed: ${GYO_POLICY_TEST_CASE}")
    return()
endif()

function(run_policy_case name expected_success expected_message)
    execute_process(
        COMMAND "${CMAKE_COMMAND}" "-DGYO_POLICY_TEST_CASE=${name}"
                -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE result
        OUTPUT_VARIABLE output
        ERROR_VARIABLE error
        TIMEOUT 15)
    if(expected_success)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Policy case ${name} failed:\n${output}\n${error}")
        endif()
    elseif(result EQUAL 0)
        message(FATAL_ERROR "Invalid policy case ${name} was accepted:\n${output}")
    endif()
    string(FIND "${output}\n${error}" "${expected_message}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "Policy case ${name} did not report '${expected_message}':\n${output}\n${error}")
    endif()
    message(STATUS "Checked ${name}")
endfunction()

foreach(name auto-windows auto-linux auto-macos explicit-vulkan cpu-none cpu-auto)
    run_policy_case("${name}" TRUE "Policy case passed: ${name}")
endforeach()
run_policy_case(reject-driver-format FALSE "requires spirv in GYO_SHADER_BUNDLE")
run_policy_case(reject-target-driver FALSE "VULKAN is unsupported on target Darwin")
run_policy_case(reject-target-format FALSE "Shader format metallib is unsupported on target Windows")
run_policy_case(reject-none-backend FALSE "conflicts with GYO_BUILD_SDL_GPU_BACKEND=ON")
run_policy_case(reject-device-driver-confusion FALSE "Unsupported GYO_RENDER_DEVICE=D3D12")
run_policy_case(reject-empty-bundle FALSE "GYO_SHADER_BUNDLE must not be empty")
run_policy_case(reject-none-required FALSE "conflicts with the SDL_GPU requirement")
message(STATUS "Render option policy: 13 isolated cases passed")
