cmake_minimum_required(VERSION 3.30)
get_filename_component(repository "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
include("${repository}/build/cmake/GyoToolRegistry.cmake")

if(DEFINED CASE)
    gyo_read_tool_registry("${CSV}" registry)
    if(CASE STREQUAL "select")
        gyo_select_tools("${registry}" "${SYSTEM}" "${SELECTION}" selected)
    elseif(CASE STREQUAL "metadata")
        gyo_read_tool_project("${METADATA}" "${VARIANT}" metadata)
    elseif(CASE STREQUAL "owners")
        gyo_validate_registry_owners("${APPS}" "${registry}")
    elseif(CASE STREQUAL "export")
        gyo_export_tool_matrix("${registry}" "${ROOT}" matrix)
    endif()
    return()
endif()
set(work "${CMAKE_CURRENT_BINARY_DIR}/tool-registry-tests")
file(MAKE_DIRECTORY "${work}")
set(header "name,description,version,enabled,default,release,windows,linux,macos")
set(csv "${work}/tools.csv")
file(WRITE "${csv}" "${header}\ncanvas,\"Editor, one\",1,true,true,true,true,true,true\naudio,,,true,false,true,true,true,true\npreview,,,true,false,false,true,true,true\ndisabled,,,false,false,false,true,true,true\nlinux_only,,,true,true,false,false,true,false\n")

function(equal actual expected context)
    if(NOT "${actual}" STREQUAL "${expected}")
        message(FATAL_ERROR "${context}: expected '${expected}', got '${actual}'")
    endif()
endfunction()
function(fails name expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DCSV=${csv}" ${ARGN}
        -P "${CMAKE_CURRENT_LIST_FILE}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(result EQUAL 0 OR NOT "${out}${err}" MATCHES "${expected}")
        message(FATAL_ERROR "${name}: expected failure '${expected}', got ${result}: ${out}${err}")
    endif()
endfunction()
gyo_read_tool_registry("${csv}" registry)
gyo_select_tools("${registry}" Windows AUTO selected)
equal("${selected}" canvas "Default tools")
gyo_select_tools("${registry}" Linux AUTO selected)
equal("${selected}" "canvas;linux_only" "Platform defaults")
gyo_select_tools("${registry}" Generic "" selected)
equal("${selected}" "" "No tools needs no platform")
gyo_select_tools("${registry}" Windows "audio;canvas:cli" selected)
equal("${selected}" "audio;canvas:cli" "Explicit modes and order")
fails(unknown "not registered" -DCASE=select -DSYSTEM=Windows -DSELECTION=unknown)
fails(disabled "disabled" -DCASE=select -DSYSTEM=Windows -DSELECTION=disabled)
fails(platform "not enabled" -DCASE=select -DSYSTEM=Windows -DSELECTION=linux_only)
fails(duplicate "more than once" -DCASE=select -DSYSTEM=Windows "-DSELECTION=canvas\;canvas:cli")
fails(mode_syntax "Invalid tool selection" -DCASE=select -DSYSTEM=Windows -DSELECTION=canvas:)
fails(owner "owner collision" -DCASE=owners "-DAPPS={\"projects\":[{\"name\":\"canvas\"}]}")

set(valid [=[{"version":1,"default_variant":"gui","requires_apps":{},"variants":{"gui":{"components":["SDL_RENDERER"],"packageable":true},"cli":{"components":[],"packageable":false}}}]=])
foreach(tool canvas audio)
    file(MAKE_DIRECTORY "${work}/tools/${tool}")
    file(WRITE "${work}/tools/${tool}/project.json" "${valid}")
endforeach()
gyo_read_tool_project("${work}/tools/canvas/project.json" "" metadata)
string(JSON variant GET "${metadata}" variant)
equal("${variant}" gui "Default mode")
gyo_read_tool_project("${work}/tools/canvas/project.json" cli metadata)
string(JSON packageable GET "${metadata}" packageable)
equal("${packageable}" OFF "CLI not packageable")
fails(unknown_mode "Unknown tool variant" -DCASE=metadata "-DMETADATA=${work}/tools/canvas/project.json" -DVARIANT=bad)
file(WRITE "${work}/bad.json" [=[{"version":1,"default_variant":"gui","requires_apps":{"game":"demo"},"variants":{"gui":{"components":[],"packageable":true}}}]=])
fails(packageable_dependency "cannot depend on apps" -DCASE=metadata "-DMETADATA=${work}/bad.json")
file(WRITE "${work}/bad.json" [=[{"version":1,"default_variant":"gui","requires_apps":{},"variants":{"gui":{"components":[],"packageable":"true"}}}]=])
fails(boolean_type "must be BOOLEAN" -DCASE=metadata "-DMETADATA=${work}/bad.json")
foreach(case bad_role unknown_component outside_variant invalid_array)
    if(case STREQUAL bad_role)
        set(overrides "{\"BadRole\":[]}")
        set(expected "Invalid tool role")
    elseif(case STREQUAL unknown_component)
        set(overrides "{\"cli\":[\"UNSUPPORTED\"]}")
        set(expected "Unknown GYO component")
    elseif(case STREQUAL outside_variant)
        set(overrides "{\"cli\":[\"SDL_TTF\"]}")
        set(expected "not declared by variant")
    else()
        set(overrides "{\"cli\":false}")
        set(expected "must be ARRAY")
    endif()
    string(JSON invalid SET "${valid}" variants gui role_components "${overrides}")
    file(WRITE "${work}/bad.json" "${invalid}")
    fails("${case}" "${expected}" -DCASE=metadata "-DMETADATA=${work}/bad.json")
endforeach()
gyo_export_tool_matrix("${registry}" "${work}" matrix)
string(JSON count LENGTH "${matrix}" include)
equal("${count}" 3 "Fixed platform baseline")
foreach(index RANGE 0 2)
    string(JSON count LENGTH "${matrix}" include ${index} tools)
    equal("${count}" 2 "Multiple release tools")
    string(JSON tool GET "${matrix}" include ${index} tools 1)
    equal("${tool}" audio:gui "Release mode")
endforeach()
file(WRITE "${work}/empty.csv" "${header}\n")
fails(empty_release "No release tools" -DCASE=export "-DCSV=${work}/empty.csv" "-DROOT=${work}")
file(WRITE "${work}/tools/audio/project.json" [=[{"version":1,"default_variant":"cli","requires_apps":{},"variants":{"cli":{"components":[],"packageable":false}}}]=])
fails(local_release "not packageable" -DCASE=export "-DROOT=${work}")
file(WRITE "${work}/tools/audio/project.json" "${valid}")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DGYO_TOOL_REGISTRY_FILE=${csv}" "-DGYO_REPOSITORY_ROOT=${work}"
    -P "${repository}/build/cmake/ExportToolRegistry.cmake" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT result EQUAL 0 OR NOT "${err}" STREQUAL "")
    message(FATAL_ERROR "Standalone tool export failed: ${out}${err}")
endif()
string(JSON count LENGTH "${out}" include)
equal("${count}" 3 "Standalone exporter JSON")

# Exercise metadata discovery and app dependencies in project mode without
# compiling or fetching anything. Poisoned unselected sources must stay unread.
set(fixture "${work}/fixture")
file(MAKE_DIRECTORY "${fixture}/engine/config" "${fixture}/apps/demo"
    "${fixture}/tools/canvas" "${fixture}/tools/audio" "${fixture}/tools/preview")
file(COPY "${csv}" DESTINATION "${fixture}/engine/config")
file(WRITE "${fixture}/engine/config/projects.csv"
    "name,description,version,enabled,windows,linux,macos\ndemo,,,true,true,true,true\n")
file(WRITE "${fixture}/apps/demo/project.json" "{\"version\":1,\"components\":[]}")
file(WRITE "${fixture}/apps/demo/CMakeLists.txt" "# Source validation only\n")
foreach(tool canvas audio)
    file(WRITE "${fixture}/tools/${tool}/project.json" "${valid}")
    file(WRITE "${fixture}/tools/${tool}/CMakeLists.txt"
        "file(APPEND \"\${CMAKE_BINARY_DIR}/configured.txt\" \"\${GYO_CURRENT_TOOL}:\${GYO_TOOL_VARIANT};\")\nadd_custom_target(${tool})\n")
endforeach()
file(WRITE "${fixture}/tools/preview/project.json" [=[
{"version":1,"default_variant":"default","requires_apps":{"game":"demo"},"variants":{"default":{"components":[],"packageable":false}}}
]=])
file(WRITE "${fixture}/tools/preview/CMakeLists.txt" [=[
gyo_tool_app_dependency(game app)
if(NOT app STREQUAL "demo")
    message(FATAL_ERROR "Wrong app dependency")
endif()
add_custom_target(preview)
]=])
file(WRITE "${fixture}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.30)
project(ToolCompositionFixture NONE)
set(GYO_REPOSITORY_ROOT "${CMAKE_SOURCE_DIR}")
include("${MODULE_ROOT}/GyoApps.cmake")
include("${MODULE_ROOT}/GyoTools.cmake")
gyo_configure_apps()
gyo_configure_tools()
file(WRITE "${CMAKE_BINARY_DIR}/configured.txt" "")
file(WRITE "${CMAKE_BINARY_DIR}/registered.txt" "")
# Capture the deployment boundary without requiring a compiler or SDL binaries.
function(gyo_install_product_target)
    cmake_parse_arguments(P "" "TARGET;PRODUCT;KIND;OWNER;ROLE" "COMPONENTS" ${ARGN})
    file(APPEND "${CMAKE_BINARY_DIR}/registered.txt" "${P_OWNER}.${P_ROLE}=${P_COMPONENTS}\n")
endfunction()
foreach(GYO_CURRENT_TOOL IN LISTS GYO_ACTIVE_TOOLS)
    get_property(GYO_TOOL_VARIANT GLOBAL PROPERTY GYO_TOOL_${GYO_CURRENT_TOOL}_VARIANT)
    add_subdirectory("tools/${GYO_CURRENT_TOOL}")
endforeach()
file(WRITE "${CMAKE_BINARY_DIR}/components.txt" "${GYO_REQUESTED_COMPONENTS}")
]=])
set(configure_args "-DMODULE_ROOT=${repository}/build/cmake"
    "-DGYO_TOOL_REGISTRY_FILE=${fixture}/engine/config/tools.csv")
if(DEFINED GENERATOR AND NOT GENERATOR STREQUAL "")
    list(APPEND configure_args -G "${GENERATOR}")
else()
    list(APPEND configure_args -G Ninja)
endif()
if(DEFINED MAKE_PROGRAM AND NOT MAKE_PROGRAM STREQUAL "")
    list(APPEND configure_args "-DCMAKE_MAKE_PROGRAM=${MAKE_PROGRAM}")
endif()
if(DEFINED PLATFORM AND NOT PLATFORM STREQUAL "")
    list(APPEND configure_args -A "${PLATFORM}")
endif()
function(configure expect_success expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${fixture}" -B "${work}/fixture-build"
        ${configure_args} ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
    if(expect_success AND NOT result EQUAL 0)
        message(FATAL_ERROR "Tool fixture configure failed: ${out}${err}")
    elseif(NOT expect_success AND (result EQUAL 0 OR NOT "${out}${err}" MATCHES "${expected}"))
        message(FATAL_ERROR "Tool fixture expected '${expected}': ${result}: ${out}${err}")
    endif()
endfunction()
configure(TRUE "" -DGYO_APPS= "-DGYO_TOOLS=audio\;canvas:cli")
file(READ "${work}/fixture-build/configured.txt" configured)
equal("${configured}" "audio:gui;canvas:cli;" "Generic multiple tool construction")
file(READ "${work}/fixture-build/components.txt" components)
equal("${components}" SDL_RENDERER "Selected modes alone contribute components")
configure(FALSE "requires selected app 'demo'" -DGYO_APPS= -DGYO_TOOLS=preview)
configure(TRUE "" -DGYO_APPS=demo -DGYO_TOOLS=preview)
configure(FALSE "Unknown tool variant" -DGYO_APPS= -DGYO_TOOLS=canvas:unknown)
configure(TRUE "" -DGYO_APPS= -DGYO_TOOLS=canvas:cli)
file(READ "${work}/fixture-build/components.txt" components)
equal("${components}" "" "Component requests do not stick across configure")
string(REPLACE "\"components\":[],\"packageable\":false" "\"components\":[\"SDL_TTF\"],\"packageable\":false" changed "${valid}")
file(WRITE "${fixture}/tools/canvas/project.json" "${changed}")
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${work}/fixture-build"
    RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 45)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Tool metadata incremental reconfigure failed: ${out}${err}")
endif()
file(READ "${work}/fixture-build/components.txt" components)
equal("${components}" SDL_TTF "Metadata edit triggers reconfigure")
string(JSON per_role SET "${valid}" variants gui role_components "{\"cli\":[]}")
file(WRITE "${fixture}/tools/canvas/project.json" "${per_role}")
file(WRITE "${fixture}/tools/canvas/CMakeLists.txt" [=[
add_executable(canvas_main IMPORTED GLOBAL)
add_executable(canvas_cli IMPORTED GLOBAL)
set_target_properties(canvas_main canvas_cli PROPERTIES IMPORTED_LOCATION "${CMAKE_COMMAND}")
gyo_tool_install_target(TARGET canvas_main ROLE main)
gyo_tool_install_target(TARGET canvas_cli ROLE cli)
]=])
configure(TRUE "" -DGYO_APPS= -DGYO_TOOLS=canvas)
file(READ "${work}/fixture-build/registered.txt" registered)
equal("${registered}" "canvas.main=SDL_RENDERER\ncanvas.cli=\n" "Same-owner roles declare independent deployment components")
file(WRITE "${fixture}/tools/canvas/project.json" "invalid unselected metadata")
file(WRITE "${fixture}/tools/canvas/CMakeLists.txt" "message(FATAL_ERROR \"Unselected tool was executed\")\n")
configure(TRUE "" -DGYO_APPS= -DGYO_TOOLS=)
file(READ "${work}/fixture-build/configured.txt" configured)
equal("${configured}" "" "No tools executes no tool code")
configure(TRUE "" -DGYO_APPS=demo -DGYO_TOOLS= "-DGYO_TOOL_REGISTRY_FILE=${fixture}/absent.csv")
message(STATUS "Tool registry: selection, ownership, metadata and release export checks passed")
