// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: runtime_v4.proto

package runtimev4

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShotRejection int32

const (
	ShotRejection_REJECTION_NONE              ShotRejection = 0
	ShotRejection_REJECTION_INVALID_REFERENCE ShotRejection = 1
	ShotRejection_REJECTION_EXPIRED           ShotRejection = 2
	ShotRejection_REJECTION_COOLDOWN          ShotRejection = 3
)

// Enum value maps for ShotRejection.
var (
	ShotRejection_name = map[int32]string{
		0: "REJECTION_NONE",
		1: "REJECTION_INVALID_REFERENCE",
		2: "REJECTION_EXPIRED",
		3: "REJECTION_COOLDOWN",
	}
	ShotRejection_value = map[string]int32{
		"REJECTION_NONE":              0,
		"REJECTION_INVALID_REFERENCE": 1,
		"REJECTION_EXPIRED":           2,
		"REJECTION_COOLDOWN":          3,
	}
)

func (x ShotRejection) Enum() *ShotRejection {
	p := new(ShotRejection)
	*p = x
	return p
}

func (x ShotRejection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShotRejection) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v4_proto_enumTypes[0].Descriptor()
}

func (ShotRejection) Type() protoreflect.EnumType {
	return &file_runtime_v4_proto_enumTypes[0]
}

func (x ShotRejection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShotRejection.Descriptor instead.
func (ShotRejection) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v4_proto_rawDescGZIP(), []int{0}
}

type ShotHitKind int32

const (
	ShotHitKind_HIT_MISS   ShotHitKind = 0
	ShotHitKind_HIT_WORLD  ShotHitKind = 1
	ShotHitKind_HIT_PLAYER ShotHitKind = 2
)

// Enum value maps for ShotHitKind.
var (
	ShotHitKind_name = map[int32]string{
		0: "HIT_MISS",
		1: "HIT_WORLD",
		2: "HIT_PLAYER",
	}
	ShotHitKind_value = map[string]int32{
		"HIT_MISS":   0,
		"HIT_WORLD":  1,
		"HIT_PLAYER": 2,
	}
)

func (x ShotHitKind) Enum() *ShotHitKind {
	p := new(ShotHitKind)
	*p = x
	return p
}

func (x ShotHitKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShotHitKind) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v4_proto_enumTypes[1].Descriptor()
}

func (ShotHitKind) Type() protoreflect.EnumType {
	return &file_runtime_v4_proto_enumTypes[1]
}

func (x ShotHitKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShotHitKind.Descriptor instead.
func (ShotHitKind) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v4_proto_rawDescGZIP(), []int{1}
}

// The local IPC host decodes this into product data. Match never sees protobuf,
// sessions, endpoints, or wire envelopes.
type Ready struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ArenaId               string                 `protobuf:"bytes,1,opt,name=arena_id,json=arenaId,proto3" json:"arena_id,omitempty"`
	ArenaVersion          uint32                 `protobuf:"varint,2,opt,name=arena_version,json=arenaVersion,proto3" json:"arena_version,omitempty"`
	TickRate              uint32                 `protobuf:"varint,3,opt,name=tick_rate,json=tickRate,proto3" json:"tick_rate,omitempty"`
	SnapshotIntervalTicks uint32                 `protobuf:"varint,4,opt,name=snapshot_interval_ticks,json=snapshotIntervalTicks,proto3" json:"snapshot_interval_ticks,omitempty"`
	MaxPlayers            uint32                 `protobuf:"varint,5,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	CombatRules           *CombatRules           `protobuf:"bytes,6,opt,name=combat_rules,json=combatRules,proto3" json:"combat_rules,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_runtime_v4_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v4_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_runtime_v4_proto_rawDescGZIP(), []int{0}
}

func (x *Ready) GetArenaId() string {
	if x != nil {
		return x.ArenaId
	}
	return ""
}

func (x *Ready) GetArenaVersion() uint32 {
	if x != nil {
		return x.ArenaVersion
	}
	return 0
}

func (x *Ready) GetTickRate() uint32 {
	if x != nil {
		return x.TickRate
	}
	return 0
}

func (x *Ready) GetSnapshotIntervalTicks() uint32 {
	if x != nil {
		return x.SnapshotIntervalTicks
	}
	return 0
}

func (x *Ready) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *Ready) GetCombatRules() *CombatRules {
	if x != nil {
		return x.CombatRules
	}
	return nil
}

type PlayerJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoin) Reset() {
	*x = PlayerJoin{}
	mi := &file_runtime_v4_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoin) ProtoMessage() {}

func (x *PlayerJoin) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v4_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoin.ProtoReflect.Descriptor instead.
func (*PlayerJoin) Descriptor() ([]byte, []int) {
	return file_runtime_v4_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerJoin) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type PlayerLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeave) Reset() {
	*x = PlayerLeave{}
	mi := &file_runtime_v4_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeave) ProtoMessage() {}

func (x *PlayerLeave) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v4_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeave.ProtoReflect.Descriptor instead.
func (*PlayerLeave) Descriptor() ([]byte, []int) {
	return file_runtime_v4_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerLeave) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// A single immutable 1/60-second movement step. No client time or position.
type MovementCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	MoveForward   float32                `protobuf:"fixed32,2,opt,name=move_forward,json=moveForward,proto3" json:"move_forward,omitempty"`
	MoveRight     float32                `protobuf:"fixed32,3,opt,name=move_right,json=moveRight,proto3" json:"move_right,omitempty"`
	Yaw           float32                `protobuf:"fixed32,4,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch         float32                `protobuf:"fixed32,5,opt,name=pitch,proto3" json:"pitch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovementCommand) Reset() {
	*x = MovementCommand{}
	mi := &file_runtime_v4_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovementCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovementCommand) ProtoMessage() {}

func (x *MovementCommand) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v4_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovementCommand.ProtoReflect.Descriptor instead.
func (*MovementCommand) Descriptor() ([]byte, []int) {
	return file_runtime_v4_proto_rawDescGZIP(), []int{3}
}

func (x *MovementCommand) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MovementCommand) GetMoveForward() float32 {
	if x != nil {
		return x.MoveForward
	}
	return 0
}

func (x *MovementCommand) GetMoveRight() float32 {
	if x != nil {
		return x.MoveRight
	}
	return 0
}

func (x *MovementCommand) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *MovementCommand) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

// Entire unacknowledged window, strictly ordered, at most 12 commands.
type PlayerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Commands      []*MovementCommand     `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	MovementEpoch uint64                 `protobuf:"varint,3,opt,name=movement_epoch,json=movementEpoch,proto3" json:"movement_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_runtime_v4_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v4_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_runtime_v4_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerInput) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerInput) GetCommands() []*MovementCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *PlayerInput) GetMovementEpoch() uint64 {
	if x != nil {
		return x.MovementEpoch
	}
	return 0
}

type JoinResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResult) Reset() {
	*x = JoinResult{}
	mi := &file_runtime_v4_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResult) ProtoMessage() {}

func (x *JoinResult) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v4_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResult.ProtoReflect.Descriptor instead.
func (*JoinResult) Descriptor() ([]byte, []int) {
	return file_runtime_v4_proto_rawDescGZIP(), []int{5}
}

func (x *JoinResult) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *JoinResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *JoinResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PlayerState struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	PlayerId                  uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X                         float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                         float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z                         float32                `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	Yaw                       float32                `protobuf:"fixed32,5,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch                     float32                `protobuf:"fixed32,6,opt,name=pitch,proto3" json:"pitch,omitempty"`
	LastResolvedCommand       uint64                 `protobuf:"varint,7,opt,name=last_resolved_command,json=lastResolvedCommand,proto3" json:"last_resolved_command,omitempty"`
	MovementEpoch             uint64                 `protobuf:"varint,8,opt,name=movement_epoch,json=movementEpoch,proto3" json:"movement_epoch,omitempty"`
	ContiguousPendingCommands uint32                 `protobuf:"varint,9,opt,name=contiguous_pending_commands,json=contiguousPendingCommands,proto3" json:"contiguous_pending_commands,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_runtime_v4_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v4_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_runtime_v4_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerState) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerState) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerState) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *PlayerState) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *PlayerState) GetLastResolvedCommand() uint64 {
	if x != nil {
		return x.LastResolvedCommand
	}
	return 0
}

func (x *PlayerState) GetMovementEpoch() uint64 {
	if x != nil {
		return x.MovementEpoch
	}
	return 0
}

func (x *PlayerState) GetContiguousPendingCommands() uint32 {
	if x != nil {
		return x.ContiguousPendingCommands
	}
	return 0
}

type WorldSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Players       []*PlayerState         `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Combat        []*CombatState         `protobuf:"bytes,3,rep,name=combat,proto3" json:"combat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldSnapshot) Reset() {
	*x = WorldSnapshot{}
	mi := &file_runtime_v4_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldSnapshot) ProtoMessage() {}

func (x *WorldSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v4_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldSnapshot.ProtoReflect.Descriptor instead.
func (*WorldSnapshot) Descriptor() ([]byte, []int) {
	return file_runtime_v4_proto_rawDescGZIP(), []int{7}
}

func (x *WorldSnapshot) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *WorldSnapshot) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *WorldSnapshot) GetCombat() []*CombatState {
	if x != nil {
		return x.Combat
	}
	return nil
}

type RuntimeError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeError) Reset() {
	*x = RuntimeError{}
	mi := &file_runtime_v4_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeError) ProtoMessage() {}

func (x *RuntimeError) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v4_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeError.ProtoReflect.Descriptor instead.
func (*RuntimeError) Descriptor() ([]byte, []int) {
	return file_runtime_v4_proto_rawDescGZIP(), []int{8}
}

func (x *RuntimeError) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *RuntimeError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RuntimeError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RuntimeEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*RuntimeEnvelope_Ready
	//	*RuntimeEnvelope_Join
	//	*RuntimeEnvelope_Leave
	//	*RuntimeEnvelope_Input
	//	*RuntimeEnvelope_JoinResult
	//	*RuntimeEnvelope_Error
	//	*RuntimeEnvelope_Snapshot
	//	*RuntimeEnvelope_Actions
	//	*RuntimeEnvelope_ActionResults
	Message       isRuntimeEnvelope_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeEnvelope) Reset() {
	*x = RuntimeEnvelope{}
	mi := &file_runtime_v4_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEnvelope) ProtoMessage() {}

func (x *RuntimeEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v4_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEnvelope.ProtoReflect.Descriptor instead.
func (*RuntimeEnvelope) Descriptor() ([]byte, []int) {
	return file_runtime_v4_proto_rawDescGZIP(), []int{9}
}

func (x *RuntimeEnvelope) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *RuntimeEnvelope) GetMessage() isRuntimeEnvelope_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RuntimeEnvelope) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetJoin() *PlayerJoin {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetLeave() *PlayerLeave {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Leave); ok {
			return x.Leave
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetInput() *PlayerInput {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetJoinResult() *JoinResult {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_JoinResult); ok {
			return x.JoinResult
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetError() *RuntimeError {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetSnapshot() *WorldSnapshot {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetActions() *ActionBatch {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Actions); ok {
			return x.Actions
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetActionResults() *ActionResults {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_ActionResults); ok {
			return x.ActionResults
		}
	}
	return nil
}

type isRuntimeEnvelope_Message interface {
	isRuntimeEnvelope_Message()
}

type RuntimeEnvelope_Ready struct {
	Ready *Ready `protobuf:"bytes,10,opt,name=ready,proto3,oneof"`
}

type RuntimeEnvelope_Join struct {
	Join *PlayerJoin `protobuf:"bytes,11,opt,name=join,proto3,oneof"`
}

type RuntimeEnvelope_Leave struct {
	Leave *PlayerLeave `protobuf:"bytes,12,opt,name=leave,proto3,oneof"`
}

type RuntimeEnvelope_Input struct {
	Input *PlayerInput `protobuf:"bytes,13,opt,name=input,proto3,oneof"`
}

type RuntimeEnvelope_JoinResult struct {
	JoinResult *JoinResult `protobuf:"bytes,14,opt,name=join_result,json=joinResult,proto3,oneof"`
}

type RuntimeEnvelope_Error struct {
	Error *RuntimeError `protobuf:"bytes,15,opt,name=error,proto3,oneof"`
}

type RuntimeEnvelope_Snapshot struct {
	Snapshot *WorldSnapshot `protobuf:"bytes,16,opt,name=snapshot,proto3,oneof"`
}

type RuntimeEnvelope_Actions struct {
	Actions *ActionBatch `protobuf:"bytes,17,opt,name=actions,proto3,oneof"`
}

type RuntimeEnvelope_ActionResults struct {
	ActionResults *ActionResults `protobuf:"bytes,18,opt,name=action_results,json=actionResults,proto3,oneof"`
}

func (*RuntimeEnvelope_Ready) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Join) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Leave) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Input) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_JoinResult) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Error) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Snapshot) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Actions) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_ActionResults) isRuntimeEnvelope_Message() {}

type ActionBatch struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlayerId            uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Shots               []*ShotRequest         `protobuf:"bytes,2,rep,name=shots,proto3" json:"shots,omitempty"`
	AcknowledgedThrough uint64                 `protobuf:"varint,3,opt,name=acknowledged_through,json=acknowledgedThrough,proto3" json:"acknowledged_through,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ActionBatch) Reset() {
	*x = ActionBatch{}
	mi := &file_runtime_v4_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionBatch) ProtoMessage() {}

func (x *ActionBatch) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v4_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionBatch.ProtoReflect.Descriptor instead.
func (*ActionBatch) Descriptor() ([]byte, []int) {
	return file_runtime_v4_proto_rawDescGZIP(), []int{10}
}

func (x *ActionBatch) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ActionBatch) GetShots() []*ShotRequest {
	if x != nil {
		return x.Shots
	}
	return nil
}

func (x *ActionBatch) GetAcknowledgedThrough() uint64 {
	if x != nil {
		return x.AcknowledgedThrough
	}
	return 0
}

type ActionResults struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	RetiredThrough uint64                 `protobuf:"varint,2,opt,name=retired_through,json=retiredThrough,proto3" json:"retired_through,omitempty"`
	Decisions      []*ShotDecision        `protobuf:"bytes,3,rep,name=decisions,proto3" json:"decisions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActionResults) Reset() {
	*x = ActionResults{}
	mi := &file_runtime_v4_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResults) ProtoMessage() {}

func (x *ActionResults) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v4_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResults.ProtoReflect.Descriptor instead.
func (*ActionResults) Descriptor() ([]byte, []int) {
	return file_runtime_v4_proto_rawDescGZIP(), []int{11}
}

func (x *ActionResults) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ActionResults) GetRetiredThrough() uint64 {
	if x != nil {
		return x.RetiredThrough
	}
	return 0
}

func (x *ActionResults) GetDecisions() []*ShotDecision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

type CombatRules struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MaximumHp             uint32                 `protobuf:"varint,1,opt,name=maximum_hp,json=maximumHp,proto3" json:"maximum_hp,omitempty"`
	ShotDamage            uint32                 `protobuf:"varint,2,opt,name=shot_damage,json=shotDamage,proto3" json:"shot_damage,omitempty"`
	CooldownTicks         uint64                 `protobuf:"varint,3,opt,name=cooldown_ticks,json=cooldownTicks,proto3" json:"cooldown_ticks,omitempty"`
	ShotRange             float32                `protobuf:"fixed32,4,opt,name=shot_range,json=shotRange,proto3" json:"shot_range,omitempty"`
	MaximumReferenceAgeMs uint32                 `protobuf:"varint,5,opt,name=maximum_reference_age_ms,json=maximumReferenceAgeMs,proto3" json:"maximum_reference_age_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CombatRules) Reset() {
	*x = CombatRules{}
	mi := &file_runtime_v4_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatRules) ProtoMessage() {}

func (x *CombatRules) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v4_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatRules.ProtoReflect.Descriptor instead.
func (*CombatRules) Descriptor() ([]byte, []int) {
	return file_runtime_v4_proto_rawDescGZIP(), []int{12}
}

func (x *CombatRules) GetMaximumHp() uint32 {
	if x != nil {
		return x.MaximumHp
	}
	return 0
}

func (x *CombatRules) GetShotDamage() uint32 {
	if x != nil {
		return x.ShotDamage
	}
	return 0
}

func (x *CombatRules) GetCooldownTicks() uint64 {
	if x != nil {
		return x.CooldownTicks
	}
	return 0
}

func (x *CombatRules) GetShotRange() float32 {
	if x != nil {
		return x.ShotRange
	}
	return 0
}

func (x *CombatRules) GetMaximumReferenceAgeMs() uint32 {
	if x != nil {
		return x.MaximumReferenceAgeMs
	}
	return 0
}

type CombatState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlayerId            uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Hp                  uint32                 `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`
	NextAllowedShotTick uint64                 `protobuf:"varint,3,opt,name=next_allowed_shot_tick,json=nextAllowedShotTick,proto3" json:"next_allowed_shot_tick,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CombatState) Reset() {
	*x = CombatState{}
	mi := &file_runtime_v4_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatState) ProtoMessage() {}

func (x *CombatState) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v4_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatState.ProtoReflect.Descriptor instead.
func (*CombatState) Descriptor() ([]byte, []int) {
	return file_runtime_v4_proto_rawDescGZIP(), []int{13}
}

func (x *CombatState) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *CombatState) GetHp() uint32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *CombatState) GetNextAllowedShotTick() uint64 {
	if x != nil {
		return x.NextAllowedShotTick
	}
	return 0
}

type ShotRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ActionId              uint64                 `protobuf:"varint,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	ObservedAuthorityTick uint64                 `protobuf:"varint,2,opt,name=observed_authority_tick,json=observedAuthorityTick,proto3" json:"observed_authority_tick,omitempty"`
	Yaw                   float32                `protobuf:"fixed32,3,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch                 float32                `protobuf:"fixed32,4,opt,name=pitch,proto3" json:"pitch,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ShotRequest) Reset() {
	*x = ShotRequest{}
	mi := &file_runtime_v4_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShotRequest) ProtoMessage() {}

func (x *ShotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v4_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShotRequest.ProtoReflect.Descriptor instead.
func (*ShotRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v4_proto_rawDescGZIP(), []int{14}
}

func (x *ShotRequest) GetActionId() uint64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *ShotRequest) GetObservedAuthorityTick() uint64 {
	if x != nil {
		return x.ObservedAuthorityTick
	}
	return 0
}

func (x *ShotRequest) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *ShotRequest) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

type ShotDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      uint64                 `protobuf:"varint,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	ResolvedTick  uint64                 `protobuf:"varint,2,opt,name=resolved_tick,json=resolvedTick,proto3" json:"resolved_tick,omitempty"`
	Accepted      bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejection     ShotRejection          `protobuf:"varint,4,opt,name=rejection,proto3,enum=object_fps_pvp.runtime.v4.ShotRejection" json:"rejection,omitempty"`
	HitKind       ShotHitKind            `protobuf:"varint,5,opt,name=hit_kind,json=hitKind,proto3,enum=object_fps_pvp.runtime.v4.ShotHitKind" json:"hit_kind,omitempty"`
	TargetId      uint64                 `protobuf:"varint,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Damage        uint32                 `protobuf:"varint,7,opt,name=damage,proto3" json:"damage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShotDecision) Reset() {
	*x = ShotDecision{}
	mi := &file_runtime_v4_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShotDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShotDecision) ProtoMessage() {}

func (x *ShotDecision) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v4_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShotDecision.ProtoReflect.Descriptor instead.
func (*ShotDecision) Descriptor() ([]byte, []int) {
	return file_runtime_v4_proto_rawDescGZIP(), []int{15}
}

func (x *ShotDecision) GetActionId() uint64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *ShotDecision) GetResolvedTick() uint64 {
	if x != nil {
		return x.ResolvedTick
	}
	return 0
}

func (x *ShotDecision) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ShotDecision) GetRejection() ShotRejection {
	if x != nil {
		return x.Rejection
	}
	return ShotRejection_REJECTION_NONE
}

func (x *ShotDecision) GetHitKind() ShotHitKind {
	if x != nil {
		return x.HitKind
	}
	return ShotHitKind_HIT_MISS
}

func (x *ShotDecision) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ShotDecision) GetDamage() uint32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

var File_runtime_v4_proto protoreflect.FileDescriptor

const file_runtime_v4_proto_rawDesc = "" +
	"\n" +
	"\x10runtime_v4.proto\x12\x19object_fps_pvp.runtime.v4\"\x88\x02\n" +
	"\x05Ready\x12\x19\n" +
	"\barena_id\x18\x01 \x01(\tR\aarenaId\x12#\n" +
	"\rarena_version\x18\x02 \x01(\rR\farenaVersion\x12\x1b\n" +
	"\ttick_rate\x18\x03 \x01(\rR\btickRate\x126\n" +
	"\x17snapshot_interval_ticks\x18\x04 \x01(\rR\x15snapshotIntervalTicks\x12\x1f\n" +
	"\vmax_players\x18\x05 \x01(\rR\n" +
	"maxPlayers\x12I\n" +
	"\fcombat_rules\x18\x06 \x01(\v2&.object_fps_pvp.runtime.v4.CombatRulesR\vcombatRules\")\n" +
	"\n" +
	"PlayerJoin\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\"*\n" +
	"\vPlayerLeave\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\"\x97\x01\n" +
	"\x0fMovementCommand\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12!\n" +
	"\fmove_forward\x18\x02 \x01(\x02R\vmoveForward\x12\x1d\n" +
	"\n" +
	"move_right\x18\x03 \x01(\x02R\tmoveRight\x12\x10\n" +
	"\x03yaw\x18\x04 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x05 \x01(\x02R\x05pitch\"\x99\x01\n" +
	"\vPlayerInput\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12F\n" +
	"\bcommands\x18\x02 \x03(\v2*.object_fps_pvp.runtime.v4.MovementCommandR\bcommands\x12%\n" +
	"\x0emovement_epoch\x18\x03 \x01(\x04R\rmovementEpoch\"]\n" +
	"\n" +
	"JoinResult\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x97\x02\n" +
	"\vPlayerState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x02R\x01z\x12\x10\n" +
	"\x03yaw\x18\x05 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x06 \x01(\x02R\x05pitch\x122\n" +
	"\x15last_resolved_command\x18\a \x01(\x04R\x13lastResolvedCommand\x12%\n" +
	"\x0emovement_epoch\x18\b \x01(\x04R\rmovementEpoch\x12>\n" +
	"\x1bcontiguous_pending_commands\x18\t \x01(\rR\x19contiguousPendingCommands\"\xa5\x01\n" +
	"\rWorldSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12@\n" +
	"\aplayers\x18\x02 \x03(\v2&.object_fps_pvp.runtime.v4.PlayerStateR\aplayers\x12>\n" +
	"\x06combat\x18\x03 \x03(\v2&.object_fps_pvp.runtime.v4.CombatStateR\x06combat\"Y\n" +
	"\fRuntimeError\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xa8\x05\n" +
	"\x0fRuntimeEnvelope\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x128\n" +
	"\x05ready\x18\n" +
	" \x01(\v2 .object_fps_pvp.runtime.v4.ReadyH\x00R\x05ready\x12;\n" +
	"\x04join\x18\v \x01(\v2%.object_fps_pvp.runtime.v4.PlayerJoinH\x00R\x04join\x12>\n" +
	"\x05leave\x18\f \x01(\v2&.object_fps_pvp.runtime.v4.PlayerLeaveH\x00R\x05leave\x12>\n" +
	"\x05input\x18\r \x01(\v2&.object_fps_pvp.runtime.v4.PlayerInputH\x00R\x05input\x12H\n" +
	"\vjoin_result\x18\x0e \x01(\v2%.object_fps_pvp.runtime.v4.JoinResultH\x00R\n" +
	"joinResult\x12?\n" +
	"\x05error\x18\x0f \x01(\v2'.object_fps_pvp.runtime.v4.RuntimeErrorH\x00R\x05error\x12F\n" +
	"\bsnapshot\x18\x10 \x01(\v2(.object_fps_pvp.runtime.v4.WorldSnapshotH\x00R\bsnapshot\x12B\n" +
	"\aactions\x18\x11 \x01(\v2&.object_fps_pvp.runtime.v4.ActionBatchH\x00R\aactions\x12Q\n" +
	"\x0eaction_results\x18\x12 \x01(\v2(.object_fps_pvp.runtime.v4.ActionResultsH\x00R\ractionResultsB\t\n" +
	"\amessage\"\x9b\x01\n" +
	"\vActionBatch\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12<\n" +
	"\x05shots\x18\x02 \x03(\v2&.object_fps_pvp.runtime.v4.ShotRequestR\x05shots\x121\n" +
	"\x14acknowledged_through\x18\x03 \x01(\x04R\x13acknowledgedThrough\"\x9c\x01\n" +
	"\rActionResults\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12'\n" +
	"\x0fretired_through\x18\x02 \x01(\x04R\x0eretiredThrough\x12E\n" +
	"\tdecisions\x18\x03 \x03(\v2'.object_fps_pvp.runtime.v4.ShotDecisionR\tdecisions\"\xcc\x01\n" +
	"\vCombatRules\x12\x1d\n" +
	"\n" +
	"maximum_hp\x18\x01 \x01(\rR\tmaximumHp\x12\x1f\n" +
	"\vshot_damage\x18\x02 \x01(\rR\n" +
	"shotDamage\x12%\n" +
	"\x0ecooldown_ticks\x18\x03 \x01(\x04R\rcooldownTicks\x12\x1d\n" +
	"\n" +
	"shot_range\x18\x04 \x01(\x02R\tshotRange\x127\n" +
	"\x18maximum_reference_age_ms\x18\x05 \x01(\rR\x15maximumReferenceAgeMs\"o\n" +
	"\vCombatState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x0e\n" +
	"\x02hp\x18\x02 \x01(\rR\x02hp\x123\n" +
	"\x16next_allowed_shot_tick\x18\x03 \x01(\x04R\x13nextAllowedShotTick\"\x8a\x01\n" +
	"\vShotRequest\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\x04R\bactionId\x126\n" +
	"\x17observed_authority_tick\x18\x02 \x01(\x04R\x15observedAuthorityTick\x12\x10\n" +
	"\x03yaw\x18\x03 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x04 \x01(\x02R\x05pitch\"\xac\x02\n" +
	"\fShotDecision\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\x04R\bactionId\x12#\n" +
	"\rresolved_tick\x18\x02 \x01(\x04R\fresolvedTick\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\x12F\n" +
	"\trejection\x18\x04 \x01(\x0e2(.object_fps_pvp.runtime.v4.ShotRejectionR\trejection\x12A\n" +
	"\bhit_kind\x18\x05 \x01(\x0e2&.object_fps_pvp.runtime.v4.ShotHitKindR\ahitKind\x12\x1b\n" +
	"\ttarget_id\x18\x06 \x01(\x04R\btargetId\x12\x16\n" +
	"\x06damage\x18\a \x01(\rR\x06damage*s\n" +
	"\rShotRejection\x12\x12\n" +
	"\x0eREJECTION_NONE\x10\x00\x12\x1f\n" +
	"\x1bREJECTION_INVALID_REFERENCE\x10\x01\x12\x15\n" +
	"\x11REJECTION_EXPIRED\x10\x02\x12\x16\n" +
	"\x12REJECTION_COOLDOWN\x10\x03*:\n" +
	"\vShotHitKind\x12\f\n" +
	"\bHIT_MISS\x10\x00\x12\r\n" +
	"\tHIT_WORLD\x10\x01\x12\x0e\n" +
	"\n" +
	"HIT_PLAYER\x10\x02B-Z+gyo.local/object_fps_pvp/protocol/runtimev4b\x06proto3"

var (
	file_runtime_v4_proto_rawDescOnce sync.Once
	file_runtime_v4_proto_rawDescData []byte
)

func file_runtime_v4_proto_rawDescGZIP() []byte {
	file_runtime_v4_proto_rawDescOnce.Do(func() {
		file_runtime_v4_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v4_proto_rawDesc), len(file_runtime_v4_proto_rawDesc)))
	})
	return file_runtime_v4_proto_rawDescData
}

var file_runtime_v4_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_runtime_v4_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_runtime_v4_proto_goTypes = []any{
	(ShotRejection)(0),      // 0: object_fps_pvp.runtime.v4.ShotRejection
	(ShotHitKind)(0),        // 1: object_fps_pvp.runtime.v4.ShotHitKind
	(*Ready)(nil),           // 2: object_fps_pvp.runtime.v4.Ready
	(*PlayerJoin)(nil),      // 3: object_fps_pvp.runtime.v4.PlayerJoin
	(*PlayerLeave)(nil),     // 4: object_fps_pvp.runtime.v4.PlayerLeave
	(*MovementCommand)(nil), // 5: object_fps_pvp.runtime.v4.MovementCommand
	(*PlayerInput)(nil),     // 6: object_fps_pvp.runtime.v4.PlayerInput
	(*JoinResult)(nil),      // 7: object_fps_pvp.runtime.v4.JoinResult
	(*PlayerState)(nil),     // 8: object_fps_pvp.runtime.v4.PlayerState
	(*WorldSnapshot)(nil),   // 9: object_fps_pvp.runtime.v4.WorldSnapshot
	(*RuntimeError)(nil),    // 10: object_fps_pvp.runtime.v4.RuntimeError
	(*RuntimeEnvelope)(nil), // 11: object_fps_pvp.runtime.v4.RuntimeEnvelope
	(*ActionBatch)(nil),     // 12: object_fps_pvp.runtime.v4.ActionBatch
	(*ActionResults)(nil),   // 13: object_fps_pvp.runtime.v4.ActionResults
	(*CombatRules)(nil),     // 14: object_fps_pvp.runtime.v4.CombatRules
	(*CombatState)(nil),     // 15: object_fps_pvp.runtime.v4.CombatState
	(*ShotRequest)(nil),     // 16: object_fps_pvp.runtime.v4.ShotRequest
	(*ShotDecision)(nil),    // 17: object_fps_pvp.runtime.v4.ShotDecision
}
var file_runtime_v4_proto_depIdxs = []int32{
	14, // 0: object_fps_pvp.runtime.v4.Ready.combat_rules:type_name -> object_fps_pvp.runtime.v4.CombatRules
	5,  // 1: object_fps_pvp.runtime.v4.PlayerInput.commands:type_name -> object_fps_pvp.runtime.v4.MovementCommand
	8,  // 2: object_fps_pvp.runtime.v4.WorldSnapshot.players:type_name -> object_fps_pvp.runtime.v4.PlayerState
	15, // 3: object_fps_pvp.runtime.v4.WorldSnapshot.combat:type_name -> object_fps_pvp.runtime.v4.CombatState
	2,  // 4: object_fps_pvp.runtime.v4.RuntimeEnvelope.ready:type_name -> object_fps_pvp.runtime.v4.Ready
	3,  // 5: object_fps_pvp.runtime.v4.RuntimeEnvelope.join:type_name -> object_fps_pvp.runtime.v4.PlayerJoin
	4,  // 6: object_fps_pvp.runtime.v4.RuntimeEnvelope.leave:type_name -> object_fps_pvp.runtime.v4.PlayerLeave
	6,  // 7: object_fps_pvp.runtime.v4.RuntimeEnvelope.input:type_name -> object_fps_pvp.runtime.v4.PlayerInput
	7,  // 8: object_fps_pvp.runtime.v4.RuntimeEnvelope.join_result:type_name -> object_fps_pvp.runtime.v4.JoinResult
	10, // 9: object_fps_pvp.runtime.v4.RuntimeEnvelope.error:type_name -> object_fps_pvp.runtime.v4.RuntimeError
	9,  // 10: object_fps_pvp.runtime.v4.RuntimeEnvelope.snapshot:type_name -> object_fps_pvp.runtime.v4.WorldSnapshot
	12, // 11: object_fps_pvp.runtime.v4.RuntimeEnvelope.actions:type_name -> object_fps_pvp.runtime.v4.ActionBatch
	13, // 12: object_fps_pvp.runtime.v4.RuntimeEnvelope.action_results:type_name -> object_fps_pvp.runtime.v4.ActionResults
	16, // 13: object_fps_pvp.runtime.v4.ActionBatch.shots:type_name -> object_fps_pvp.runtime.v4.ShotRequest
	17, // 14: object_fps_pvp.runtime.v4.ActionResults.decisions:type_name -> object_fps_pvp.runtime.v4.ShotDecision
	0,  // 15: object_fps_pvp.runtime.v4.ShotDecision.rejection:type_name -> object_fps_pvp.runtime.v4.ShotRejection
	1,  // 16: object_fps_pvp.runtime.v4.ShotDecision.hit_kind:type_name -> object_fps_pvp.runtime.v4.ShotHitKind
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_runtime_v4_proto_init() }
func file_runtime_v4_proto_init() {
	if File_runtime_v4_proto != nil {
		return
	}
	file_runtime_v4_proto_msgTypes[9].OneofWrappers = []any{
		(*RuntimeEnvelope_Ready)(nil),
		(*RuntimeEnvelope_Join)(nil),
		(*RuntimeEnvelope_Leave)(nil),
		(*RuntimeEnvelope_Input)(nil),
		(*RuntimeEnvelope_JoinResult)(nil),
		(*RuntimeEnvelope_Error)(nil),
		(*RuntimeEnvelope_Snapshot)(nil),
		(*RuntimeEnvelope_Actions)(nil),
		(*RuntimeEnvelope_ActionResults)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v4_proto_rawDesc), len(file_runtime_v4_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_runtime_v4_proto_goTypes,
		DependencyIndexes: file_runtime_v4_proto_depIdxs,
		EnumInfos:         file_runtime_v4_proto_enumTypes,
		MessageInfos:      file_runtime_v4_proto_msgTypes,
	}.Build()
	File_runtime_v4_proto = out.File
	file_runtime_v4_proto_goTypes = nil
	file_runtime_v4_proto_depIdxs = nil
}
