// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: client_v5.proto

package clientv5

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LifeState int32

const (
	LifeState_LIFE_UNSPECIFIED LifeState = 0
	LifeState_LIFE_ALIVE       LifeState = 1
	LifeState_LIFE_DEAD        LifeState = 2
)

// Enum value maps for LifeState.
var (
	LifeState_name = map[int32]string{
		0: "LIFE_UNSPECIFIED",
		1: "LIFE_ALIVE",
		2: "LIFE_DEAD",
	}
	LifeState_value = map[string]int32{
		"LIFE_UNSPECIFIED": 0,
		"LIFE_ALIVE":       1,
		"LIFE_DEAD":        2,
	}
)

func (x LifeState) Enum() *LifeState {
	p := new(LifeState)
	*p = x
	return p
}

func (x LifeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifeState) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v5_proto_enumTypes[0].Descriptor()
}

func (LifeState) Type() protoreflect.EnumType {
	return &file_client_v5_proto_enumTypes[0]
}

func (x LifeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LifeState.Descriptor instead.
func (LifeState) EnumDescriptor() ([]byte, []int) {
	return file_client_v5_proto_rawDescGZIP(), []int{0}
}

// Historical names are retained; requests and decisions cover Shot and Reload.
type ActionKind int32

const (
	ActionKind_ACTION_UNSPECIFIED ActionKind = 0
	ActionKind_ACTION_SHOT        ActionKind = 1
	ActionKind_ACTION_RELOAD      ActionKind = 2
)

// Enum value maps for ActionKind.
var (
	ActionKind_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_SHOT",
		2: "ACTION_RELOAD",
	}
	ActionKind_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_SHOT":        1,
		"ACTION_RELOAD":      2,
	}
)

func (x ActionKind) Enum() *ActionKind {
	p := new(ActionKind)
	*p = x
	return p
}

func (x ActionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v5_proto_enumTypes[1].Descriptor()
}

func (ActionKind) Type() protoreflect.EnumType {
	return &file_client_v5_proto_enumTypes[1]
}

func (x ActionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionKind.Descriptor instead.
func (ActionKind) EnumDescriptor() ([]byte, []int) {
	return file_client_v5_proto_rawDescGZIP(), []int{1}
}

type ShotRejection int32

const (
	ShotRejection_REJECTION_NONE              ShotRejection = 0
	ShotRejection_REJECTION_INVALID_REFERENCE ShotRejection = 1
	ShotRejection_REJECTION_EXPIRED           ShotRejection = 2
	ShotRejection_REJECTION_COOLDOWN          ShotRejection = 3
	ShotRejection_REJECTION_STALE_LIFE        ShotRejection = 4
	ShotRejection_REJECTION_INVALID_LIFE      ShotRejection = 5
	ShotRejection_REJECTION_DEAD              ShotRejection = 6
	ShotRejection_REJECTION_RELOADING         ShotRejection = 7
	ShotRejection_REJECTION_EMPTY_MAGAZINE    ShotRejection = 8
	ShotRejection_REJECTION_MAGAZINE_FULL     ShotRejection = 9
)

// Enum value maps for ShotRejection.
var (
	ShotRejection_name = map[int32]string{
		0: "REJECTION_NONE",
		1: "REJECTION_INVALID_REFERENCE",
		2: "REJECTION_EXPIRED",
		3: "REJECTION_COOLDOWN",
		4: "REJECTION_STALE_LIFE",
		5: "REJECTION_INVALID_LIFE",
		6: "REJECTION_DEAD",
		7: "REJECTION_RELOADING",
		8: "REJECTION_EMPTY_MAGAZINE",
		9: "REJECTION_MAGAZINE_FULL",
	}
	ShotRejection_value = map[string]int32{
		"REJECTION_NONE":              0,
		"REJECTION_INVALID_REFERENCE": 1,
		"REJECTION_EXPIRED":           2,
		"REJECTION_COOLDOWN":          3,
		"REJECTION_STALE_LIFE":        4,
		"REJECTION_INVALID_LIFE":      5,
		"REJECTION_DEAD":              6,
		"REJECTION_RELOADING":         7,
		"REJECTION_EMPTY_MAGAZINE":    8,
		"REJECTION_MAGAZINE_FULL":     9,
	}
)

func (x ShotRejection) Enum() *ShotRejection {
	p := new(ShotRejection)
	*p = x
	return p
}

func (x ShotRejection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShotRejection) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v5_proto_enumTypes[2].Descriptor()
}

func (ShotRejection) Type() protoreflect.EnumType {
	return &file_client_v5_proto_enumTypes[2]
}

func (x ShotRejection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShotRejection.Descriptor instead.
func (ShotRejection) EnumDescriptor() ([]byte, []int) {
	return file_client_v5_proto_rawDescGZIP(), []int{2}
}

type ShotHitKind int32

const (
	ShotHitKind_HIT_MISS   ShotHitKind = 0
	ShotHitKind_HIT_WORLD  ShotHitKind = 1
	ShotHitKind_HIT_PLAYER ShotHitKind = 2
)

// Enum value maps for ShotHitKind.
var (
	ShotHitKind_name = map[int32]string{
		0: "HIT_MISS",
		1: "HIT_WORLD",
		2: "HIT_PLAYER",
	}
	ShotHitKind_value = map[string]int32{
		"HIT_MISS":   0,
		"HIT_WORLD":  1,
		"HIT_PLAYER": 2,
	}
)

func (x ShotHitKind) Enum() *ShotHitKind {
	p := new(ShotHitKind)
	*p = x
	return p
}

func (x ShotHitKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShotHitKind) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v5_proto_enumTypes[3].Descriptor()
}

func (ShotHitKind) Type() protoreflect.EnumType {
	return &file_client_v5_proto_enumTypes[3]
}

func (x ShotHitKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShotHitKind.Descriptor instead.
func (ShotHitKind) EnumDescriptor() ([]byte, []int) {
	return file_client_v5_proto_rawDescGZIP(), []int{3}
}

// This remote-client contract is independent of runtime_v5.proto.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_client_v5_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_client_v5_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_client_v5_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MatchId       uint64                 `protobuf:"varint,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	TickRate      uint32                 `protobuf:"varint,3,opt,name=tick_rate,json=tickRate,proto3" json:"tick_rate,omitempty"`
	SnapshotRate  uint32                 `protobuf:"varint,4,opt,name=snapshot_rate,json=snapshotRate,proto3" json:"snapshot_rate,omitempty"`
	ArenaId       string                 `protobuf:"bytes,5,opt,name=arena_id,json=arenaId,proto3" json:"arena_id,omitempty"`
	ArenaVersion  uint32                 `protobuf:"varint,6,opt,name=arena_version,json=arenaVersion,proto3" json:"arena_version,omitempty"`
	CombatRules   *CombatRules           `protobuf:"bytes,7,opt,name=combat_rules,json=combatRules,proto3" json:"combat_rules,omitempty"`
	JumpHeight    float32                `protobuf:"fixed32,8,opt,name=jump_height,json=jumpHeight,proto3" json:"jump_height,omitempty"`
	Gravity       float32                `protobuf:"fixed32,9,opt,name=gravity,proto3" json:"gravity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_client_v5_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_client_v5_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_client_v5_proto_rawDescGZIP(), []int{1}
}

func (x *Welcome) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Welcome) GetMatchId() uint64 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

func (x *Welcome) GetTickRate() uint32 {
	if x != nil {
		return x.TickRate
	}
	return 0
}

func (x *Welcome) GetSnapshotRate() uint32 {
	if x != nil {
		return x.SnapshotRate
	}
	return 0
}

func (x *Welcome) GetArenaId() string {
	if x != nil {
		return x.ArenaId
	}
	return ""
}

func (x *Welcome) GetArenaVersion() uint32 {
	if x != nil {
		return x.ArenaVersion
	}
	return 0
}

func (x *Welcome) GetCombatRules() *CombatRules {
	if x != nil {
		return x.CombatRules
	}
	return nil
}

func (x *Welcome) GetJumpHeight() float32 {
	if x != nil {
		return x.JumpHeight
	}
	return 0
}

func (x *Welcome) GetGravity() float32 {
	if x != nil {
		return x.Gravity
	}
	return 0
}

// A single immutable 1/60-second movement step. No client time or position.
type MovementCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	MoveForward   float32                `protobuf:"fixed32,2,opt,name=move_forward,json=moveForward,proto3" json:"move_forward,omitempty"`
	MoveRight     float32                `protobuf:"fixed32,3,opt,name=move_right,json=moveRight,proto3" json:"move_right,omitempty"`
	Yaw           float32                `protobuf:"fixed32,4,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch         float32                `protobuf:"fixed32,5,opt,name=pitch,proto3" json:"pitch,omitempty"`
	JumpRequested bool                   `protobuf:"varint,6,opt,name=jump_requested,json=jumpRequested,proto3" json:"jump_requested,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovementCommand) Reset() {
	*x = MovementCommand{}
	mi := &file_client_v5_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovementCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovementCommand) ProtoMessage() {}

func (x *MovementCommand) ProtoReflect() protoreflect.Message {
	mi := &file_client_v5_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovementCommand.ProtoReflect.Descriptor instead.
func (*MovementCommand) Descriptor() ([]byte, []int) {
	return file_client_v5_proto_rawDescGZIP(), []int{2}
}

func (x *MovementCommand) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MovementCommand) GetMoveForward() float32 {
	if x != nil {
		return x.MoveForward
	}
	return 0
}

func (x *MovementCommand) GetMoveRight() float32 {
	if x != nil {
		return x.MoveRight
	}
	return 0
}

func (x *MovementCommand) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *MovementCommand) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *MovementCommand) GetJumpRequested() bool {
	if x != nil {
		return x.JumpRequested
	}
	return false
}

// Entire unacknowledged window, strictly ordered, at most 12 commands.
type PlayerInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Commands       []*MovementCommand     `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	MovementEpoch  uint64                 `protobuf:"varint,2,opt,name=movement_epoch,json=movementEpoch,proto3" json:"movement_epoch,omitempty"`
	LifeGeneration uint64                 `protobuf:"varint,3,opt,name=life_generation,json=lifeGeneration,proto3" json:"life_generation,omitempty"`
	// Tick of the latest snapshot the Client applied when it published this
	// window (0 before any). The Match times connection quality with it.
	ObservedAuthorityTick uint64 `protobuf:"varint,4,opt,name=observed_authority_tick,json=observedAuthorityTick,proto3" json:"observed_authority_tick,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_client_v5_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_client_v5_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_client_v5_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerInput) GetCommands() []*MovementCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *PlayerInput) GetMovementEpoch() uint64 {
	if x != nil {
		return x.MovementEpoch
	}
	return 0
}

func (x *PlayerInput) GetLifeGeneration() uint64 {
	if x != nil {
		return x.LifeGeneration
	}
	return 0
}

func (x *PlayerInput) GetObservedAuthorityTick() uint64 {
	if x != nil {
		return x.ObservedAuthorityTick
	}
	return 0
}

type PlayerState struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	PlayerId                  uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X                         float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                         float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z                         float32                `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	Yaw                       float32                `protobuf:"fixed32,5,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch                     float32                `protobuf:"fixed32,6,opt,name=pitch,proto3" json:"pitch,omitempty"`
	LastResolvedCommand       uint64                 `protobuf:"varint,7,opt,name=last_resolved_command,json=lastResolvedCommand,proto3" json:"last_resolved_command,omitempty"`
	MovementEpoch             uint64                 `protobuf:"varint,8,opt,name=movement_epoch,json=movementEpoch,proto3" json:"movement_epoch,omitempty"`
	ContiguousPendingCommands uint32                 `protobuf:"varint,9,opt,name=contiguous_pending_commands,json=contiguousPendingCommands,proto3" json:"contiguous_pending_commands,omitempty"`
	VerticalVelocity          float32                `protobuf:"fixed32,10,opt,name=vertical_velocity,json=verticalVelocity,proto3" json:"vertical_velocity,omitempty"`
	Grounded                  bool                   `protobuf:"varint,11,opt,name=grounded,proto3" json:"grounded,omitempty"`
	LifeGeneration            uint64                 `protobuf:"varint,12,opt,name=life_generation,json=lifeGeneration,proto3" json:"life_generation,omitempty"`
	LifeState                 LifeState              `protobuf:"varint,13,opt,name=life_state,json=lifeState,proto3,enum=object_fps_pvp.client.v5.LifeState" json:"life_state,omitempty"`
	LifeStateTick             uint64                 `protobuf:"varint,14,opt,name=life_state_tick,json=lifeStateTick,proto3" json:"life_state_tick,omitempty"`
	RespawnTick               uint64                 `protobuf:"varint,15,opt,name=respawn_tick,json=respawnTick,proto3" json:"respawn_tick,omitempty"`
	// Host timing observation, never simulation input: the smallest movement
	// slack since the previous published snapshot and its command sequence.
	// Slack is the executing tick minus the command's first receipt, or minus
	// the receipt of a command that arrived after its sequence was substituted
	// (negative). Both or neither; |slack| <= 1,000,000 and
	// 1 <= sequence <= last_resolved_command. Only the Client's phase tracking
	// reads it.
	MovementSlackSequence *uint64 `protobuf:"varint,17,opt,name=movement_slack_sequence,json=movementSlackSequence,proto3,oneof" json:"movement_slack_sequence,omitempty"`
	MovementSlackUs       *int32  `protobuf:"zigzag32,18,opt,name=movement_slack_us,json=movementSlackUs,proto3,oneof" json:"movement_slack_us,omitempty"`
	// Consecutive failed 10-second connection-quality windows (0-2). At 3 the
	// Match evicts the player; the HUD warns while this is non-zero.
	ConnectionQualityFailures uint32 `protobuf:"varint,19,opt,name=connection_quality_failures,json=connectionQualityFailures,proto3" json:"connection_quality_failures,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_client_v5_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_client_v5_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_client_v5_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerState) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerState) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerState) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *PlayerState) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *PlayerState) GetLastResolvedCommand() uint64 {
	if x != nil {
		return x.LastResolvedCommand
	}
	return 0
}

func (x *PlayerState) GetMovementEpoch() uint64 {
	if x != nil {
		return x.MovementEpoch
	}
	return 0
}

func (x *PlayerState) GetContiguousPendingCommands() uint32 {
	if x != nil {
		return x.ContiguousPendingCommands
	}
	return 0
}

func (x *PlayerState) GetVerticalVelocity() float32 {
	if x != nil {
		return x.VerticalVelocity
	}
	return 0
}

func (x *PlayerState) GetGrounded() bool {
	if x != nil {
		return x.Grounded
	}
	return false
}

func (x *PlayerState) GetLifeGeneration() uint64 {
	if x != nil {
		return x.LifeGeneration
	}
	return 0
}

func (x *PlayerState) GetLifeState() LifeState {
	if x != nil {
		return x.LifeState
	}
	return LifeState_LIFE_UNSPECIFIED
}

func (x *PlayerState) GetLifeStateTick() uint64 {
	if x != nil {
		return x.LifeStateTick
	}
	return 0
}

func (x *PlayerState) GetRespawnTick() uint64 {
	if x != nil {
		return x.RespawnTick
	}
	return 0
}

func (x *PlayerState) GetMovementSlackSequence() uint64 {
	if x != nil && x.MovementSlackSequence != nil {
		return *x.MovementSlackSequence
	}
	return 0
}

func (x *PlayerState) GetMovementSlackUs() int32 {
	if x != nil && x.MovementSlackUs != nil {
		return *x.MovementSlackUs
	}
	return 0
}

func (x *PlayerState) GetConnectionQualityFailures() uint32 {
	if x != nil {
		return x.ConnectionQualityFailures
	}
	return 0
}

type WorldSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Players       []*PlayerState         `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Combat        []*CombatState         `protobuf:"bytes,3,rep,name=combat,proto3" json:"combat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldSnapshot) Reset() {
	*x = WorldSnapshot{}
	mi := &file_client_v5_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldSnapshot) ProtoMessage() {}

func (x *WorldSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_client_v5_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldSnapshot.ProtoReflect.Descriptor instead.
func (*WorldSnapshot) Descriptor() ([]byte, []int) {
	return file_client_v5_proto_rawDescGZIP(), []int{5}
}

func (x *WorldSnapshot) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *WorldSnapshot) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *WorldSnapshot) GetCombat() []*CombatState {
	if x != nil {
		return x.Combat
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_client_v5_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_client_v5_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_client_v5_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ActionBatch struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Shots               []*ShotRequest         `protobuf:"bytes,1,rep,name=shots,proto3" json:"shots,omitempty"`
	AcknowledgedThrough uint64                 `protobuf:"varint,2,opt,name=acknowledged_through,json=acknowledgedThrough,proto3" json:"acknowledged_through,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ActionBatch) Reset() {
	*x = ActionBatch{}
	mi := &file_client_v5_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionBatch) ProtoMessage() {}

func (x *ActionBatch) ProtoReflect() protoreflect.Message {
	mi := &file_client_v5_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionBatch.ProtoReflect.Descriptor instead.
func (*ActionBatch) Descriptor() ([]byte, []int) {
	return file_client_v5_proto_rawDescGZIP(), []int{7}
}

func (x *ActionBatch) GetShots() []*ShotRequest {
	if x != nil {
		return x.Shots
	}
	return nil
}

func (x *ActionBatch) GetAcknowledgedThrough() uint64 {
	if x != nil {
		return x.AcknowledgedThrough
	}
	return 0
}

type ActionResults struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RetiredThrough uint64                 `protobuf:"varint,1,opt,name=retired_through,json=retiredThrough,proto3" json:"retired_through,omitempty"`
	Decisions      []*ShotDecision        `protobuf:"bytes,2,rep,name=decisions,proto3" json:"decisions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActionResults) Reset() {
	*x = ActionResults{}
	mi := &file_client_v5_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResults) ProtoMessage() {}

func (x *ActionResults) ProtoReflect() protoreflect.Message {
	mi := &file_client_v5_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResults.ProtoReflect.Descriptor instead.
func (*ActionResults) Descriptor() ([]byte, []int) {
	return file_client_v5_proto_rawDescGZIP(), []int{8}
}

func (x *ActionResults) GetRetiredThrough() uint64 {
	if x != nil {
		return x.RetiredThrough
	}
	return 0
}

func (x *ActionResults) GetDecisions() []*ShotDecision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

type CombatRules struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MaximumHp             uint32                 `protobuf:"varint,1,opt,name=maximum_hp,json=maximumHp,proto3" json:"maximum_hp,omitempty"`
	ShotDamage            uint32                 `protobuf:"varint,2,opt,name=shot_damage,json=shotDamage,proto3" json:"shot_damage,omitempty"`
	CooldownTicks         uint64                 `protobuf:"varint,3,opt,name=cooldown_ticks,json=cooldownTicks,proto3" json:"cooldown_ticks,omitempty"`
	ShotRange             float32                `protobuf:"fixed32,4,opt,name=shot_range,json=shotRange,proto3" json:"shot_range,omitempty"`
	MaximumReferenceAgeMs uint32                 `protobuf:"varint,5,opt,name=maximum_reference_age_ms,json=maximumReferenceAgeMs,proto3" json:"maximum_reference_age_ms,omitempty"`
	MagazineCapacity      uint32                 `protobuf:"varint,6,opt,name=magazine_capacity,json=magazineCapacity,proto3" json:"magazine_capacity,omitempty"`
	ReloadTicks           uint64                 `protobuf:"varint,7,opt,name=reload_ticks,json=reloadTicks,proto3" json:"reload_ticks,omitempty"`
	RespawnTicks          uint64                 `protobuf:"varint,8,opt,name=respawn_ticks,json=respawnTicks,proto3" json:"respawn_ticks,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CombatRules) Reset() {
	*x = CombatRules{}
	mi := &file_client_v5_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatRules) ProtoMessage() {}

func (x *CombatRules) ProtoReflect() protoreflect.Message {
	mi := &file_client_v5_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatRules.ProtoReflect.Descriptor instead.
func (*CombatRules) Descriptor() ([]byte, []int) {
	return file_client_v5_proto_rawDescGZIP(), []int{9}
}

func (x *CombatRules) GetMaximumHp() uint32 {
	if x != nil {
		return x.MaximumHp
	}
	return 0
}

func (x *CombatRules) GetShotDamage() uint32 {
	if x != nil {
		return x.ShotDamage
	}
	return 0
}

func (x *CombatRules) GetCooldownTicks() uint64 {
	if x != nil {
		return x.CooldownTicks
	}
	return 0
}

func (x *CombatRules) GetShotRange() float32 {
	if x != nil {
		return x.ShotRange
	}
	return 0
}

func (x *CombatRules) GetMaximumReferenceAgeMs() uint32 {
	if x != nil {
		return x.MaximumReferenceAgeMs
	}
	return 0
}

func (x *CombatRules) GetMagazineCapacity() uint32 {
	if x != nil {
		return x.MagazineCapacity
	}
	return 0
}

func (x *CombatRules) GetReloadTicks() uint64 {
	if x != nil {
		return x.ReloadTicks
	}
	return 0
}

func (x *CombatRules) GetRespawnTicks() uint64 {
	if x != nil {
		return x.RespawnTicks
	}
	return 0
}

type CombatState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlayerId            uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Hp                  uint32                 `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`
	NextAllowedShotTick uint64                 `protobuf:"varint,3,opt,name=next_allowed_shot_tick,json=nextAllowedShotTick,proto3" json:"next_allowed_shot_tick,omitempty"`
	LifeGeneration      uint64                 `protobuf:"varint,4,opt,name=life_generation,json=lifeGeneration,proto3" json:"life_generation,omitempty"`
	MagazineAmmo        uint32                 `protobuf:"varint,5,opt,name=magazine_ammo,json=magazineAmmo,proto3" json:"magazine_ammo,omitempty"`
	ReloadActionId      uint64                 `protobuf:"varint,6,opt,name=reload_action_id,json=reloadActionId,proto3" json:"reload_action_id,omitempty"`
	ReloadStartTick     uint64                 `protobuf:"varint,7,opt,name=reload_start_tick,json=reloadStartTick,proto3" json:"reload_start_tick,omitempty"`
	ReloadEndTick       uint64                 `protobuf:"varint,8,opt,name=reload_end_tick,json=reloadEndTick,proto3" json:"reload_end_tick,omitempty"`
	LastShotActionId    uint64                 `protobuf:"varint,9,opt,name=last_shot_action_id,json=lastShotActionId,proto3" json:"last_shot_action_id,omitempty"`
	LastShotTick        uint64                 `protobuf:"varint,10,opt,name=last_shot_tick,json=lastShotTick,proto3" json:"last_shot_tick,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CombatState) Reset() {
	*x = CombatState{}
	mi := &file_client_v5_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatState) ProtoMessage() {}

func (x *CombatState) ProtoReflect() protoreflect.Message {
	mi := &file_client_v5_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatState.ProtoReflect.Descriptor instead.
func (*CombatState) Descriptor() ([]byte, []int) {
	return file_client_v5_proto_rawDescGZIP(), []int{10}
}

func (x *CombatState) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *CombatState) GetHp() uint32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *CombatState) GetNextAllowedShotTick() uint64 {
	if x != nil {
		return x.NextAllowedShotTick
	}
	return 0
}

func (x *CombatState) GetLifeGeneration() uint64 {
	if x != nil {
		return x.LifeGeneration
	}
	return 0
}

func (x *CombatState) GetMagazineAmmo() uint32 {
	if x != nil {
		return x.MagazineAmmo
	}
	return 0
}

func (x *CombatState) GetReloadActionId() uint64 {
	if x != nil {
		return x.ReloadActionId
	}
	return 0
}

func (x *CombatState) GetReloadStartTick() uint64 {
	if x != nil {
		return x.ReloadStartTick
	}
	return 0
}

func (x *CombatState) GetReloadEndTick() uint64 {
	if x != nil {
		return x.ReloadEndTick
	}
	return 0
}

func (x *CombatState) GetLastShotActionId() uint64 {
	if x != nil {
		return x.LastShotActionId
	}
	return 0
}

func (x *CombatState) GetLastShotTick() uint64 {
	if x != nil {
		return x.LastShotTick
	}
	return 0
}

type ShotRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ActionId              uint64                 `protobuf:"varint,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	ObservedAuthorityTick uint64                 `protobuf:"varint,2,opt,name=observed_authority_tick,json=observedAuthorityTick,proto3" json:"observed_authority_tick,omitempty"`
	Yaw                   *float32               `protobuf:"fixed32,3,opt,name=yaw,proto3,oneof" json:"yaw,omitempty"`
	Pitch                 *float32               `protobuf:"fixed32,4,opt,name=pitch,proto3,oneof" json:"pitch,omitempty"`
	Kind                  ActionKind             `protobuf:"varint,5,opt,name=kind,proto3,enum=object_fps_pvp.client.v5.ActionKind" json:"kind,omitempty"`
	LifeGeneration        uint64                 `protobuf:"varint,6,opt,name=life_generation,json=lifeGeneration,proto3" json:"life_generation,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ShotRequest) Reset() {
	*x = ShotRequest{}
	mi := &file_client_v5_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShotRequest) ProtoMessage() {}

func (x *ShotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v5_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShotRequest.ProtoReflect.Descriptor instead.
func (*ShotRequest) Descriptor() ([]byte, []int) {
	return file_client_v5_proto_rawDescGZIP(), []int{11}
}

func (x *ShotRequest) GetActionId() uint64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *ShotRequest) GetObservedAuthorityTick() uint64 {
	if x != nil {
		return x.ObservedAuthorityTick
	}
	return 0
}

func (x *ShotRequest) GetYaw() float32 {
	if x != nil && x.Yaw != nil {
		return *x.Yaw
	}
	return 0
}

func (x *ShotRequest) GetPitch() float32 {
	if x != nil && x.Pitch != nil {
		return *x.Pitch
	}
	return 0
}

func (x *ShotRequest) GetKind() ActionKind {
	if x != nil {
		return x.Kind
	}
	return ActionKind_ACTION_UNSPECIFIED
}

func (x *ShotRequest) GetLifeGeneration() uint64 {
	if x != nil {
		return x.LifeGeneration
	}
	return 0
}

type ShotDecision struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ActionId             uint64                 `protobuf:"varint,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	ResolvedTick         uint64                 `protobuf:"varint,2,opt,name=resolved_tick,json=resolvedTick,proto3" json:"resolved_tick,omitempty"`
	Accepted             bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejection            ShotRejection          `protobuf:"varint,4,opt,name=rejection,proto3,enum=object_fps_pvp.client.v5.ShotRejection" json:"rejection,omitempty"`
	HitKind              ShotHitKind            `protobuf:"varint,5,opt,name=hit_kind,json=hitKind,proto3,enum=object_fps_pvp.client.v5.ShotHitKind" json:"hit_kind,omitempty"`
	TargetId             uint64                 `protobuf:"varint,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Damage               uint32                 `protobuf:"varint,7,opt,name=damage,proto3" json:"damage,omitempty"`
	Kind                 ActionKind             `protobuf:"varint,8,opt,name=kind,proto3,enum=object_fps_pvp.client.v5.ActionKind" json:"kind,omitempty"`
	LifeGeneration       uint64                 `protobuf:"varint,9,opt,name=life_generation,json=lifeGeneration,proto3" json:"life_generation,omitempty"`
	TargetLifeGeneration uint64                 `protobuf:"varint,10,opt,name=target_life_generation,json=targetLifeGeneration,proto3" json:"target_life_generation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ShotDecision) Reset() {
	*x = ShotDecision{}
	mi := &file_client_v5_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShotDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShotDecision) ProtoMessage() {}

func (x *ShotDecision) ProtoReflect() protoreflect.Message {
	mi := &file_client_v5_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShotDecision.ProtoReflect.Descriptor instead.
func (*ShotDecision) Descriptor() ([]byte, []int) {
	return file_client_v5_proto_rawDescGZIP(), []int{12}
}

func (x *ShotDecision) GetActionId() uint64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *ShotDecision) GetResolvedTick() uint64 {
	if x != nil {
		return x.ResolvedTick
	}
	return 0
}

func (x *ShotDecision) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ShotDecision) GetRejection() ShotRejection {
	if x != nil {
		return x.Rejection
	}
	return ShotRejection_REJECTION_NONE
}

func (x *ShotDecision) GetHitKind() ShotHitKind {
	if x != nil {
		return x.HitKind
	}
	return ShotHitKind_HIT_MISS
}

func (x *ShotDecision) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ShotDecision) GetDamage() uint32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *ShotDecision) GetKind() ActionKind {
	if x != nil {
		return x.Kind
	}
	return ActionKind_ACTION_UNSPECIFIED
}

func (x *ShotDecision) GetLifeGeneration() uint64 {
	if x != nil {
		return x.LifeGeneration
	}
	return 0
}

func (x *ShotDecision) GetTargetLifeGeneration() uint64 {
	if x != nil {
		return x.TargetLifeGeneration
	}
	return 0
}

var File_client_v5_proto protoreflect.FileDescriptor

const file_client_v5_proto_rawDesc = "" +
	"\n" +
	"\x0fclient_v5.proto\x12\x18object_fps_pvp.client.v5\",\n" +
	"\x05Hello\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\"\xc8\x02\n" +
	"\aWelcome\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x19\n" +
	"\bmatch_id\x18\x02 \x01(\x04R\amatchId\x12\x1b\n" +
	"\ttick_rate\x18\x03 \x01(\rR\btickRate\x12#\n" +
	"\rsnapshot_rate\x18\x04 \x01(\rR\fsnapshotRate\x12\x19\n" +
	"\barena_id\x18\x05 \x01(\tR\aarenaId\x12#\n" +
	"\rarena_version\x18\x06 \x01(\rR\farenaVersion\x12H\n" +
	"\fcombat_rules\x18\a \x01(\v2%.object_fps_pvp.client.v5.CombatRulesR\vcombatRules\x12\x1f\n" +
	"\vjump_height\x18\b \x01(\x02R\n" +
	"jumpHeight\x12\x18\n" +
	"\agravity\x18\t \x01(\x02R\agravity\"\xbe\x01\n" +
	"\x0fMovementCommand\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12!\n" +
	"\fmove_forward\x18\x02 \x01(\x02R\vmoveForward\x12\x1d\n" +
	"\n" +
	"move_right\x18\x03 \x01(\x02R\tmoveRight\x12\x10\n" +
	"\x03yaw\x18\x04 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x05 \x01(\x02R\x05pitch\x12%\n" +
	"\x0ejump_requested\x18\x06 \x01(\bR\rjumpRequested\"\xdc\x01\n" +
	"\vPlayerInput\x12E\n" +
	"\bcommands\x18\x01 \x03(\v2).object_fps_pvp.client.v5.MovementCommandR\bcommands\x12%\n" +
	"\x0emovement_epoch\x18\x02 \x01(\x04R\rmovementEpoch\x12'\n" +
	"\x0flife_generation\x18\x03 \x01(\x04R\x0elifeGeneration\x126\n" +
	"\x17observed_authority_tick\x18\x04 \x01(\x04R\x15observedAuthorityTick\"\x93\x06\n" +
	"\vPlayerState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x02R\x01z\x12\x10\n" +
	"\x03yaw\x18\x05 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x06 \x01(\x02R\x05pitch\x122\n" +
	"\x15last_resolved_command\x18\a \x01(\x04R\x13lastResolvedCommand\x12%\n" +
	"\x0emovement_epoch\x18\b \x01(\x04R\rmovementEpoch\x12>\n" +
	"\x1bcontiguous_pending_commands\x18\t \x01(\rR\x19contiguousPendingCommands\x12+\n" +
	"\x11vertical_velocity\x18\n" +
	" \x01(\x02R\x10verticalVelocity\x12\x1a\n" +
	"\bgrounded\x18\v \x01(\bR\bgrounded\x12'\n" +
	"\x0flife_generation\x18\f \x01(\x04R\x0elifeGeneration\x12B\n" +
	"\n" +
	"life_state\x18\r \x01(\x0e2#.object_fps_pvp.client.v5.LifeStateR\tlifeState\x12&\n" +
	"\x0flife_state_tick\x18\x0e \x01(\x04R\rlifeStateTick\x12!\n" +
	"\frespawn_tick\x18\x0f \x01(\x04R\vrespawnTick\x12;\n" +
	"\x17movement_slack_sequence\x18\x11 \x01(\x04H\x00R\x15movementSlackSequence\x88\x01\x01\x12/\n" +
	"\x11movement_slack_us\x18\x12 \x01(\x11H\x01R\x0fmovementSlackUs\x88\x01\x01\x12>\n" +
	"\x1bconnection_quality_failures\x18\x13 \x01(\rR\x19connectionQualityFailuresB\x1a\n" +
	"\x18_movement_slack_sequenceB\x14\n" +
	"\x12_movement_slack_usJ\x04\b\x10\x10\x11R\x13epoch_start_wait_us\"\xa3\x01\n" +
	"\rWorldSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12?\n" +
	"\aplayers\x18\x02 \x03(\v2%.object_fps_pvp.client.v5.PlayerStateR\aplayers\x12=\n" +
	"\x06combat\x18\x03 \x03(\v2%.object_fps_pvp.client.v5.CombatStateR\x06combat\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"}\n" +
	"\vActionBatch\x12;\n" +
	"\x05shots\x18\x01 \x03(\v2%.object_fps_pvp.client.v5.ShotRequestR\x05shots\x121\n" +
	"\x14acknowledged_through\x18\x02 \x01(\x04R\x13acknowledgedThrough\"~\n" +
	"\rActionResults\x12'\n" +
	"\x0fretired_through\x18\x01 \x01(\x04R\x0eretiredThrough\x12D\n" +
	"\tdecisions\x18\x02 \x03(\v2&.object_fps_pvp.client.v5.ShotDecisionR\tdecisions\"\xc1\x02\n" +
	"\vCombatRules\x12\x1d\n" +
	"\n" +
	"maximum_hp\x18\x01 \x01(\rR\tmaximumHp\x12\x1f\n" +
	"\vshot_damage\x18\x02 \x01(\rR\n" +
	"shotDamage\x12%\n" +
	"\x0ecooldown_ticks\x18\x03 \x01(\x04R\rcooldownTicks\x12\x1d\n" +
	"\n" +
	"shot_range\x18\x04 \x01(\x02R\tshotRange\x127\n" +
	"\x18maximum_reference_age_ms\x18\x05 \x01(\rR\x15maximumReferenceAgeMs\x12+\n" +
	"\x11magazine_capacity\x18\x06 \x01(\rR\x10magazineCapacity\x12!\n" +
	"\freload_ticks\x18\a \x01(\x04R\vreloadTicks\x12#\n" +
	"\rrespawn_ticks\x18\b \x01(\x04R\frespawnTicks\"\x90\x03\n" +
	"\vCombatState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x0e\n" +
	"\x02hp\x18\x02 \x01(\rR\x02hp\x123\n" +
	"\x16next_allowed_shot_tick\x18\x03 \x01(\x04R\x13nextAllowedShotTick\x12'\n" +
	"\x0flife_generation\x18\x04 \x01(\x04R\x0elifeGeneration\x12#\n" +
	"\rmagazine_ammo\x18\x05 \x01(\rR\fmagazineAmmo\x12(\n" +
	"\x10reload_action_id\x18\x06 \x01(\x04R\x0ereloadActionId\x12*\n" +
	"\x11reload_start_tick\x18\a \x01(\x04R\x0freloadStartTick\x12&\n" +
	"\x0freload_end_tick\x18\b \x01(\x04R\rreloadEndTick\x12-\n" +
	"\x13last_shot_action_id\x18\t \x01(\x04R\x10lastShotActionId\x12$\n" +
	"\x0elast_shot_tick\x18\n" +
	" \x01(\x04R\flastShotTick\"\x89\x02\n" +
	"\vShotRequest\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\x04R\bactionId\x126\n" +
	"\x17observed_authority_tick\x18\x02 \x01(\x04R\x15observedAuthorityTick\x12\x15\n" +
	"\x03yaw\x18\x03 \x01(\x02H\x00R\x03yaw\x88\x01\x01\x12\x19\n" +
	"\x05pitch\x18\x04 \x01(\x02H\x01R\x05pitch\x88\x01\x01\x128\n" +
	"\x04kind\x18\x05 \x01(\x0e2$.object_fps_pvp.client.v5.ActionKindR\x04kind\x12'\n" +
	"\x0flife_generation\x18\x06 \x01(\x04R\x0elifeGenerationB\x06\n" +
	"\x04_yawB\b\n" +
	"\x06_pitch\"\xc3\x03\n" +
	"\fShotDecision\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\x04R\bactionId\x12#\n" +
	"\rresolved_tick\x18\x02 \x01(\x04R\fresolvedTick\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\x12E\n" +
	"\trejection\x18\x04 \x01(\x0e2'.object_fps_pvp.client.v5.ShotRejectionR\trejection\x12@\n" +
	"\bhit_kind\x18\x05 \x01(\x0e2%.object_fps_pvp.client.v5.ShotHitKindR\ahitKind\x12\x1b\n" +
	"\ttarget_id\x18\x06 \x01(\x04R\btargetId\x12\x16\n" +
	"\x06damage\x18\a \x01(\rR\x06damage\x128\n" +
	"\x04kind\x18\b \x01(\x0e2$.object_fps_pvp.client.v5.ActionKindR\x04kind\x12'\n" +
	"\x0flife_generation\x18\t \x01(\x04R\x0elifeGeneration\x124\n" +
	"\x16target_life_generation\x18\n" +
	" \x01(\x04R\x14targetLifeGeneration*@\n" +
	"\tLifeState\x12\x14\n" +
	"\x10LIFE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"LIFE_ALIVE\x10\x01\x12\r\n" +
	"\tLIFE_DEAD\x10\x02*H\n" +
	"\n" +
	"ActionKind\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vACTION_SHOT\x10\x01\x12\x11\n" +
	"\rACTION_RELOAD\x10\x02*\x91\x02\n" +
	"\rShotRejection\x12\x12\n" +
	"\x0eREJECTION_NONE\x10\x00\x12\x1f\n" +
	"\x1bREJECTION_INVALID_REFERENCE\x10\x01\x12\x15\n" +
	"\x11REJECTION_EXPIRED\x10\x02\x12\x16\n" +
	"\x12REJECTION_COOLDOWN\x10\x03\x12\x18\n" +
	"\x14REJECTION_STALE_LIFE\x10\x04\x12\x1a\n" +
	"\x16REJECTION_INVALID_LIFE\x10\x05\x12\x12\n" +
	"\x0eREJECTION_DEAD\x10\x06\x12\x17\n" +
	"\x13REJECTION_RELOADING\x10\a\x12\x1c\n" +
	"\x18REJECTION_EMPTY_MAGAZINE\x10\b\x12\x1b\n" +
	"\x17REJECTION_MAGAZINE_FULL\x10\t*:\n" +
	"\vShotHitKind\x12\f\n" +
	"\bHIT_MISS\x10\x00\x12\r\n" +
	"\tHIT_WORLD\x10\x01\x12\x0e\n" +
	"\n" +
	"HIT_PLAYER\x10\x02B,Z*gyo.local/object_fps_pvp/protocol/clientv5b\x06proto3"

var (
	file_client_v5_proto_rawDescOnce sync.Once
	file_client_v5_proto_rawDescData []byte
)

func file_client_v5_proto_rawDescGZIP() []byte {
	file_client_v5_proto_rawDescOnce.Do(func() {
		file_client_v5_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_v5_proto_rawDesc), len(file_client_v5_proto_rawDesc)))
	})
	return file_client_v5_proto_rawDescData
}

var file_client_v5_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_client_v5_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_client_v5_proto_goTypes = []any{
	(LifeState)(0),          // 0: object_fps_pvp.client.v5.LifeState
	(ActionKind)(0),         // 1: object_fps_pvp.client.v5.ActionKind
	(ShotRejection)(0),      // 2: object_fps_pvp.client.v5.ShotRejection
	(ShotHitKind)(0),        // 3: object_fps_pvp.client.v5.ShotHitKind
	(*Hello)(nil),           // 4: object_fps_pvp.client.v5.Hello
	(*Welcome)(nil),         // 5: object_fps_pvp.client.v5.Welcome
	(*MovementCommand)(nil), // 6: object_fps_pvp.client.v5.MovementCommand
	(*PlayerInput)(nil),     // 7: object_fps_pvp.client.v5.PlayerInput
	(*PlayerState)(nil),     // 8: object_fps_pvp.client.v5.PlayerState
	(*WorldSnapshot)(nil),   // 9: object_fps_pvp.client.v5.WorldSnapshot
	(*Error)(nil),           // 10: object_fps_pvp.client.v5.Error
	(*ActionBatch)(nil),     // 11: object_fps_pvp.client.v5.ActionBatch
	(*ActionResults)(nil),   // 12: object_fps_pvp.client.v5.ActionResults
	(*CombatRules)(nil),     // 13: object_fps_pvp.client.v5.CombatRules
	(*CombatState)(nil),     // 14: object_fps_pvp.client.v5.CombatState
	(*ShotRequest)(nil),     // 15: object_fps_pvp.client.v5.ShotRequest
	(*ShotDecision)(nil),    // 16: object_fps_pvp.client.v5.ShotDecision
}
var file_client_v5_proto_depIdxs = []int32{
	13, // 0: object_fps_pvp.client.v5.Welcome.combat_rules:type_name -> object_fps_pvp.client.v5.CombatRules
	6,  // 1: object_fps_pvp.client.v5.PlayerInput.commands:type_name -> object_fps_pvp.client.v5.MovementCommand
	0,  // 2: object_fps_pvp.client.v5.PlayerState.life_state:type_name -> object_fps_pvp.client.v5.LifeState
	8,  // 3: object_fps_pvp.client.v5.WorldSnapshot.players:type_name -> object_fps_pvp.client.v5.PlayerState
	14, // 4: object_fps_pvp.client.v5.WorldSnapshot.combat:type_name -> object_fps_pvp.client.v5.CombatState
	15, // 5: object_fps_pvp.client.v5.ActionBatch.shots:type_name -> object_fps_pvp.client.v5.ShotRequest
	16, // 6: object_fps_pvp.client.v5.ActionResults.decisions:type_name -> object_fps_pvp.client.v5.ShotDecision
	1,  // 7: object_fps_pvp.client.v5.ShotRequest.kind:type_name -> object_fps_pvp.client.v5.ActionKind
	2,  // 8: object_fps_pvp.client.v5.ShotDecision.rejection:type_name -> object_fps_pvp.client.v5.ShotRejection
	3,  // 9: object_fps_pvp.client.v5.ShotDecision.hit_kind:type_name -> object_fps_pvp.client.v5.ShotHitKind
	1,  // 10: object_fps_pvp.client.v5.ShotDecision.kind:type_name -> object_fps_pvp.client.v5.ActionKind
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_client_v5_proto_init() }
func file_client_v5_proto_init() {
	if File_client_v5_proto != nil {
		return
	}
	file_client_v5_proto_msgTypes[4].OneofWrappers = []any{}
	file_client_v5_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_v5_proto_rawDesc), len(file_client_v5_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_v5_proto_goTypes,
		DependencyIndexes: file_client_v5_proto_depIdxs,
		EnumInfos:         file_client_v5_proto_enumTypes,
		MessageInfos:      file_client_v5_proto_msgTypes,
	}.Build()
	File_client_v5_proto = out.File
	file_client_v5_proto_goTypes = nil
	file_client_v5_proto_depIdxs = nil
}
