// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: client_v1.proto

package clientv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This remote-client contract is independent of runtime_v1.proto.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_client_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_client_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MatchId       uint64                 `protobuf:"varint,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	TickRate      uint32                 `protobuf:"varint,3,opt,name=tick_rate,json=tickRate,proto3" json:"tick_rate,omitempty"`
	SnapshotRate  uint32                 `protobuf:"varint,4,opt,name=snapshot_rate,json=snapshotRate,proto3" json:"snapshot_rate,omitempty"`
	ArenaId       string                 `protobuf:"bytes,5,opt,name=arena_id,json=arenaId,proto3" json:"arena_id,omitempty"`
	ArenaVersion  uint32                 `protobuf:"varint,6,opt,name=arena_version,json=arenaVersion,proto3" json:"arena_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_client_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_client_v1_proto_rawDescGZIP(), []int{1}
}

func (x *Welcome) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Welcome) GetMatchId() uint64 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

func (x *Welcome) GetTickRate() uint32 {
	if x != nil {
		return x.TickRate
	}
	return 0
}

func (x *Welcome) GetSnapshotRate() uint32 {
	if x != nil {
		return x.SnapshotRate
	}
	return 0
}

func (x *Welcome) GetArenaId() string {
	if x != nil {
		return x.ArenaId
	}
	return ""
}

func (x *Welcome) GetArenaVersion() uint32 {
	if x != nil {
		return x.ArenaVersion
	}
	return 0
}

type PlayerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputSequence uint64                 `protobuf:"varint,1,opt,name=input_sequence,json=inputSequence,proto3" json:"input_sequence,omitempty"`
	ClientTick    uint64                 `protobuf:"varint,2,opt,name=client_tick,json=clientTick,proto3" json:"client_tick,omitempty"`
	MoveForward   float32                `protobuf:"fixed32,3,opt,name=move_forward,json=moveForward,proto3" json:"move_forward,omitempty"`
	MoveRight     float32                `protobuf:"fixed32,4,opt,name=move_right,json=moveRight,proto3" json:"move_right,omitempty"`
	Yaw           float32                `protobuf:"fixed32,5,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch         float32                `protobuf:"fixed32,6,opt,name=pitch,proto3" json:"pitch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_client_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_client_v1_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerInput) GetInputSequence() uint64 {
	if x != nil {
		return x.InputSequence
	}
	return 0
}

func (x *PlayerInput) GetClientTick() uint64 {
	if x != nil {
		return x.ClientTick
	}
	return 0
}

func (x *PlayerInput) GetMoveForward() float32 {
	if x != nil {
		return x.MoveForward
	}
	return 0
}

func (x *PlayerInput) GetMoveRight() float32 {
	if x != nil {
		return x.MoveRight
	}
	return 0
}

func (x *PlayerInput) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *PlayerInput) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

type PlayerState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PlayerId          uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X                 float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                 float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z                 float32                `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	Yaw               float32                `protobuf:"fixed32,5,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch             float32                `protobuf:"fixed32,6,opt,name=pitch,proto3" json:"pitch,omitempty"`
	LastInputSequence uint64                 `protobuf:"varint,7,opt,name=last_input_sequence,json=lastInputSequence,proto3" json:"last_input_sequence,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_client_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_client_v1_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerState) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerState) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerState) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *PlayerState) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *PlayerState) GetLastInputSequence() uint64 {
	if x != nil {
		return x.LastInputSequence
	}
	return 0
}

type WorldSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Players       []*PlayerState         `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldSnapshot) Reset() {
	*x = WorldSnapshot{}
	mi := &file_client_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldSnapshot) ProtoMessage() {}

func (x *WorldSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldSnapshot.ProtoReflect.Descriptor instead.
func (*WorldSnapshot) Descriptor() ([]byte, []int) {
	return file_client_v1_proto_rawDescGZIP(), []int{4}
}

func (x *WorldSnapshot) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *WorldSnapshot) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_client_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_client_v1_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_client_v1_proto protoreflect.FileDescriptor

const file_client_v1_proto_rawDesc = "" +
	"\n" +
	"\x0fclient_v1.proto\x12\x18object_fps_pvp.client.v1\",\n" +
	"\x05Hello\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\"\xc3\x01\n" +
	"\aWelcome\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x19\n" +
	"\bmatch_id\x18\x02 \x01(\x04R\amatchId\x12\x1b\n" +
	"\ttick_rate\x18\x03 \x01(\rR\btickRate\x12#\n" +
	"\rsnapshot_rate\x18\x04 \x01(\rR\fsnapshotRate\x12\x19\n" +
	"\barena_id\x18\x05 \x01(\tR\aarenaId\x12#\n" +
	"\rarena_version\x18\x06 \x01(\rR\farenaVersion\"\xbf\x01\n" +
	"\vPlayerInput\x12%\n" +
	"\x0einput_sequence\x18\x01 \x01(\x04R\rinputSequence\x12\x1f\n" +
	"\vclient_tick\x18\x02 \x01(\x04R\n" +
	"clientTick\x12!\n" +
	"\fmove_forward\x18\x03 \x01(\x02R\vmoveForward\x12\x1d\n" +
	"\n" +
	"move_right\x18\x04 \x01(\x02R\tmoveRight\x12\x10\n" +
	"\x03yaw\x18\x05 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x06 \x01(\x02R\x05pitch\"\xac\x01\n" +
	"\vPlayerState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x02R\x01z\x12\x10\n" +
	"\x03yaw\x18\x05 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x06 \x01(\x02R\x05pitch\x12.\n" +
	"\x13last_input_sequence\x18\a \x01(\x04R\x11lastInputSequence\"d\n" +
	"\rWorldSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12?\n" +
	"\aplayers\x18\x02 \x03(\v2%.object_fps_pvp.client.v1.PlayerStateR\aplayers\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB,Z*gyo.local/object_fps_pvp/protocol/clientv1b\x06proto3"

var (
	file_client_v1_proto_rawDescOnce sync.Once
	file_client_v1_proto_rawDescData []byte
)

func file_client_v1_proto_rawDescGZIP() []byte {
	file_client_v1_proto_rawDescOnce.Do(func() {
		file_client_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_v1_proto_rawDesc), len(file_client_v1_proto_rawDesc)))
	})
	return file_client_v1_proto_rawDescData
}

var file_client_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_client_v1_proto_goTypes = []any{
	(*Hello)(nil),         // 0: object_fps_pvp.client.v1.Hello
	(*Welcome)(nil),       // 1: object_fps_pvp.client.v1.Welcome
	(*PlayerInput)(nil),   // 2: object_fps_pvp.client.v1.PlayerInput
	(*PlayerState)(nil),   // 3: object_fps_pvp.client.v1.PlayerState
	(*WorldSnapshot)(nil), // 4: object_fps_pvp.client.v1.WorldSnapshot
	(*Error)(nil),         // 5: object_fps_pvp.client.v1.Error
}
var file_client_v1_proto_depIdxs = []int32{
	3, // 0: object_fps_pvp.client.v1.WorldSnapshot.players:type_name -> object_fps_pvp.client.v1.PlayerState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_client_v1_proto_init() }
func file_client_v1_proto_init() {
	if File_client_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_v1_proto_rawDesc), len(file_client_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_v1_proto_goTypes,
		DependencyIndexes: file_client_v1_proto_depIdxs,
		MessageInfos:      file_client_v1_proto_msgTypes,
	}.Build()
	File_client_v1_proto = out.File
	file_client_v1_proto_goTypes = nil
	file_client_v1_proto_depIdxs = nil
}
