// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: runtime_v6.proto

package runtimev6

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LifeState int32

const (
	LifeState_LIFE_UNSPECIFIED LifeState = 0
	LifeState_LIFE_ALIVE       LifeState = 1
	LifeState_LIFE_DEAD        LifeState = 2
)

// Enum value maps for LifeState.
var (
	LifeState_name = map[int32]string{
		0: "LIFE_UNSPECIFIED",
		1: "LIFE_ALIVE",
		2: "LIFE_DEAD",
	}
	LifeState_value = map[string]int32{
		"LIFE_UNSPECIFIED": 0,
		"LIFE_ALIVE":       1,
		"LIFE_DEAD":        2,
	}
)

func (x LifeState) Enum() *LifeState {
	p := new(LifeState)
	*p = x
	return p
}

func (x LifeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifeState) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v6_proto_enumTypes[0].Descriptor()
}

func (LifeState) Type() protoreflect.EnumType {
	return &file_runtime_v6_proto_enumTypes[0]
}

func (x LifeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LifeState.Descriptor instead.
func (LifeState) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{0}
}

// Match-initiated removal for sustained poor connection quality. The Gateway
// clears the player like a Leave and tells the Client why.
type EvictionReason int32

const (
	EvictionReason_EVICTION_UNSPECIFIED    EvictionReason = 0
	EvictionReason_EVICTION_HIGH_LATENCY   EvictionReason = 1
	EvictionReason_EVICTION_UNSTABLE_INPUT EvictionReason = 2
)

// Enum value maps for EvictionReason.
var (
	EvictionReason_name = map[int32]string{
		0: "EVICTION_UNSPECIFIED",
		1: "EVICTION_HIGH_LATENCY",
		2: "EVICTION_UNSTABLE_INPUT",
	}
	EvictionReason_value = map[string]int32{
		"EVICTION_UNSPECIFIED":    0,
		"EVICTION_HIGH_LATENCY":   1,
		"EVICTION_UNSTABLE_INPUT": 2,
	}
)

func (x EvictionReason) Enum() *EvictionReason {
	p := new(EvictionReason)
	*p = x
	return p
}

func (x EvictionReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvictionReason) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v6_proto_enumTypes[1].Descriptor()
}

func (EvictionReason) Type() protoreflect.EnumType {
	return &file_runtime_v6_proto_enumTypes[1]
}

func (x EvictionReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvictionReason.Descriptor instead.
func (EvictionReason) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{1}
}

// Historical names are retained; requests and decisions cover Shot and Reload.
type ActionKind int32

const (
	ActionKind_ACTION_UNSPECIFIED ActionKind = 0
	ActionKind_ACTION_SHOT        ActionKind = 1
	ActionKind_ACTION_RELOAD      ActionKind = 2
)

// Enum value maps for ActionKind.
var (
	ActionKind_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_SHOT",
		2: "ACTION_RELOAD",
	}
	ActionKind_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_SHOT":        1,
		"ACTION_RELOAD":      2,
	}
)

func (x ActionKind) Enum() *ActionKind {
	p := new(ActionKind)
	*p = x
	return p
}

func (x ActionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v6_proto_enumTypes[2].Descriptor()
}

func (ActionKind) Type() protoreflect.EnumType {
	return &file_runtime_v6_proto_enumTypes[2]
}

func (x ActionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionKind.Descriptor instead.
func (ActionKind) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{2}
}

type ShotRejection int32

const (
	ShotRejection_REJECTION_NONE              ShotRejection = 0
	ShotRejection_REJECTION_INVALID_REFERENCE ShotRejection = 1
	ShotRejection_REJECTION_EXPIRED           ShotRejection = 2
	ShotRejection_REJECTION_COOLDOWN          ShotRejection = 3
	ShotRejection_REJECTION_STALE_LIFE        ShotRejection = 4
	ShotRejection_REJECTION_INVALID_LIFE      ShotRejection = 5
	ShotRejection_REJECTION_DEAD              ShotRejection = 6
	ShotRejection_REJECTION_RELOADING         ShotRejection = 7
	ShotRejection_REJECTION_EMPTY_MAGAZINE    ShotRejection = 8
	ShotRejection_REJECTION_MAGAZINE_FULL     ShotRejection = 9
)

// Enum value maps for ShotRejection.
var (
	ShotRejection_name = map[int32]string{
		0: "REJECTION_NONE",
		1: "REJECTION_INVALID_REFERENCE",
		2: "REJECTION_EXPIRED",
		3: "REJECTION_COOLDOWN",
		4: "REJECTION_STALE_LIFE",
		5: "REJECTION_INVALID_LIFE",
		6: "REJECTION_DEAD",
		7: "REJECTION_RELOADING",
		8: "REJECTION_EMPTY_MAGAZINE",
		9: "REJECTION_MAGAZINE_FULL",
	}
	ShotRejection_value = map[string]int32{
		"REJECTION_NONE":              0,
		"REJECTION_INVALID_REFERENCE": 1,
		"REJECTION_EXPIRED":           2,
		"REJECTION_COOLDOWN":          3,
		"REJECTION_STALE_LIFE":        4,
		"REJECTION_INVALID_LIFE":      5,
		"REJECTION_DEAD":              6,
		"REJECTION_RELOADING":         7,
		"REJECTION_EMPTY_MAGAZINE":    8,
		"REJECTION_MAGAZINE_FULL":     9,
	}
)

func (x ShotRejection) Enum() *ShotRejection {
	p := new(ShotRejection)
	*p = x
	return p
}

func (x ShotRejection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShotRejection) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v6_proto_enumTypes[3].Descriptor()
}

func (ShotRejection) Type() protoreflect.EnumType {
	return &file_runtime_v6_proto_enumTypes[3]
}

func (x ShotRejection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShotRejection.Descriptor instead.
func (ShotRejection) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{3}
}

type ShotHitKind int32

const (
	ShotHitKind_HIT_MISS   ShotHitKind = 0
	ShotHitKind_HIT_WORLD  ShotHitKind = 1
	ShotHitKind_HIT_PLAYER ShotHitKind = 2
)

// Enum value maps for ShotHitKind.
var (
	ShotHitKind_name = map[int32]string{
		0: "HIT_MISS",
		1: "HIT_WORLD",
		2: "HIT_PLAYER",
	}
	ShotHitKind_value = map[string]int32{
		"HIT_MISS":   0,
		"HIT_WORLD":  1,
		"HIT_PLAYER": 2,
	}
)

func (x ShotHitKind) Enum() *ShotHitKind {
	p := new(ShotHitKind)
	*p = x
	return p
}

func (x ShotHitKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShotHitKind) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v6_proto_enumTypes[4].Descriptor()
}

func (ShotHitKind) Type() protoreflect.EnumType {
	return &file_runtime_v6_proto_enumTypes[4]
}

func (x ShotHitKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShotHitKind.Descriptor instead.
func (ShotHitKind) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{4}
}

// The local IPC host decodes this into product data. Match never sees protobuf,
// sessions, endpoints, or wire envelopes.
type Ready struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ArenaId               string                 `protobuf:"bytes,1,opt,name=arena_id,json=arenaId,proto3" json:"arena_id,omitempty"`
	ArenaVersion          uint32                 `protobuf:"varint,2,opt,name=arena_version,json=arenaVersion,proto3" json:"arena_version,omitempty"`
	TickRate              uint32                 `protobuf:"varint,3,opt,name=tick_rate,json=tickRate,proto3" json:"tick_rate,omitempty"`
	SnapshotIntervalTicks uint32                 `protobuf:"varint,4,opt,name=snapshot_interval_ticks,json=snapshotIntervalTicks,proto3" json:"snapshot_interval_ticks,omitempty"`
	MaxPlayers            uint32                 `protobuf:"varint,5,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	CombatRules           *CombatRules           `protobuf:"bytes,6,opt,name=combat_rules,json=combatRules,proto3" json:"combat_rules,omitempty"`
	JumpHeight            float32                `protobuf:"fixed32,7,opt,name=jump_height,json=jumpHeight,proto3" json:"jump_height,omitempty"`
	Gravity               float32                `protobuf:"fixed32,8,opt,name=gravity,proto3" json:"gravity,omitempty"`
	// Content digest of the served arena (pv6 contract §2); 0 means missing.
	ArenaDigest   uint64 `protobuf:"fixed64,9,opt,name=arena_digest,json=arenaDigest,proto3" json:"arena_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_runtime_v6_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v6_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{0}
}

func (x *Ready) GetArenaId() string {
	if x != nil {
		return x.ArenaId
	}
	return ""
}

func (x *Ready) GetArenaVersion() uint32 {
	if x != nil {
		return x.ArenaVersion
	}
	return 0
}

func (x *Ready) GetTickRate() uint32 {
	if x != nil {
		return x.TickRate
	}
	return 0
}

func (x *Ready) GetSnapshotIntervalTicks() uint32 {
	if x != nil {
		return x.SnapshotIntervalTicks
	}
	return 0
}

func (x *Ready) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *Ready) GetCombatRules() *CombatRules {
	if x != nil {
		return x.CombatRules
	}
	return nil
}

func (x *Ready) GetJumpHeight() float32 {
	if x != nil {
		return x.JumpHeight
	}
	return 0
}

func (x *Ready) GetGravity() float32 {
	if x != nil {
		return x.Gravity
	}
	return 0
}

func (x *Ready) GetArenaDigest() uint64 {
	if x != nil {
		return x.ArenaDigest
	}
	return 0
}

type PlayerJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoin) Reset() {
	*x = PlayerJoin{}
	mi := &file_runtime_v6_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoin) ProtoMessage() {}

func (x *PlayerJoin) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v6_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoin.ProtoReflect.Descriptor instead.
func (*PlayerJoin) Descriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerJoin) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type PlayerLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeave) Reset() {
	*x = PlayerLeave{}
	mi := &file_runtime_v6_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeave) ProtoMessage() {}

func (x *PlayerLeave) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v6_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeave.ProtoReflect.Descriptor instead.
func (*PlayerLeave) Descriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerLeave) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// A single immutable 1/60-second movement step. No client time or position.
type MovementCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	MoveForward   float32                `protobuf:"fixed32,2,opt,name=move_forward,json=moveForward,proto3" json:"move_forward,omitempty"`
	MoveRight     float32                `protobuf:"fixed32,3,opt,name=move_right,json=moveRight,proto3" json:"move_right,omitempty"`
	Yaw           float32                `protobuf:"fixed32,4,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch         float32                `protobuf:"fixed32,5,opt,name=pitch,proto3" json:"pitch,omitempty"`
	JumpRequested bool                   `protobuf:"varint,6,opt,name=jump_requested,json=jumpRequested,proto3" json:"jump_requested,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovementCommand) Reset() {
	*x = MovementCommand{}
	mi := &file_runtime_v6_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovementCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovementCommand) ProtoMessage() {}

func (x *MovementCommand) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v6_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovementCommand.ProtoReflect.Descriptor instead.
func (*MovementCommand) Descriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{3}
}

func (x *MovementCommand) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MovementCommand) GetMoveForward() float32 {
	if x != nil {
		return x.MoveForward
	}
	return 0
}

func (x *MovementCommand) GetMoveRight() float32 {
	if x != nil {
		return x.MoveRight
	}
	return 0
}

func (x *MovementCommand) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *MovementCommand) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *MovementCommand) GetJumpRequested() bool {
	if x != nil {
		return x.JumpRequested
	}
	return false
}

// Entire unacknowledged window, strictly ordered, at most 12 commands.
type PlayerInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Commands       []*MovementCommand     `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	MovementEpoch  uint64                 `protobuf:"varint,3,opt,name=movement_epoch,json=movementEpoch,proto3" json:"movement_epoch,omitempty"`
	LifeGeneration uint64                 `protobuf:"varint,4,opt,name=life_generation,json=lifeGeneration,proto3" json:"life_generation,omitempty"`
	// Latest snapshot tick the Client applied; merged windows carry the largest.
	ObservedAuthorityTick uint64 `protobuf:"varint,5,opt,name=observed_authority_tick,json=observedAuthorityTick,proto3" json:"observed_authority_tick,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_runtime_v6_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v6_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerInput) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerInput) GetCommands() []*MovementCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *PlayerInput) GetMovementEpoch() uint64 {
	if x != nil {
		return x.MovementEpoch
	}
	return 0
}

func (x *PlayerInput) GetLifeGeneration() uint64 {
	if x != nil {
		return x.LifeGeneration
	}
	return 0
}

func (x *PlayerInput) GetObservedAuthorityTick() uint64 {
	if x != nil {
		return x.ObservedAuthorityTick
	}
	return 0
}

type JoinResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResult) Reset() {
	*x = JoinResult{}
	mi := &file_runtime_v6_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResult) ProtoMessage() {}

func (x *JoinResult) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v6_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResult.ProtoReflect.Descriptor instead.
func (*JoinResult) Descriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{5}
}

func (x *JoinResult) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *JoinResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *JoinResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PlayerState struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	PlayerId                  uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X                         float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                         float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z                         float32                `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	Yaw                       float32                `protobuf:"fixed32,5,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch                     float32                `protobuf:"fixed32,6,opt,name=pitch,proto3" json:"pitch,omitempty"`
	LastResolvedCommand       uint64                 `protobuf:"varint,7,opt,name=last_resolved_command,json=lastResolvedCommand,proto3" json:"last_resolved_command,omitempty"`
	MovementEpoch             uint64                 `protobuf:"varint,8,opt,name=movement_epoch,json=movementEpoch,proto3" json:"movement_epoch,omitempty"`
	ContiguousPendingCommands uint32                 `protobuf:"varint,9,opt,name=contiguous_pending_commands,json=contiguousPendingCommands,proto3" json:"contiguous_pending_commands,omitempty"`
	VerticalVelocity          float32                `protobuf:"fixed32,10,opt,name=vertical_velocity,json=verticalVelocity,proto3" json:"vertical_velocity,omitempty"`
	Grounded                  bool                   `protobuf:"varint,11,opt,name=grounded,proto3" json:"grounded,omitempty"`
	LifeGeneration            uint64                 `protobuf:"varint,12,opt,name=life_generation,json=lifeGeneration,proto3" json:"life_generation,omitempty"`
	LifeState                 LifeState              `protobuf:"varint,13,opt,name=life_state,json=lifeState,proto3,enum=object_fps_pvp.runtime.v6.LifeState" json:"life_state,omitempty"`
	LifeStateTick             uint64                 `protobuf:"varint,14,opt,name=life_state_tick,json=lifeStateTick,proto3" json:"life_state_tick,omitempty"`
	RespawnTick               uint64                 `protobuf:"varint,15,opt,name=respawn_tick,json=respawnTick,proto3" json:"respawn_tick,omitempty"`
	// Host timing observation, never simulation input: the smallest movement
	// slack since the previous published snapshot and its command sequence.
	// Slack is the executing tick minus the command's first receipt, or minus
	// the receipt of a command that arrived after its sequence was substituted
	// (negative). Both or neither; |slack| <= 1,000,000 and
	// 1 <= sequence <= last_resolved_command. Only the Client's phase tracking
	// reads it.
	MovementSlackSequence *uint64 `protobuf:"varint,17,opt,name=movement_slack_sequence,json=movementSlackSequence,proto3,oneof" json:"movement_slack_sequence,omitempty"`
	MovementSlackUs       *int32  `protobuf:"zigzag32,18,opt,name=movement_slack_us,json=movementSlackUs,proto3,oneof" json:"movement_slack_us,omitempty"`
	// Consecutive failed 10-second connection-quality windows (0-2). At 3 the
	// Match evicts the player; the HUD warns while this is non-zero.
	ConnectionQualityFailures uint32 `protobuf:"varint,19,opt,name=connection_quality_failures,json=connectionQualityFailures,proto3" json:"connection_quality_failures,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_runtime_v6_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v6_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerState) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerState) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerState) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *PlayerState) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *PlayerState) GetLastResolvedCommand() uint64 {
	if x != nil {
		return x.LastResolvedCommand
	}
	return 0
}

func (x *PlayerState) GetMovementEpoch() uint64 {
	if x != nil {
		return x.MovementEpoch
	}
	return 0
}

func (x *PlayerState) GetContiguousPendingCommands() uint32 {
	if x != nil {
		return x.ContiguousPendingCommands
	}
	return 0
}

func (x *PlayerState) GetVerticalVelocity() float32 {
	if x != nil {
		return x.VerticalVelocity
	}
	return 0
}

func (x *PlayerState) GetGrounded() bool {
	if x != nil {
		return x.Grounded
	}
	return false
}

func (x *PlayerState) GetLifeGeneration() uint64 {
	if x != nil {
		return x.LifeGeneration
	}
	return 0
}

func (x *PlayerState) GetLifeState() LifeState {
	if x != nil {
		return x.LifeState
	}
	return LifeState_LIFE_UNSPECIFIED
}

func (x *PlayerState) GetLifeStateTick() uint64 {
	if x != nil {
		return x.LifeStateTick
	}
	return 0
}

func (x *PlayerState) GetRespawnTick() uint64 {
	if x != nil {
		return x.RespawnTick
	}
	return 0
}

func (x *PlayerState) GetMovementSlackSequence() uint64 {
	if x != nil && x.MovementSlackSequence != nil {
		return *x.MovementSlackSequence
	}
	return 0
}

func (x *PlayerState) GetMovementSlackUs() int32 {
	if x != nil && x.MovementSlackUs != nil {
		return *x.MovementSlackUs
	}
	return 0
}

func (x *PlayerState) GetConnectionQualityFailures() uint32 {
	if x != nil {
		return x.ConnectionQualityFailures
	}
	return 0
}

type WorldSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Players       []*PlayerState         `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Combat        []*CombatState         `protobuf:"bytes,3,rep,name=combat,proto3" json:"combat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldSnapshot) Reset() {
	*x = WorldSnapshot{}
	mi := &file_runtime_v6_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldSnapshot) ProtoMessage() {}

func (x *WorldSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v6_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldSnapshot.ProtoReflect.Descriptor instead.
func (*WorldSnapshot) Descriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{7}
}

func (x *WorldSnapshot) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *WorldSnapshot) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *WorldSnapshot) GetCombat() []*CombatState {
	if x != nil {
		return x.Combat
	}
	return nil
}

type PlayerEvicted struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlayerId            uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Reason              EvictionReason         `protobuf:"varint,2,opt,name=reason,proto3,enum=object_fps_pvp.runtime.v6.EvictionReason" json:"reason,omitempty"`
	ReferenceAgeMs      uint32                 `protobuf:"varint,3,opt,name=reference_age_ms,json=referenceAgeMs,proto3" json:"reference_age_ms,omitempty"`
	SubstitutedPermille uint32                 `protobuf:"varint,4,opt,name=substituted_permille,json=substitutedPermille,proto3" json:"substituted_permille,omitempty"`
	MovementResets      uint32                 `protobuf:"varint,5,opt,name=movement_resets,json=movementResets,proto3" json:"movement_resets,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PlayerEvicted) Reset() {
	*x = PlayerEvicted{}
	mi := &file_runtime_v6_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEvicted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEvicted) ProtoMessage() {}

func (x *PlayerEvicted) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v6_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEvicted.ProtoReflect.Descriptor instead.
func (*PlayerEvicted) Descriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerEvicted) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerEvicted) GetReason() EvictionReason {
	if x != nil {
		return x.Reason
	}
	return EvictionReason_EVICTION_UNSPECIFIED
}

func (x *PlayerEvicted) GetReferenceAgeMs() uint32 {
	if x != nil {
		return x.ReferenceAgeMs
	}
	return 0
}

func (x *PlayerEvicted) GetSubstitutedPermille() uint32 {
	if x != nil {
		return x.SubstitutedPermille
	}
	return 0
}

func (x *PlayerEvicted) GetMovementResets() uint32 {
	if x != nil {
		return x.MovementResets
	}
	return 0
}

type RuntimeError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeError) Reset() {
	*x = RuntimeError{}
	mi := &file_runtime_v6_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeError) ProtoMessage() {}

func (x *RuntimeError) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v6_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeError.ProtoReflect.Descriptor instead.
func (*RuntimeError) Descriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{9}
}

func (x *RuntimeError) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *RuntimeError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RuntimeError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RuntimeEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*RuntimeEnvelope_Ready
	//	*RuntimeEnvelope_Join
	//	*RuntimeEnvelope_Leave
	//	*RuntimeEnvelope_Input
	//	*RuntimeEnvelope_JoinResult
	//	*RuntimeEnvelope_Error
	//	*RuntimeEnvelope_Snapshot
	//	*RuntimeEnvelope_Actions
	//	*RuntimeEnvelope_ActionResults
	//	*RuntimeEnvelope_Evicted
	Message       isRuntimeEnvelope_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeEnvelope) Reset() {
	*x = RuntimeEnvelope{}
	mi := &file_runtime_v6_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEnvelope) ProtoMessage() {}

func (x *RuntimeEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v6_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEnvelope.ProtoReflect.Descriptor instead.
func (*RuntimeEnvelope) Descriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{10}
}

func (x *RuntimeEnvelope) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *RuntimeEnvelope) GetMessage() isRuntimeEnvelope_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RuntimeEnvelope) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetJoin() *PlayerJoin {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetLeave() *PlayerLeave {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Leave); ok {
			return x.Leave
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetInput() *PlayerInput {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetJoinResult() *JoinResult {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_JoinResult); ok {
			return x.JoinResult
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetError() *RuntimeError {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetSnapshot() *WorldSnapshot {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetActions() *ActionBatch {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Actions); ok {
			return x.Actions
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetActionResults() *ActionResults {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_ActionResults); ok {
			return x.ActionResults
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetEvicted() *PlayerEvicted {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Evicted); ok {
			return x.Evicted
		}
	}
	return nil
}

type isRuntimeEnvelope_Message interface {
	isRuntimeEnvelope_Message()
}

type RuntimeEnvelope_Ready struct {
	Ready *Ready `protobuf:"bytes,10,opt,name=ready,proto3,oneof"`
}

type RuntimeEnvelope_Join struct {
	Join *PlayerJoin `protobuf:"bytes,11,opt,name=join,proto3,oneof"`
}

type RuntimeEnvelope_Leave struct {
	Leave *PlayerLeave `protobuf:"bytes,12,opt,name=leave,proto3,oneof"`
}

type RuntimeEnvelope_Input struct {
	Input *PlayerInput `protobuf:"bytes,13,opt,name=input,proto3,oneof"`
}

type RuntimeEnvelope_JoinResult struct {
	JoinResult *JoinResult `protobuf:"bytes,14,opt,name=join_result,json=joinResult,proto3,oneof"`
}

type RuntimeEnvelope_Error struct {
	Error *RuntimeError `protobuf:"bytes,15,opt,name=error,proto3,oneof"`
}

type RuntimeEnvelope_Snapshot struct {
	Snapshot *WorldSnapshot `protobuf:"bytes,16,opt,name=snapshot,proto3,oneof"`
}

type RuntimeEnvelope_Actions struct {
	Actions *ActionBatch `protobuf:"bytes,17,opt,name=actions,proto3,oneof"`
}

type RuntimeEnvelope_ActionResults struct {
	ActionResults *ActionResults `protobuf:"bytes,18,opt,name=action_results,json=actionResults,proto3,oneof"`
}

type RuntimeEnvelope_Evicted struct {
	Evicted *PlayerEvicted `protobuf:"bytes,19,opt,name=evicted,proto3,oneof"`
}

func (*RuntimeEnvelope_Ready) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Join) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Leave) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Input) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_JoinResult) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Error) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Snapshot) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Actions) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_ActionResults) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Evicted) isRuntimeEnvelope_Message() {}

type ActionBatch struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlayerId            uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Shots               []*ShotRequest         `protobuf:"bytes,2,rep,name=shots,proto3" json:"shots,omitempty"`
	AcknowledgedThrough uint64                 `protobuf:"varint,3,opt,name=acknowledged_through,json=acknowledgedThrough,proto3" json:"acknowledged_through,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ActionBatch) Reset() {
	*x = ActionBatch{}
	mi := &file_runtime_v6_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionBatch) ProtoMessage() {}

func (x *ActionBatch) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v6_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionBatch.ProtoReflect.Descriptor instead.
func (*ActionBatch) Descriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{11}
}

func (x *ActionBatch) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ActionBatch) GetShots() []*ShotRequest {
	if x != nil {
		return x.Shots
	}
	return nil
}

func (x *ActionBatch) GetAcknowledgedThrough() uint64 {
	if x != nil {
		return x.AcknowledgedThrough
	}
	return 0
}

type ActionResults struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	RetiredThrough uint64                 `protobuf:"varint,2,opt,name=retired_through,json=retiredThrough,proto3" json:"retired_through,omitempty"`
	Decisions      []*ShotDecision        `protobuf:"bytes,3,rep,name=decisions,proto3" json:"decisions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActionResults) Reset() {
	*x = ActionResults{}
	mi := &file_runtime_v6_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResults) ProtoMessage() {}

func (x *ActionResults) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v6_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResults.ProtoReflect.Descriptor instead.
func (*ActionResults) Descriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{12}
}

func (x *ActionResults) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ActionResults) GetRetiredThrough() uint64 {
	if x != nil {
		return x.RetiredThrough
	}
	return 0
}

func (x *ActionResults) GetDecisions() []*ShotDecision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

type CombatRules struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MaximumHp             uint32                 `protobuf:"varint,1,opt,name=maximum_hp,json=maximumHp,proto3" json:"maximum_hp,omitempty"`
	ShotDamage            uint32                 `protobuf:"varint,2,opt,name=shot_damage,json=shotDamage,proto3" json:"shot_damage,omitempty"`
	CooldownTicks         uint64                 `protobuf:"varint,3,opt,name=cooldown_ticks,json=cooldownTicks,proto3" json:"cooldown_ticks,omitempty"`
	ShotRange             float32                `protobuf:"fixed32,4,opt,name=shot_range,json=shotRange,proto3" json:"shot_range,omitempty"`
	MaximumReferenceAgeMs uint32                 `protobuf:"varint,5,opt,name=maximum_reference_age_ms,json=maximumReferenceAgeMs,proto3" json:"maximum_reference_age_ms,omitempty"`
	MagazineCapacity      uint32                 `protobuf:"varint,6,opt,name=magazine_capacity,json=magazineCapacity,proto3" json:"magazine_capacity,omitempty"`
	ReloadTicks           uint64                 `protobuf:"varint,7,opt,name=reload_ticks,json=reloadTicks,proto3" json:"reload_ticks,omitempty"`
	RespawnTicks          uint64                 `protobuf:"varint,8,opt,name=respawn_ticks,json=respawnTicks,proto3" json:"respawn_ticks,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CombatRules) Reset() {
	*x = CombatRules{}
	mi := &file_runtime_v6_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatRules) ProtoMessage() {}

func (x *CombatRules) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v6_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatRules.ProtoReflect.Descriptor instead.
func (*CombatRules) Descriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{13}
}

func (x *CombatRules) GetMaximumHp() uint32 {
	if x != nil {
		return x.MaximumHp
	}
	return 0
}

func (x *CombatRules) GetShotDamage() uint32 {
	if x != nil {
		return x.ShotDamage
	}
	return 0
}

func (x *CombatRules) GetCooldownTicks() uint64 {
	if x != nil {
		return x.CooldownTicks
	}
	return 0
}

func (x *CombatRules) GetShotRange() float32 {
	if x != nil {
		return x.ShotRange
	}
	return 0
}

func (x *CombatRules) GetMaximumReferenceAgeMs() uint32 {
	if x != nil {
		return x.MaximumReferenceAgeMs
	}
	return 0
}

func (x *CombatRules) GetMagazineCapacity() uint32 {
	if x != nil {
		return x.MagazineCapacity
	}
	return 0
}

func (x *CombatRules) GetReloadTicks() uint64 {
	if x != nil {
		return x.ReloadTicks
	}
	return 0
}

func (x *CombatRules) GetRespawnTicks() uint64 {
	if x != nil {
		return x.RespawnTicks
	}
	return 0
}

type CombatState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlayerId            uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Hp                  uint32                 `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`
	NextAllowedShotTick uint64                 `protobuf:"varint,3,opt,name=next_allowed_shot_tick,json=nextAllowedShotTick,proto3" json:"next_allowed_shot_tick,omitempty"`
	LifeGeneration      uint64                 `protobuf:"varint,4,opt,name=life_generation,json=lifeGeneration,proto3" json:"life_generation,omitempty"`
	MagazineAmmo        uint32                 `protobuf:"varint,5,opt,name=magazine_ammo,json=magazineAmmo,proto3" json:"magazine_ammo,omitempty"`
	ReloadActionId      uint64                 `protobuf:"varint,6,opt,name=reload_action_id,json=reloadActionId,proto3" json:"reload_action_id,omitempty"`
	ReloadStartTick     uint64                 `protobuf:"varint,7,opt,name=reload_start_tick,json=reloadStartTick,proto3" json:"reload_start_tick,omitempty"`
	ReloadEndTick       uint64                 `protobuf:"varint,8,opt,name=reload_end_tick,json=reloadEndTick,proto3" json:"reload_end_tick,omitempty"`
	LastShotActionId    uint64                 `protobuf:"varint,9,opt,name=last_shot_action_id,json=lastShotActionId,proto3" json:"last_shot_action_id,omitempty"`
	LastShotTick        uint64                 `protobuf:"varint,10,opt,name=last_shot_tick,json=lastShotTick,proto3" json:"last_shot_tick,omitempty"`
	// Presentation-only hit record of the current life (pv6 contract §2): all
	// three are zero before the first hit and reset on respawn.
	LastDamageTick uint64 `protobuf:"varint,11,opt,name=last_damage_tick,json=lastDamageTick,proto3" json:"last_damage_tick,omitempty"`
	DamageCount    uint32 `protobuf:"varint,12,opt,name=damage_count,json=damageCount,proto3" json:"damage_count,omitempty"`
	LastAttackerId uint64 `protobuf:"varint,13,opt,name=last_attacker_id,json=lastAttackerId,proto3" json:"last_attacker_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CombatState) Reset() {
	*x = CombatState{}
	mi := &file_runtime_v6_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatState) ProtoMessage() {}

func (x *CombatState) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v6_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatState.ProtoReflect.Descriptor instead.
func (*CombatState) Descriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{14}
}

func (x *CombatState) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *CombatState) GetHp() uint32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *CombatState) GetNextAllowedShotTick() uint64 {
	if x != nil {
		return x.NextAllowedShotTick
	}
	return 0
}

func (x *CombatState) GetLifeGeneration() uint64 {
	if x != nil {
		return x.LifeGeneration
	}
	return 0
}

func (x *CombatState) GetMagazineAmmo() uint32 {
	if x != nil {
		return x.MagazineAmmo
	}
	return 0
}

func (x *CombatState) GetReloadActionId() uint64 {
	if x != nil {
		return x.ReloadActionId
	}
	return 0
}

func (x *CombatState) GetReloadStartTick() uint64 {
	if x != nil {
		return x.ReloadStartTick
	}
	return 0
}

func (x *CombatState) GetReloadEndTick() uint64 {
	if x != nil {
		return x.ReloadEndTick
	}
	return 0
}

func (x *CombatState) GetLastShotActionId() uint64 {
	if x != nil {
		return x.LastShotActionId
	}
	return 0
}

func (x *CombatState) GetLastShotTick() uint64 {
	if x != nil {
		return x.LastShotTick
	}
	return 0
}

func (x *CombatState) GetLastDamageTick() uint64 {
	if x != nil {
		return x.LastDamageTick
	}
	return 0
}

func (x *CombatState) GetDamageCount() uint32 {
	if x != nil {
		return x.DamageCount
	}
	return 0
}

func (x *CombatState) GetLastAttackerId() uint64 {
	if x != nil {
		return x.LastAttackerId
	}
	return 0
}

type ShotRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ActionId              uint64                 `protobuf:"varint,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	ObservedAuthorityTick uint64                 `protobuf:"varint,2,opt,name=observed_authority_tick,json=observedAuthorityTick,proto3" json:"observed_authority_tick,omitempty"`
	Yaw                   *float32               `protobuf:"fixed32,3,opt,name=yaw,proto3,oneof" json:"yaw,omitempty"`
	Pitch                 *float32               `protobuf:"fixed32,4,opt,name=pitch,proto3,oneof" json:"pitch,omitempty"`
	Kind                  ActionKind             `protobuf:"varint,5,opt,name=kind,proto3,enum=object_fps_pvp.runtime.v6.ActionKind" json:"kind,omitempty"`
	LifeGeneration        uint64                 `protobuf:"varint,6,opt,name=life_generation,json=lifeGeneration,proto3" json:"life_generation,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ShotRequest) Reset() {
	*x = ShotRequest{}
	mi := &file_runtime_v6_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShotRequest) ProtoMessage() {}

func (x *ShotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v6_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShotRequest.ProtoReflect.Descriptor instead.
func (*ShotRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{15}
}

func (x *ShotRequest) GetActionId() uint64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *ShotRequest) GetObservedAuthorityTick() uint64 {
	if x != nil {
		return x.ObservedAuthorityTick
	}
	return 0
}

func (x *ShotRequest) GetYaw() float32 {
	if x != nil && x.Yaw != nil {
		return *x.Yaw
	}
	return 0
}

func (x *ShotRequest) GetPitch() float32 {
	if x != nil && x.Pitch != nil {
		return *x.Pitch
	}
	return 0
}

func (x *ShotRequest) GetKind() ActionKind {
	if x != nil {
		return x.Kind
	}
	return ActionKind_ACTION_UNSPECIFIED
}

func (x *ShotRequest) GetLifeGeneration() uint64 {
	if x != nil {
		return x.LifeGeneration
	}
	return 0
}

type ShotDecision struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ActionId             uint64                 `protobuf:"varint,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	ResolvedTick         uint64                 `protobuf:"varint,2,opt,name=resolved_tick,json=resolvedTick,proto3" json:"resolved_tick,omitempty"`
	Accepted             bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejection            ShotRejection          `protobuf:"varint,4,opt,name=rejection,proto3,enum=object_fps_pvp.runtime.v6.ShotRejection" json:"rejection,omitempty"`
	HitKind              ShotHitKind            `protobuf:"varint,5,opt,name=hit_kind,json=hitKind,proto3,enum=object_fps_pvp.runtime.v6.ShotHitKind" json:"hit_kind,omitempty"`
	TargetId             uint64                 `protobuf:"varint,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Damage               uint32                 `protobuf:"varint,7,opt,name=damage,proto3" json:"damage,omitempty"`
	Kind                 ActionKind             `protobuf:"varint,8,opt,name=kind,proto3,enum=object_fps_pvp.runtime.v6.ActionKind" json:"kind,omitempty"`
	LifeGeneration       uint64                 `protobuf:"varint,9,opt,name=life_generation,json=lifeGeneration,proto3" json:"life_generation,omitempty"`
	TargetLifeGeneration uint64                 `protobuf:"varint,10,opt,name=target_life_generation,json=targetLifeGeneration,proto3" json:"target_life_generation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ShotDecision) Reset() {
	*x = ShotDecision{}
	mi := &file_runtime_v6_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShotDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShotDecision) ProtoMessage() {}

func (x *ShotDecision) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v6_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShotDecision.ProtoReflect.Descriptor instead.
func (*ShotDecision) Descriptor() ([]byte, []int) {
	return file_runtime_v6_proto_rawDescGZIP(), []int{16}
}

func (x *ShotDecision) GetActionId() uint64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *ShotDecision) GetResolvedTick() uint64 {
	if x != nil {
		return x.ResolvedTick
	}
	return 0
}

func (x *ShotDecision) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ShotDecision) GetRejection() ShotRejection {
	if x != nil {
		return x.Rejection
	}
	return ShotRejection_REJECTION_NONE
}

func (x *ShotDecision) GetHitKind() ShotHitKind {
	if x != nil {
		return x.HitKind
	}
	return ShotHitKind_HIT_MISS
}

func (x *ShotDecision) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ShotDecision) GetDamage() uint32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *ShotDecision) GetKind() ActionKind {
	if x != nil {
		return x.Kind
	}
	return ActionKind_ACTION_UNSPECIFIED
}

func (x *ShotDecision) GetLifeGeneration() uint64 {
	if x != nil {
		return x.LifeGeneration
	}
	return 0
}

func (x *ShotDecision) GetTargetLifeGeneration() uint64 {
	if x != nil {
		return x.TargetLifeGeneration
	}
	return 0
}

var File_runtime_v6_proto protoreflect.FileDescriptor

const file_runtime_v6_proto_rawDesc = "" +
	"\n" +
	"\x10runtime_v6.proto\x12\x19object_fps_pvp.runtime.v6\"\xe6\x02\n" +
	"\x05Ready\x12\x19\n" +
	"\barena_id\x18\x01 \x01(\tR\aarenaId\x12#\n" +
	"\rarena_version\x18\x02 \x01(\rR\farenaVersion\x12\x1b\n" +
	"\ttick_rate\x18\x03 \x01(\rR\btickRate\x126\n" +
	"\x17snapshot_interval_ticks\x18\x04 \x01(\rR\x15snapshotIntervalTicks\x12\x1f\n" +
	"\vmax_players\x18\x05 \x01(\rR\n" +
	"maxPlayers\x12I\n" +
	"\fcombat_rules\x18\x06 \x01(\v2&.object_fps_pvp.runtime.v6.CombatRulesR\vcombatRules\x12\x1f\n" +
	"\vjump_height\x18\a \x01(\x02R\n" +
	"jumpHeight\x12\x18\n" +
	"\agravity\x18\b \x01(\x02R\agravity\x12!\n" +
	"\farena_digest\x18\t \x01(\x06R\varenaDigest\")\n" +
	"\n" +
	"PlayerJoin\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\"*\n" +
	"\vPlayerLeave\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\"\xbe\x01\n" +
	"\x0fMovementCommand\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12!\n" +
	"\fmove_forward\x18\x02 \x01(\x02R\vmoveForward\x12\x1d\n" +
	"\n" +
	"move_right\x18\x03 \x01(\x02R\tmoveRight\x12\x10\n" +
	"\x03yaw\x18\x04 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x05 \x01(\x02R\x05pitch\x12%\n" +
	"\x0ejump_requested\x18\x06 \x01(\bR\rjumpRequested\"\xfa\x01\n" +
	"\vPlayerInput\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12F\n" +
	"\bcommands\x18\x02 \x03(\v2*.object_fps_pvp.runtime.v6.MovementCommandR\bcommands\x12%\n" +
	"\x0emovement_epoch\x18\x03 \x01(\x04R\rmovementEpoch\x12'\n" +
	"\x0flife_generation\x18\x04 \x01(\x04R\x0elifeGeneration\x126\n" +
	"\x17observed_authority_tick\x18\x05 \x01(\x04R\x15observedAuthorityTick\"]\n" +
	"\n" +
	"JoinResult\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x94\x06\n" +
	"\vPlayerState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x02R\x01z\x12\x10\n" +
	"\x03yaw\x18\x05 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x06 \x01(\x02R\x05pitch\x122\n" +
	"\x15last_resolved_command\x18\a \x01(\x04R\x13lastResolvedCommand\x12%\n" +
	"\x0emovement_epoch\x18\b \x01(\x04R\rmovementEpoch\x12>\n" +
	"\x1bcontiguous_pending_commands\x18\t \x01(\rR\x19contiguousPendingCommands\x12+\n" +
	"\x11vertical_velocity\x18\n" +
	" \x01(\x02R\x10verticalVelocity\x12\x1a\n" +
	"\bgrounded\x18\v \x01(\bR\bgrounded\x12'\n" +
	"\x0flife_generation\x18\f \x01(\x04R\x0elifeGeneration\x12C\n" +
	"\n" +
	"life_state\x18\r \x01(\x0e2$.object_fps_pvp.runtime.v6.LifeStateR\tlifeState\x12&\n" +
	"\x0flife_state_tick\x18\x0e \x01(\x04R\rlifeStateTick\x12!\n" +
	"\frespawn_tick\x18\x0f \x01(\x04R\vrespawnTick\x12;\n" +
	"\x17movement_slack_sequence\x18\x11 \x01(\x04H\x00R\x15movementSlackSequence\x88\x01\x01\x12/\n" +
	"\x11movement_slack_us\x18\x12 \x01(\x11H\x01R\x0fmovementSlackUs\x88\x01\x01\x12>\n" +
	"\x1bconnection_quality_failures\x18\x13 \x01(\rR\x19connectionQualityFailuresB\x1a\n" +
	"\x18_movement_slack_sequenceB\x14\n" +
	"\x12_movement_slack_usJ\x04\b\x10\x10\x11R\x13epoch_start_wait_us\"\xa5\x01\n" +
	"\rWorldSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12@\n" +
	"\aplayers\x18\x02 \x03(\v2&.object_fps_pvp.runtime.v6.PlayerStateR\aplayers\x12>\n" +
	"\x06combat\x18\x03 \x03(\v2&.object_fps_pvp.runtime.v6.CombatStateR\x06combat\"\xf5\x01\n" +
	"\rPlayerEvicted\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12A\n" +
	"\x06reason\x18\x02 \x01(\x0e2).object_fps_pvp.runtime.v6.EvictionReasonR\x06reason\x12(\n" +
	"\x10reference_age_ms\x18\x03 \x01(\rR\x0ereferenceAgeMs\x121\n" +
	"\x14substituted_permille\x18\x04 \x01(\rR\x13substitutedPermille\x12'\n" +
	"\x0fmovement_resets\x18\x05 \x01(\rR\x0emovementResets\"Y\n" +
	"\fRuntimeError\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xee\x05\n" +
	"\x0fRuntimeEnvelope\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x128\n" +
	"\x05ready\x18\n" +
	" \x01(\v2 .object_fps_pvp.runtime.v6.ReadyH\x00R\x05ready\x12;\n" +
	"\x04join\x18\v \x01(\v2%.object_fps_pvp.runtime.v6.PlayerJoinH\x00R\x04join\x12>\n" +
	"\x05leave\x18\f \x01(\v2&.object_fps_pvp.runtime.v6.PlayerLeaveH\x00R\x05leave\x12>\n" +
	"\x05input\x18\r \x01(\v2&.object_fps_pvp.runtime.v6.PlayerInputH\x00R\x05input\x12H\n" +
	"\vjoin_result\x18\x0e \x01(\v2%.object_fps_pvp.runtime.v6.JoinResultH\x00R\n" +
	"joinResult\x12?\n" +
	"\x05error\x18\x0f \x01(\v2'.object_fps_pvp.runtime.v6.RuntimeErrorH\x00R\x05error\x12F\n" +
	"\bsnapshot\x18\x10 \x01(\v2(.object_fps_pvp.runtime.v6.WorldSnapshotH\x00R\bsnapshot\x12B\n" +
	"\aactions\x18\x11 \x01(\v2&.object_fps_pvp.runtime.v6.ActionBatchH\x00R\aactions\x12Q\n" +
	"\x0eaction_results\x18\x12 \x01(\v2(.object_fps_pvp.runtime.v6.ActionResultsH\x00R\ractionResults\x12D\n" +
	"\aevicted\x18\x13 \x01(\v2(.object_fps_pvp.runtime.v6.PlayerEvictedH\x00R\aevictedB\t\n" +
	"\amessage\"\x9b\x01\n" +
	"\vActionBatch\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12<\n" +
	"\x05shots\x18\x02 \x03(\v2&.object_fps_pvp.runtime.v6.ShotRequestR\x05shots\x121\n" +
	"\x14acknowledged_through\x18\x03 \x01(\x04R\x13acknowledgedThrough\"\x9c\x01\n" +
	"\rActionResults\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12'\n" +
	"\x0fretired_through\x18\x02 \x01(\x04R\x0eretiredThrough\x12E\n" +
	"\tdecisions\x18\x03 \x03(\v2'.object_fps_pvp.runtime.v6.ShotDecisionR\tdecisions\"\xc1\x02\n" +
	"\vCombatRules\x12\x1d\n" +
	"\n" +
	"maximum_hp\x18\x01 \x01(\rR\tmaximumHp\x12\x1f\n" +
	"\vshot_damage\x18\x02 \x01(\rR\n" +
	"shotDamage\x12%\n" +
	"\x0ecooldown_ticks\x18\x03 \x01(\x04R\rcooldownTicks\x12\x1d\n" +
	"\n" +
	"shot_range\x18\x04 \x01(\x02R\tshotRange\x127\n" +
	"\x18maximum_reference_age_ms\x18\x05 \x01(\rR\x15maximumReferenceAgeMs\x12+\n" +
	"\x11magazine_capacity\x18\x06 \x01(\rR\x10magazineCapacity\x12!\n" +
	"\freload_ticks\x18\a \x01(\x04R\vreloadTicks\x12#\n" +
	"\rrespawn_ticks\x18\b \x01(\x04R\frespawnTicks\"\x87\x04\n" +
	"\vCombatState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x0e\n" +
	"\x02hp\x18\x02 \x01(\rR\x02hp\x123\n" +
	"\x16next_allowed_shot_tick\x18\x03 \x01(\x04R\x13nextAllowedShotTick\x12'\n" +
	"\x0flife_generation\x18\x04 \x01(\x04R\x0elifeGeneration\x12#\n" +
	"\rmagazine_ammo\x18\x05 \x01(\rR\fmagazineAmmo\x12(\n" +
	"\x10reload_action_id\x18\x06 \x01(\x04R\x0ereloadActionId\x12*\n" +
	"\x11reload_start_tick\x18\a \x01(\x04R\x0freloadStartTick\x12&\n" +
	"\x0freload_end_tick\x18\b \x01(\x04R\rreloadEndTick\x12-\n" +
	"\x13last_shot_action_id\x18\t \x01(\x04R\x10lastShotActionId\x12$\n" +
	"\x0elast_shot_tick\x18\n" +
	" \x01(\x04R\flastShotTick\x12(\n" +
	"\x10last_damage_tick\x18\v \x01(\x04R\x0elastDamageTick\x12!\n" +
	"\fdamage_count\x18\f \x01(\rR\vdamageCount\x12(\n" +
	"\x10last_attacker_id\x18\r \x01(\x04R\x0elastAttackerId\"\x8a\x02\n" +
	"\vShotRequest\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\x04R\bactionId\x126\n" +
	"\x17observed_authority_tick\x18\x02 \x01(\x04R\x15observedAuthorityTick\x12\x15\n" +
	"\x03yaw\x18\x03 \x01(\x02H\x00R\x03yaw\x88\x01\x01\x12\x19\n" +
	"\x05pitch\x18\x04 \x01(\x02H\x01R\x05pitch\x88\x01\x01\x129\n" +
	"\x04kind\x18\x05 \x01(\x0e2%.object_fps_pvp.runtime.v6.ActionKindR\x04kind\x12'\n" +
	"\x0flife_generation\x18\x06 \x01(\x04R\x0elifeGenerationB\x06\n" +
	"\x04_yawB\b\n" +
	"\x06_pitch\"\xc6\x03\n" +
	"\fShotDecision\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\x04R\bactionId\x12#\n" +
	"\rresolved_tick\x18\x02 \x01(\x04R\fresolvedTick\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\x12F\n" +
	"\trejection\x18\x04 \x01(\x0e2(.object_fps_pvp.runtime.v6.ShotRejectionR\trejection\x12A\n" +
	"\bhit_kind\x18\x05 \x01(\x0e2&.object_fps_pvp.runtime.v6.ShotHitKindR\ahitKind\x12\x1b\n" +
	"\ttarget_id\x18\x06 \x01(\x04R\btargetId\x12\x16\n" +
	"\x06damage\x18\a \x01(\rR\x06damage\x129\n" +
	"\x04kind\x18\b \x01(\x0e2%.object_fps_pvp.runtime.v6.ActionKindR\x04kind\x12'\n" +
	"\x0flife_generation\x18\t \x01(\x04R\x0elifeGeneration\x124\n" +
	"\x16target_life_generation\x18\n" +
	" \x01(\x04R\x14targetLifeGeneration*@\n" +
	"\tLifeState\x12\x14\n" +
	"\x10LIFE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"LIFE_ALIVE\x10\x01\x12\r\n" +
	"\tLIFE_DEAD\x10\x02*b\n" +
	"\x0eEvictionReason\x12\x18\n" +
	"\x14EVICTION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EVICTION_HIGH_LATENCY\x10\x01\x12\x1b\n" +
	"\x17EVICTION_UNSTABLE_INPUT\x10\x02*H\n" +
	"\n" +
	"ActionKind\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vACTION_SHOT\x10\x01\x12\x11\n" +
	"\rACTION_RELOAD\x10\x02*\x91\x02\n" +
	"\rShotRejection\x12\x12\n" +
	"\x0eREJECTION_NONE\x10\x00\x12\x1f\n" +
	"\x1bREJECTION_INVALID_REFERENCE\x10\x01\x12\x15\n" +
	"\x11REJECTION_EXPIRED\x10\x02\x12\x16\n" +
	"\x12REJECTION_COOLDOWN\x10\x03\x12\x18\n" +
	"\x14REJECTION_STALE_LIFE\x10\x04\x12\x1a\n" +
	"\x16REJECTION_INVALID_LIFE\x10\x05\x12\x12\n" +
	"\x0eREJECTION_DEAD\x10\x06\x12\x17\n" +
	"\x13REJECTION_RELOADING\x10\a\x12\x1c\n" +
	"\x18REJECTION_EMPTY_MAGAZINE\x10\b\x12\x1b\n" +
	"\x17REJECTION_MAGAZINE_FULL\x10\t*:\n" +
	"\vShotHitKind\x12\f\n" +
	"\bHIT_MISS\x10\x00\x12\r\n" +
	"\tHIT_WORLD\x10\x01\x12\x0e\n" +
	"\n" +
	"HIT_PLAYER\x10\x02B-Z+gyo.local/object_fps_pvp/protocol/runtimev6b\x06proto3"

var (
	file_runtime_v6_proto_rawDescOnce sync.Once
	file_runtime_v6_proto_rawDescData []byte
)

func file_runtime_v6_proto_rawDescGZIP() []byte {
	file_runtime_v6_proto_rawDescOnce.Do(func() {
		file_runtime_v6_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v6_proto_rawDesc), len(file_runtime_v6_proto_rawDesc)))
	})
	return file_runtime_v6_proto_rawDescData
}

var file_runtime_v6_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_runtime_v6_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_runtime_v6_proto_goTypes = []any{
	(LifeState)(0),          // 0: object_fps_pvp.runtime.v6.LifeState
	(EvictionReason)(0),     // 1: object_fps_pvp.runtime.v6.EvictionReason
	(ActionKind)(0),         // 2: object_fps_pvp.runtime.v6.ActionKind
	(ShotRejection)(0),      // 3: object_fps_pvp.runtime.v6.ShotRejection
	(ShotHitKind)(0),        // 4: object_fps_pvp.runtime.v6.ShotHitKind
	(*Ready)(nil),           // 5: object_fps_pvp.runtime.v6.Ready
	(*PlayerJoin)(nil),      // 6: object_fps_pvp.runtime.v6.PlayerJoin
	(*PlayerLeave)(nil),     // 7: object_fps_pvp.runtime.v6.PlayerLeave
	(*MovementCommand)(nil), // 8: object_fps_pvp.runtime.v6.MovementCommand
	(*PlayerInput)(nil),     // 9: object_fps_pvp.runtime.v6.PlayerInput
	(*JoinResult)(nil),      // 10: object_fps_pvp.runtime.v6.JoinResult
	(*PlayerState)(nil),     // 11: object_fps_pvp.runtime.v6.PlayerState
	(*WorldSnapshot)(nil),   // 12: object_fps_pvp.runtime.v6.WorldSnapshot
	(*PlayerEvicted)(nil),   // 13: object_fps_pvp.runtime.v6.PlayerEvicted
	(*RuntimeError)(nil),    // 14: object_fps_pvp.runtime.v6.RuntimeError
	(*RuntimeEnvelope)(nil), // 15: object_fps_pvp.runtime.v6.RuntimeEnvelope
	(*ActionBatch)(nil),     // 16: object_fps_pvp.runtime.v6.ActionBatch
	(*ActionResults)(nil),   // 17: object_fps_pvp.runtime.v6.ActionResults
	(*CombatRules)(nil),     // 18: object_fps_pvp.runtime.v6.CombatRules
	(*CombatState)(nil),     // 19: object_fps_pvp.runtime.v6.CombatState
	(*ShotRequest)(nil),     // 20: object_fps_pvp.runtime.v6.ShotRequest
	(*ShotDecision)(nil),    // 21: object_fps_pvp.runtime.v6.ShotDecision
}
var file_runtime_v6_proto_depIdxs = []int32{
	18, // 0: object_fps_pvp.runtime.v6.Ready.combat_rules:type_name -> object_fps_pvp.runtime.v6.CombatRules
	8,  // 1: object_fps_pvp.runtime.v6.PlayerInput.commands:type_name -> object_fps_pvp.runtime.v6.MovementCommand
	0,  // 2: object_fps_pvp.runtime.v6.PlayerState.life_state:type_name -> object_fps_pvp.runtime.v6.LifeState
	11, // 3: object_fps_pvp.runtime.v6.WorldSnapshot.players:type_name -> object_fps_pvp.runtime.v6.PlayerState
	19, // 4: object_fps_pvp.runtime.v6.WorldSnapshot.combat:type_name -> object_fps_pvp.runtime.v6.CombatState
	1,  // 5: object_fps_pvp.runtime.v6.PlayerEvicted.reason:type_name -> object_fps_pvp.runtime.v6.EvictionReason
	5,  // 6: object_fps_pvp.runtime.v6.RuntimeEnvelope.ready:type_name -> object_fps_pvp.runtime.v6.Ready
	6,  // 7: object_fps_pvp.runtime.v6.RuntimeEnvelope.join:type_name -> object_fps_pvp.runtime.v6.PlayerJoin
	7,  // 8: object_fps_pvp.runtime.v6.RuntimeEnvelope.leave:type_name -> object_fps_pvp.runtime.v6.PlayerLeave
	9,  // 9: object_fps_pvp.runtime.v6.RuntimeEnvelope.input:type_name -> object_fps_pvp.runtime.v6.PlayerInput
	10, // 10: object_fps_pvp.runtime.v6.RuntimeEnvelope.join_result:type_name -> object_fps_pvp.runtime.v6.JoinResult
	14, // 11: object_fps_pvp.runtime.v6.RuntimeEnvelope.error:type_name -> object_fps_pvp.runtime.v6.RuntimeError
	12, // 12: object_fps_pvp.runtime.v6.RuntimeEnvelope.snapshot:type_name -> object_fps_pvp.runtime.v6.WorldSnapshot
	16, // 13: object_fps_pvp.runtime.v6.RuntimeEnvelope.actions:type_name -> object_fps_pvp.runtime.v6.ActionBatch
	17, // 14: object_fps_pvp.runtime.v6.RuntimeEnvelope.action_results:type_name -> object_fps_pvp.runtime.v6.ActionResults
	13, // 15: object_fps_pvp.runtime.v6.RuntimeEnvelope.evicted:type_name -> object_fps_pvp.runtime.v6.PlayerEvicted
	20, // 16: object_fps_pvp.runtime.v6.ActionBatch.shots:type_name -> object_fps_pvp.runtime.v6.ShotRequest
	21, // 17: object_fps_pvp.runtime.v6.ActionResults.decisions:type_name -> object_fps_pvp.runtime.v6.ShotDecision
	2,  // 18: object_fps_pvp.runtime.v6.ShotRequest.kind:type_name -> object_fps_pvp.runtime.v6.ActionKind
	3,  // 19: object_fps_pvp.runtime.v6.ShotDecision.rejection:type_name -> object_fps_pvp.runtime.v6.ShotRejection
	4,  // 20: object_fps_pvp.runtime.v6.ShotDecision.hit_kind:type_name -> object_fps_pvp.runtime.v6.ShotHitKind
	2,  // 21: object_fps_pvp.runtime.v6.ShotDecision.kind:type_name -> object_fps_pvp.runtime.v6.ActionKind
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_runtime_v6_proto_init() }
func file_runtime_v6_proto_init() {
	if File_runtime_v6_proto != nil {
		return
	}
	file_runtime_v6_proto_msgTypes[6].OneofWrappers = []any{}
	file_runtime_v6_proto_msgTypes[10].OneofWrappers = []any{
		(*RuntimeEnvelope_Ready)(nil),
		(*RuntimeEnvelope_Join)(nil),
		(*RuntimeEnvelope_Leave)(nil),
		(*RuntimeEnvelope_Input)(nil),
		(*RuntimeEnvelope_JoinResult)(nil),
		(*RuntimeEnvelope_Error)(nil),
		(*RuntimeEnvelope_Snapshot)(nil),
		(*RuntimeEnvelope_Actions)(nil),
		(*RuntimeEnvelope_ActionResults)(nil),
		(*RuntimeEnvelope_Evicted)(nil),
	}
	file_runtime_v6_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v6_proto_rawDesc), len(file_runtime_v6_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_runtime_v6_proto_goTypes,
		DependencyIndexes: file_runtime_v6_proto_depIdxs,
		EnumInfos:         file_runtime_v6_proto_enumTypes,
		MessageInfos:      file_runtime_v6_proto_msgTypes,
	}.Build()
	File_runtime_v6_proto = out.File
	file_runtime_v6_proto_goTypes = nil
	file_runtime_v6_proto_depIdxs = nil
}
