cmake_minimum_required(VERSION 3.30)
foreach(required ROOT WORK TOOL GENERATOR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
set(source "${WORK}/source")
set(binary "${WORK}/build")
file(MAKE_DIRECTORY "${source}/shaders")
file(COPY "${ROOT}/engine/render/shaders/common" "${ROOT}/engine/render/shaders/builtin"
    DESTINATION "${source}/shaders")
file(WRITE "${source}/CMakeLists.txt" "cmake_minimum_required(VERSION 3.30)\nproject(ShaderBundleIntegration NONE)\ninclude(\"${ROOT}/build/cmake/GyoShaders.cmake\")\nset(bundle_output \"\${CMAKE_BINARY_DIR}/bundle\")\nif(REJECT_OUTPUT)\nset(bundle_output \"\${CMAKE_SOURCE_DIR}/forbidden\")\nendif()\ngyo_add_shader_bundle(integration_shaders SPEC \"\${CMAKE_SOURCE_DIR}/shaders/builtin/bundle.json\" OUTPUT_DIRECTORY \"\${bundle_output}\")\n")
set(generator_args -G "${GENERATOR}")
if(PLATFORM)
    list(APPEND generator_args -A "${PLATFORM}")
endif()
function(configure format)
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" ${generator_args}
        "-DGYO_SHADER_TOOL_EXECUTABLE=${TOOL}" "-DGYO_SHADER_FORMATS=${format}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Bundle configure failed: ${output}\n${error}")
    endif()
endfunction()
function(build)
    set(native_args)
    if(GENERATOR MATCHES "Visual Studio")
        set(native_args -- /nr:false)
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${binary}" --config Release
        --target integration_shaders --parallel 1 ${native_args}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Bundle build failed: ${output}\n${error}")
    endif()
endfunction()
configure(spirv)
build()
set(manifest "${binary}/bundle/manifest.json")
file(READ "${manifest}" first_manifest)
file(TIMESTAMP "${manifest}" first_time "%s")
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1)
build()
file(TIMESTAMP "${manifest}" unchanged_time "%s")
if(NOT first_time STREQUAL unchanged_time)
    message(FATAL_ERROR "An unchanged bundle was rebuilt")
endif()
file(APPEND "${source}/shaders/common/RasterAbi.hlsli" "\n// dependency regression\n")
build()
file(READ "${manifest}" changed_manifest)
string(JSON first_hash GET "${first_manifest}" toolchain source_hash)
string(JSON changed_hash GET "${changed_manifest}" toolchain source_hash)
if(first_hash STREQUAL changed_hash)
    message(FATAL_ERROR "Shared include change did not rebuild the shader bundle")
endif()
configure(dxil)
build()
file(READ "${manifest}" format_manifest)
string(JSON format GET "${format_manifest}" programs 0 variants 0 format)
if(NOT format STREQUAL "dxil")
    message(FATAL_ERROR "Format change did not rebuild the shader bundle")
endif()
function(expect_configure_rejected name expected_error)
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${WORK}/rejected-${name}" ${generator_args}
        "-DGYO_SHADER_TOOL_EXECUTABLE=${TOOL}" -DGYO_SHADER_FORMATS=spirv ${ARGN}
        RESULT_VARIABLE rejected OUTPUT_VARIABLE reject_output ERROR_VARIABLE reject_error)
    if(rejected EQUAL 0 OR NOT reject_error MATCHES "${expected_error}")
        message(FATAL_ERROR "Expected ${name} rejection: ${reject_output}\n${reject_error}")
    endif()
endfunction()
expect_configure_rejected(source_output "Shader bundle output must be in the build tree" -DREJECT_OUTPUT=ON)
expect_configure_rejected(missing_tool "GYO_SHADER_TOOL_EXECUTABLE does not exist"
    "-DGYO_SHADER_TOOL_EXECUTABLE=${WORK}/missing-tool")
expect_configure_rejected(invalid_format "Unknown shader format" -DGYO_SHADER_FORMATS=unsupported)
expect_configure_rejected(cross_host "Cross compiling requires GYO_SHADER_TOOL_EXECUTABLE"
    "-DCMAKE_SYSTEM_NAME=${CMAKE_HOST_SYSTEM_NAME}" -DGYO_SHADER_TOOL_EXECUTABLE=)
if(CMAKE_HOST_APPLE)
    expect_configure_rejected(missing_deployment "Metallib requires CMAKE_OSX_DEPLOYMENT_TARGET"
        -DGYO_SHADER_FORMATS=metallib -DCMAKE_OSX_DEPLOYMENT_TARGET=)
    expect_configure_rejected(missing_metal "Missing Apple metal compiler"
        -DGYO_SHADER_FORMATS=metallib -DCMAKE_OSX_DEPLOYMENT_TARGET=13.3
        "-DGYO_XCRUN_EXECUTABLE=${WORK}/missing-xcrun")
else()
    expect_configure_rejected(metal_host "Strict metallib builds require a native macOS host"
        -DGYO_SHADER_FORMATS=metallib)
endif()
message(STATUS "Shader CMake checks passed: incremental dependencies and unsupported/missing toolchain rejection")
