// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: client_v3.proto

package clientv3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This remote-client contract is independent of runtime_v3.proto.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_client_v3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_client_v3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_client_v3_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MatchId       uint64                 `protobuf:"varint,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	TickRate      uint32                 `protobuf:"varint,3,opt,name=tick_rate,json=tickRate,proto3" json:"tick_rate,omitempty"`
	SnapshotRate  uint32                 `protobuf:"varint,4,opt,name=snapshot_rate,json=snapshotRate,proto3" json:"snapshot_rate,omitempty"`
	ArenaId       string                 `protobuf:"bytes,5,opt,name=arena_id,json=arenaId,proto3" json:"arena_id,omitempty"`
	ArenaVersion  uint32                 `protobuf:"varint,6,opt,name=arena_version,json=arenaVersion,proto3" json:"arena_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_client_v3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_client_v3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_client_v3_proto_rawDescGZIP(), []int{1}
}

func (x *Welcome) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Welcome) GetMatchId() uint64 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

func (x *Welcome) GetTickRate() uint32 {
	if x != nil {
		return x.TickRate
	}
	return 0
}

func (x *Welcome) GetSnapshotRate() uint32 {
	if x != nil {
		return x.SnapshotRate
	}
	return 0
}

func (x *Welcome) GetArenaId() string {
	if x != nil {
		return x.ArenaId
	}
	return ""
}

func (x *Welcome) GetArenaVersion() uint32 {
	if x != nil {
		return x.ArenaVersion
	}
	return 0
}

// A single immutable 1/60-second movement step. No client time or position.
type MovementCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	MoveForward   float32                `protobuf:"fixed32,2,opt,name=move_forward,json=moveForward,proto3" json:"move_forward,omitempty"`
	MoveRight     float32                `protobuf:"fixed32,3,opt,name=move_right,json=moveRight,proto3" json:"move_right,omitempty"`
	Yaw           float32                `protobuf:"fixed32,4,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch         float32                `protobuf:"fixed32,5,opt,name=pitch,proto3" json:"pitch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovementCommand) Reset() {
	*x = MovementCommand{}
	mi := &file_client_v3_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovementCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovementCommand) ProtoMessage() {}

func (x *MovementCommand) ProtoReflect() protoreflect.Message {
	mi := &file_client_v3_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovementCommand.ProtoReflect.Descriptor instead.
func (*MovementCommand) Descriptor() ([]byte, []int) {
	return file_client_v3_proto_rawDescGZIP(), []int{2}
}

func (x *MovementCommand) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MovementCommand) GetMoveForward() float32 {
	if x != nil {
		return x.MoveForward
	}
	return 0
}

func (x *MovementCommand) GetMoveRight() float32 {
	if x != nil {
		return x.MoveRight
	}
	return 0
}

func (x *MovementCommand) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *MovementCommand) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

// Entire unacknowledged window, strictly ordered, at most 12 commands.
type PlayerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*MovementCommand     `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	MovementEpoch uint64                 `protobuf:"varint,2,opt,name=movement_epoch,json=movementEpoch,proto3" json:"movement_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_client_v3_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_client_v3_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_client_v3_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerInput) GetCommands() []*MovementCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *PlayerInput) GetMovementEpoch() uint64 {
	if x != nil {
		return x.MovementEpoch
	}
	return 0
}

type PlayerState struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	PlayerId                  uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X                         float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                         float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z                         float32                `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	Yaw                       float32                `protobuf:"fixed32,5,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch                     float32                `protobuf:"fixed32,6,opt,name=pitch,proto3" json:"pitch,omitempty"`
	LastResolvedCommand       uint64                 `protobuf:"varint,7,opt,name=last_resolved_command,json=lastResolvedCommand,proto3" json:"last_resolved_command,omitempty"`
	MovementEpoch             uint64                 `protobuf:"varint,8,opt,name=movement_epoch,json=movementEpoch,proto3" json:"movement_epoch,omitempty"`
	ContiguousPendingCommands uint32                 `protobuf:"varint,9,opt,name=contiguous_pending_commands,json=contiguousPendingCommands,proto3" json:"contiguous_pending_commands,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_client_v3_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_client_v3_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_client_v3_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerState) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerState) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerState) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *PlayerState) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *PlayerState) GetLastResolvedCommand() uint64 {
	if x != nil {
		return x.LastResolvedCommand
	}
	return 0
}

func (x *PlayerState) GetMovementEpoch() uint64 {
	if x != nil {
		return x.MovementEpoch
	}
	return 0
}

func (x *PlayerState) GetContiguousPendingCommands() uint32 {
	if x != nil {
		return x.ContiguousPendingCommands
	}
	return 0
}

type WorldSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Players       []*PlayerState         `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldSnapshot) Reset() {
	*x = WorldSnapshot{}
	mi := &file_client_v3_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldSnapshot) ProtoMessage() {}

func (x *WorldSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_client_v3_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldSnapshot.ProtoReflect.Descriptor instead.
func (*WorldSnapshot) Descriptor() ([]byte, []int) {
	return file_client_v3_proto_rawDescGZIP(), []int{5}
}

func (x *WorldSnapshot) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *WorldSnapshot) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_client_v3_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_client_v3_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_client_v3_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_client_v3_proto protoreflect.FileDescriptor

const file_client_v3_proto_rawDesc = "" +
	"\n" +
	"\x0fclient_v3.proto\x12\x18object_fps_pvp.client.v3\",\n" +
	"\x05Hello\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\"\xc3\x01\n" +
	"\aWelcome\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x19\n" +
	"\bmatch_id\x18\x02 \x01(\x04R\amatchId\x12\x1b\n" +
	"\ttick_rate\x18\x03 \x01(\rR\btickRate\x12#\n" +
	"\rsnapshot_rate\x18\x04 \x01(\rR\fsnapshotRate\x12\x19\n" +
	"\barena_id\x18\x05 \x01(\tR\aarenaId\x12#\n" +
	"\rarena_version\x18\x06 \x01(\rR\farenaVersion\"\x97\x01\n" +
	"\x0fMovementCommand\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12!\n" +
	"\fmove_forward\x18\x02 \x01(\x02R\vmoveForward\x12\x1d\n" +
	"\n" +
	"move_right\x18\x03 \x01(\x02R\tmoveRight\x12\x10\n" +
	"\x03yaw\x18\x04 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x05 \x01(\x02R\x05pitch\"{\n" +
	"\vPlayerInput\x12E\n" +
	"\bcommands\x18\x01 \x03(\v2).object_fps_pvp.client.v3.MovementCommandR\bcommands\x12%\n" +
	"\x0emovement_epoch\x18\x02 \x01(\x04R\rmovementEpoch\"\x97\x02\n" +
	"\vPlayerState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x02R\x01z\x12\x10\n" +
	"\x03yaw\x18\x05 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x06 \x01(\x02R\x05pitch\x122\n" +
	"\x15last_resolved_command\x18\a \x01(\x04R\x13lastResolvedCommand\x12%\n" +
	"\x0emovement_epoch\x18\b \x01(\x04R\rmovementEpoch\x12>\n" +
	"\x1bcontiguous_pending_commands\x18\t \x01(\rR\x19contiguousPendingCommands\"d\n" +
	"\rWorldSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12?\n" +
	"\aplayers\x18\x02 \x03(\v2%.object_fps_pvp.client.v3.PlayerStateR\aplayers\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB,Z*gyo.local/object_fps_pvp/protocol/clientv3b\x06proto3"

var (
	file_client_v3_proto_rawDescOnce sync.Once
	file_client_v3_proto_rawDescData []byte
)

func file_client_v3_proto_rawDescGZIP() []byte {
	file_client_v3_proto_rawDescOnce.Do(func() {
		file_client_v3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_v3_proto_rawDesc), len(file_client_v3_proto_rawDesc)))
	})
	return file_client_v3_proto_rawDescData
}

var file_client_v3_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_client_v3_proto_goTypes = []any{
	(*Hello)(nil),           // 0: object_fps_pvp.client.v3.Hello
	(*Welcome)(nil),         // 1: object_fps_pvp.client.v3.Welcome
	(*MovementCommand)(nil), // 2: object_fps_pvp.client.v3.MovementCommand
	(*PlayerInput)(nil),     // 3: object_fps_pvp.client.v3.PlayerInput
	(*PlayerState)(nil),     // 4: object_fps_pvp.client.v3.PlayerState
	(*WorldSnapshot)(nil),   // 5: object_fps_pvp.client.v3.WorldSnapshot
	(*Error)(nil),           // 6: object_fps_pvp.client.v3.Error
}
var file_client_v3_proto_depIdxs = []int32{
	2, // 0: object_fps_pvp.client.v3.PlayerInput.commands:type_name -> object_fps_pvp.client.v3.MovementCommand
	4, // 1: object_fps_pvp.client.v3.WorldSnapshot.players:type_name -> object_fps_pvp.client.v3.PlayerState
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_client_v3_proto_init() }
func file_client_v3_proto_init() {
	if File_client_v3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_v3_proto_rawDesc), len(file_client_v3_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_v3_proto_goTypes,
		DependencyIndexes: file_client_v3_proto_depIdxs,
		MessageInfos:      file_client_v3_proto_msgTypes,
	}.Build()
	File_client_v3_proto = out.File
	file_client_v3_proto_goTypes = nil
	file_client_v3_proto_depIdxs = nil
}
