add_subdirectory(collision)
add_subdirectory(core)
add_subdirectory(input)
add_subdirectory(model)
add_subdirectory(render)
add_subdirectory(render/sdl_gpu)
add_subdirectory(ui)
if(TARGET GYO::RenderBackendSDL)
    add_subdirectory(runtime_sdl)
endif()
add_subdirectory(cmake)
if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/ci/CMakeLists.txt")
    add_subdirectory(ci)
endif()
if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/assembly/CMakeLists.txt")
    add_subdirectory(assembly)
endif()
