include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/GyoComponents.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/GyoAppRegistry.cmake")

function(gyo_app_requirements)
    cmake_parse_arguments(PARSE_ARGV 0 APP "" "" "COMPONENTS")
    if(APP_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "Invalid gyo_app_requirements declaration: ${APP_UNPARSED_ARGUMENTS} ${APP_KEYWORDS_MISSING_VALUES}")
    endif()
    gyo_validate_components(${APP_COMPONENTS})
    set(_gyo_declared_components "${APP_COMPONENTS}" PARENT_SCOPE)
    set(_gyo_requirements_declared TRUE PARENT_SCOPE)
endfunction()

function(gyo_collect_requirements file output)
    set(GYO_APP_DISCOVERY ON)
    set(_gyo_requirements_declared FALSE)
    set(_gyo_declared_components "")
    include("${file}")
    if(NOT _gyo_requirements_declared)
        message(FATAL_ERROR "${file} must declare gyo_app_requirements() before its discovery guard")
    endif()
    set(${output} "${_gyo_declared_components}" PARENT_SCOPE)
endfunction()

function(gyo_configure_apps)
    foreach(legacy GYO_BUILD_RUNTIME GYO_BUILD_OBJECT_FPS GYO_BUILD_SANDBOX)
        if(DEFINED ${legacy})
            message(FATAL_ERROR "${legacy} was removed. Edit config/engine/projects.csv and use GYO_APPS=AUTO (or a selected subset). Remove the old cache entry with cmake -U ${legacy}, or configure a fresh build directory.")
        endif()
    endforeach()
    set(GYO_APPS AUTO CACHE STRING "AUTO selects enabled CSV apps for the target; an empty value selects none; otherwise a semicolon-separated subset")
    set(registry "${PROJECT_SOURCE_DIR}/config/engine/projects.csv")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${registry}")
    gyo_read_app_registry("${registry}" data)
    gyo_select_apps("${data}" "${CMAKE_SYSTEM_NAME}" "${GYO_APPS}" selected)
    gyo_validate_app_sources("${PROJECT_SOURCE_DIR}" ${selected})
    set(components "")
    foreach(app IN LISTS selected)
        gyo_collect_requirements("${PROJECT_SOURCE_DIR}/apps/${app}/CMakeLists.txt" requested)
        set_property(GLOBAL PROPERTY GYO_APP_${app}_COMPONENTS "${requested}")
        list(APPEND components ${requested})
    endforeach()
    if(GYO_BUILD_UI_EDITOR)
        gyo_collect_requirements("${PROJECT_SOURCE_DIR}/tools/editor/CMakeLists.txt" requested)
        list(APPEND components ${requested})
    endif()
    list(REMOVE_DUPLICATES components)
    set(GYO_ACTIVE_APPS "${selected}" PARENT_SCOPE)
    set(GYO_REQUESTED_COMPONENTS "${components}" PARENT_SCOPE)
    message(STATUS "GYO apps: target=${CMAKE_SYSTEM_NAME}, selected=[${selected}], components=[${components}]")
endfunction()
