include_guard(GLOBAL)

function(_gyo_app_literal value output)
    set(equals "=")
    string(FIND "${value}" "]${equals}]" closing)
    while(NOT closing EQUAL -1)
        string(APPEND equals "=")
        string(FIND "${value}" "]${equals}]" closing)
    endwhile()
    set(${output} "[${equals}[${value}]${equals}]" PARENT_SCOPE)
endfunction()

function(gyo_app_add_test)
    _gyo_require_app_context()
    cmake_parse_arguments(PARSE_ARGV 0 TEST "RUN_SERIAL" "NAME;TIMEOUT;WORKING_DIRECTORY"
        "COMMAND;LABELS;ENVIRONMENT")
    if(TEST_UNPARSED_ARGUMENTS OR TEST_KEYWORDS_MISSING_VALUES OR NOT TEST_COMMAND OR
       NOT TEST_NAME MATCHES "^[a-z][a-z0-9_.-]*$")
        message(FATAL_ERROR "gyo_app_add_test requires NAME and COMMAND")
    endif()
    set(name "${GYO_APP_ID}.${TEST_NAME}")
    get_property(names DIRECTORY PROPERTY GYO_APP_TEST_NAMES)
    if(name IN_LIST names)
        message(FATAL_ERROR "Duplicate app test ${name}")
    endif()
    set_property(DIRECTORY APPEND PROPERTY GYO_APP_TEST_NAMES "${name}")
    if(NOT BUILD_TESTING)
        return()
    endif()
    # Keep argv boundaries through this wrapper, including empty arguments and
    # literal semicolons. Bracket arguments do not evaluate user text as CMake.
    _gyo_app_literal("${name}" literal)
    set(invocation "add_test(NAME ${literal} COMMAND")
    foreach(argument IN LISTS TEST_COMMAND)
        _gyo_app_literal("${argument}" literal)
        string(APPEND invocation " ${literal}")
    endforeach()
    string(APPEND invocation ")")
    cmake_language(EVAL CODE "${invocation}")
    if(TEST_LABELS)
        set_tests_properties("${name}" PROPERTIES LABELS "${TEST_LABELS}")
    else()
        set_tests_properties("${name}" PROPERTIES LABELS cpu)
    endif()
    foreach(property TIMEOUT WORKING_DIRECTORY ENVIRONMENT)
        if(DEFINED TEST_${property})
            set_tests_properties("${name}" PROPERTIES ${property} "${TEST_${property}}")
        endif()
    endforeach()
    if(TEST_RUN_SERIAL)
        set_tests_properties("${name}" PROPERTIES RUN_SERIAL TRUE)
    endif()
endfunction()

