include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/GyoComponents.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/GyoRuntimeDeployment.cmake")

# This context belongs to one app directory, never to the engine or its cache.
function(gyo_app_project)
    cmake_parse_arguments(PARSE_ARGV 0 APP "" "ASSET_ROOT;DISPLAY_NAME" "")
    get_filename_component(directory_name "${CMAKE_CURRENT_SOURCE_DIR}" NAME)
    if(APP_UNPARSED_ARGUMENTS OR APP_KEYWORDS_MISSING_VALUES OR
       "${GYO_CURRENT_APP}" STREQUAL "" OR NOT directory_name STREQUAL GYO_CURRENT_APP)
        message(FATAL_ERROR "gyo_app_project() requires the CSV-selected app directory; configure from the repository root")
    endif()
    get_property(initialized DIRECTORY PROPERTY GYO_APP_CONTEXT SET)
    if(initialized)
        message(FATAL_ERROR "App ${GYO_CURRENT_APP} already has a project context")
    endif()
    set_property(DIRECTORY PROPERTY GYO_APP_CONTEXT "${GYO_CURRENT_APP}")
    set(id "${GYO_CURRENT_APP}")
    if(DEFINED APP_ASSET_ROOT)
        get_filename_component(asset_root "${APP_ASSET_ROOT}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    else()
        set(asset_root "${PROJECT_SOURCE_DIR}/assets/${id}")
    endif()
    if(DEFINED APP_DISPLAY_NAME)
        set(display_name "${APP_DISPLAY_NAME}")
    else()
        set(display_name "${id}")
    endif()
    # Only package-relative strings enter C++; source paths stay in CMake.
    foreach(value id display_name)
        string(REPLACE "\\" "\\\\" ${value}_cpp "${${value}}")
        string(REPLACE "\"" "\\\"" ${value}_cpp "${${value}_cpp}")
        string(REPLACE "\n" "\\n" ${value}_cpp "${${value}_cpp}")
        string(REPLACE "\r" "\\r" ${value}_cpp "${${value}_cpp}")
    endforeach()
    set(generated "${CMAKE_CURRENT_BINARY_DIR}/generated")
    file(MAKE_DIRECTORY "${generated}/gyo")
    file(CONFIGURE OUTPUT "${generated}/gyo/AppConfig.hpp" CONTENT [=[
#pragma once
namespace Gyo::AppConfig {
inline constexpr const char* Id = "@id_cpp@";
inline constexpr const char* DisplayName = "@display_name_cpp@";
inline constexpr const char* Assets = "assets/@id_cpp@";
inline constexpr const char* Shaders = "shaders/@id_cpp@";
inline constexpr const char* CommonAssets = "assets/common";
inline constexpr const char* BuiltinShaders = "shaders/builtin";
}
]=] @ONLY)
    set(GYO_APP_ID "${id}" PARENT_SCOPE)
    set(GYO_APP_ASSET_ROOT "${asset_root}" PARENT_SCOPE)
    set(GYO_APP_GENERATED_INCLUDE_DIR "${generated}" PARENT_SCOPE)
    # Quality and release tooling consume the completed product graph. A plain
    # product build does not even load this extension module or its app files.
    if(BUILD_TESTING OR GYO_ENABLE_PACKAGING)
        include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/GyoAppTooling.cmake")
        cmake_language(DEFER CALL _gyo_configure_optional_app_tools)
    endif()
endfunction()

function(_gyo_require_app_context)
    get_property(context DIRECTORY PROPERTY GYO_APP_CONTEXT)
    if("${context}" STREQUAL "" OR NOT context STREQUAL GYO_APP_ID)
        message(FATAL_ERROR "Call gyo_app_project() before creating app targets or content")
    endif()
endfunction()

function(_gyo_app_target_name role main output)
    _gyo_require_app_context()
    if(NOT role MATCHES "^[a-z][a-z0-9_]*$")
        message(FATAL_ERROR "Invalid app target role '${role}'")
    endif()
    get_property(roles DIRECTORY PROPERTY GYO_APP_TARGET_ROLES)
    if(role IN_LIST roles)
        message(FATAL_ERROR "Duplicate app target role ${GYO_APP_ID}/${role}")
    endif()
    set_property(DIRECTORY APPEND PROPERTY GYO_APP_TARGET_ROLES "${role}")
    if(main)
        set(target "gyo_${GYO_APP_ID}")
    else()
        # App IDs and roles cannot contain '-', so this separator is unambiguous.
        set(target "gyo_${GYO_APP_ID}-${role}")
    endif()
    if(TARGET "${target}")
        message(FATAL_ERROR "App target already exists: ${target}")
    endif()
    set_property(DIRECTORY PROPERTY "GYO_APP_ROLE_${role}_TARGET" "${target}")
    set(${output} "${target}" PARENT_SCOPE)
endfunction()

function(gyo_app_get_target role)
    _gyo_require_app_context()
    cmake_parse_arguments(PARSE_ARGV 1 LOOKUP "" "OUT_TARGET" "")
    if(LOOKUP_UNPARSED_ARGUMENTS OR LOOKUP_KEYWORDS_MISSING_VALUES OR NOT LOOKUP_OUT_TARGET)
        message(FATAL_ERROR "gyo_app_get_target requires a role and OUT_TARGET")
    endif()
    get_property(target DIRECTORY PROPERTY "GYO_APP_ROLE_${role}_TARGET")
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "App ${GYO_APP_ID} has no product target role '${role}'")
    endif()
    set(${LOOKUP_OUT_TARGET} "${target}" PARENT_SCOPE)
endfunction()

function(_gyo_app_target_defaults target)
    set_property(TARGET ${target} PROPERTY GYO_APP_OWNER "${GYO_APP_ID}")
    target_compile_features(${target} PUBLIC cxx_std_20)
    set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF)
    get_target_property(type ${target} TYPE)
    if(type STREQUAL EXECUTABLE)
        # Shader build output must not be an ancestor of staged runtime content.
        set_target_properties(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/bin")
    endif()
    target_include_directories(${target} PRIVATE "${GYO_APP_GENERATED_INCLUDE_DIR}")
    if(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/include")
        target_include_directories(${target} PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")
    endif()
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4 /permissive- /utf-8)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    endif()
    if(WIN32)
        target_compile_definitions(${target} PRIVATE NOMINMAX)
    endif()
endfunction()

function(gyo_app_link_components target visibility)
    _gyo_require_app_context()
    if(NOT TARGET "${target}" OR NOT visibility MATCHES "^(PUBLIC|PRIVATE|INTERFACE)$")
        message(FATAL_ERROR "gyo_app_link_components requires a target and PUBLIC, PRIVATE or INTERFACE visibility")
    endif()
    get_target_property(owner ${target} GYO_APP_OWNER)
    if(NOT owner STREQUAL GYO_APP_ID)
        message(FATAL_ERROR "Cannot modify another project's target: ${target}")
    endif()
    gyo_validate_components(${ARGN})
    get_property(declared GLOBAL PROPERTY GYO_APP_${GYO_APP_ID}_COMPONENTS)
    set(SDL_PLATFORM GYO::PlatformSDL)
    set(SDL_RENDERER GYO::RenderBackendSDL)
    set(SDL_GPU GYO::RenderBackendSDLGPU)
    set(SDL_INPUT GYO::InputBackendSDL)
    set(SDL_IMAGE GYO::AssetSdlImage)
    set(SDL_TTF GYO::TextBackendSDLTTF)
    set(UFBX GYO::AssetUfbx)
    set(IMGUI imgui::sdl3_sdlrenderer3)
    foreach(component IN LISTS ARGN)
        # SDL platform is also an implicit dependency of its renderer/input APIs.
        set(available "${declared}")
        if("SDL_GPU" IN_LIST declared OR "SDL_RENDERER" IN_LIST declared OR "SDL_INPUT" IN_LIST declared)
            list(APPEND available SDL_PLATFORM)
        endif()
        if(NOT component IN_LIST available)
            message(FATAL_ERROR "App ${GYO_APP_ID} did not declare component ${component} in gyo_app_requirements()")
        endif()
        if(NOT TARGET "${${component}}")
            message(FATAL_ERROR "Required component ${component} target ${${component}} is unavailable for ${GYO_APP_ID}")
        endif()
        target_link_libraries(${target} ${visibility} ${${component}})
    endforeach()
endfunction()

function(gyo_app_add_library role)
    cmake_parse_arguments(PARSE_ARGV 1 LIB "" "OUT_TARGET"
        "SOURCES;PUBLIC_LIBRARIES;PRIVATE_LIBRARIES;PUBLIC_COMPONENTS;PRIVATE_COMPONENTS")
    if(LIB_UNPARSED_ARGUMENTS OR LIB_KEYWORDS_MISSING_VALUES OR NOT LIB_OUT_TARGET OR NOT LIB_SOURCES)
        message(FATAL_ERROR "gyo_app_add_library requires a role, OUT_TARGET and explicit SOURCES")
    endif()
    _gyo_app_target_name("${role}" FALSE target)
    add_library(${target} STATIC ${LIB_SOURCES})
    _gyo_app_target_defaults(${target})
    target_link_libraries(${target} PUBLIC ${LIB_PUBLIC_LIBRARIES} PRIVATE ${LIB_PRIVATE_LIBRARIES})
    gyo_app_link_components(${target} PUBLIC ${LIB_PUBLIC_COMPONENTS})
    gyo_app_link_components(${target} PRIVATE ${LIB_PRIVATE_COMPONENTS})
    set(${LIB_OUT_TARGET} "${target}" PARENT_SCOPE)
endfunction()

function(gyo_app_add_executable role)
    cmake_parse_arguments(PARSE_ARGV 1 EXE "MAIN;WIN32" "OUT_TARGET" "SOURCES;LIBRARIES;COMPONENTS")
    if(EXE_UNPARSED_ARGUMENTS OR EXE_KEYWORDS_MISSING_VALUES OR NOT EXE_OUT_TARGET OR NOT EXE_SOURCES)
        message(FATAL_ERROR "gyo_app_add_executable requires a role, OUT_TARGET and explicit SOURCES")
    endif()
    _gyo_app_target_name("${role}" "${EXE_MAIN}" target)
    set(options "")
    if(EXE_WIN32)
        list(APPEND options WIN32)
    endif()
    add_executable(${target} ${options} ${EXE_SOURCES})
    _gyo_app_target_defaults(${target})
    target_link_libraries(${target} PRIVATE ${EXE_LIBRARIES})
    gyo_app_link_components(${target} PRIVATE ${EXE_COMPONENTS})
    gyo_copy_runtime_dlls(${target})
    if(EXE_MAIN)
        set_property(DIRECTORY PROPERTY GYO_APP_MAIN_TARGET "${target}")
        gyo_install_app_target(${target})
    endif()
    set(${EXE_OUT_TARGET} "${target}" PARENT_SCOPE)
endfunction()

function(_gyo_app_content_directory target source destination required output)
    if(NOT IS_DIRECTORY "${source}")
        message(FATAL_ERROR "App ${GYO_APP_ID} content directory is missing: ${source}")
    endif()
    if(required AND NOT EXISTS "${source}/${required}")
        message(FATAL_ERROR "App ${GYO_APP_ID} required content is missing: ${source}/${required}")
    endif()
    _gyo_app_claim_destination("${source}" "${destination}")
    set(${output}
        COMMAND "${CMAKE_COMMAND}" -E copy_directory "${source}" "$<TARGET_FILE_DIR:${target}>/${destination}"
        PARENT_SCOPE)
    install(DIRECTORY "${source}/" DESTINATION "bin/${destination}")
endfunction()

function(_gyo_app_claim_destination source destination)
    get_property(destinations DIRECTORY PROPERTY GYO_APP_CONTENT_DESTINATIONS)
    if(destination IN_LIST destinations)
        message(FATAL_ERROR "Duplicate app deployment destination ${GYO_APP_ID}/${destination}")
    endif()
    set_property(DIRECTORY APPEND PROPERTY GYO_APP_CONTENT_DESTINATIONS "${destination}")
    # Different apps may share identical engine content, never different content
    # at the same install location. This also catches reserved-name collisions.
    string(SHA256 key "${destination}")
    get_property(previous GLOBAL PROPERTY GYO_CONTENT_SOURCE_${key})
    cmake_path(NORMAL_PATH source OUTPUT_VARIABLE normalized)
    if(previous AND NOT previous STREQUAL normalized)
        message(FATAL_ERROR "Conflicting deployment destination ${destination}: ${previous} and ${normalized}")
    endif()
    set_property(GLOBAL PROPERTY GYO_CONTENT_SOURCE_${key} "${normalized}")
endfunction()

function(gyo_app_deploy_content)
    _gyo_require_app_context()
    cmake_parse_arguments(PARSE_ARGV 0 CONTENT "ASSETS;COMMON_ASSETS;BUILTIN_SHADERS"
        "TARGET;SHADER_SPEC;OUT_REQUIRED_FILES;OUT_STAGE_TARGET" "")
    if(CONTENT_UNPARSED_ARGUMENTS OR CONTENT_KEYWORDS_MISSING_VALUES OR
       NOT TARGET "${CONTENT_TARGET}")
        message(FATAL_ERROR "gyo_app_deploy_content requires an executable TARGET")
    endif()
    get_target_property(owner ${CONTENT_TARGET} GYO_APP_OWNER)
    get_target_property(type ${CONTENT_TARGET} TYPE)
    if(NOT owner STREQUAL GYO_APP_ID OR NOT type STREQUAL EXECUTABLE)
        message(FATAL_ERROR "Content must belong to this app's executable: ${CONTENT_TARGET}")
    endif()
    set(commands "")
    set(dependencies "")
    set(required_files "")
    if(CONTENT_ASSETS)
        _gyo_app_content_directory(${CONTENT_TARGET} "${GYO_APP_ASSET_ROOT}"
            "assets/${GYO_APP_ID}" asset_catalog.json copy_command)
        list(APPEND commands ${copy_command})
        list(APPEND required_files "bin/assets/${GYO_APP_ID}/asset_catalog.json")
    endif()
    if(CONTENT_COMMON_ASSETS)
        _gyo_app_content_directory(${CONTENT_TARGET} "${PROJECT_SOURCE_DIR}/assets/common"
            assets/common asset_catalog.json copy_command)
        list(APPEND commands ${copy_command})
        list(APPEND required_files bin/assets/common/asset_catalog.json)
    endif()
    if(CONTENT_SHADER_SPEC)
        get_filename_component(spec "${CONTENT_SHADER_SPEC}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
        if(NOT EXISTS "${spec}")
            message(FATAL_ERROR "App shader specification is missing: ${spec}")
        endif()
        set(shader_directory "${CMAKE_CURRENT_BINARY_DIR}/shaders")
        _gyo_app_claim_destination("${shader_directory}" "shaders/${GYO_APP_ID}")
        if(NOT COMMAND gyo_add_shader_bundle)
            include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/GyoShaders.cmake")
        endif()
        set(shaders "gyo_${GYO_APP_ID}--shaders")
        gyo_add_shader_bundle(${shaders} SPEC "${spec}" OUTPUT_DIRECTORY "${shader_directory}")
        list(APPEND dependencies ${shaders})
        list(APPEND commands COMMAND "${CMAKE_COMMAND}" -E copy_directory
            "${shader_directory}" "$<TARGET_FILE_DIR:${CONTENT_TARGET}>/shaders/${GYO_APP_ID}")
        install(DIRECTORY "${shader_directory}/" DESTINATION "bin/shaders/${GYO_APP_ID}")
        list(APPEND required_files "bin/shaders/${GYO_APP_ID}/manifest.json")
    endif()
    if(CONTENT_BUILTIN_SHADERS)
        if(NOT TARGET gyo_builtin_shaders)
            message(FATAL_ERROR "Builtin shaders are unavailable; declare the SDL_GPU component")
        endif()
        set(builtin "${PROJECT_BINARY_DIR}/shaders/builtin")
        _gyo_app_claim_destination("${builtin}" shaders/builtin)
        list(APPEND dependencies gyo_builtin_shaders)
        list(APPEND commands COMMAND "${CMAKE_COMMAND}" -E copy_directory
            "${builtin}" "$<TARGET_FILE_DIR:${CONTENT_TARGET}>/shaders/builtin")
        install(DIRECTORY "${builtin}/" DESTINATION bin/shaders/builtin)
        list(APPEND required_files bin/shaders/builtin/manifest.json)
    endif()
    set(staging "")
    if(commands)
        get_property(count DIRECTORY PROPERTY GYO_APP_CONTENT_TARGET_COUNT)
        if(NOT count)
            set(count 0)
        endif()
        math(EXPR count "${count}+1")
        set_property(DIRECTORY PROPERTY GYO_APP_CONTENT_TARGET_COUNT "${count}")
        set(staging "gyo_${GYO_APP_ID}--content-${count}")
        cmake_policy(PUSH)
        cmake_policy(SET CMP0112 NEW)
        add_custom_target(${staging} ${commands} DEPENDS ${dependencies}
            COMMENT "Staging content for ${GYO_APP_ID}" VERBATIM)
        cmake_policy(POP)
        add_dependencies(${CONTENT_TARGET} ${staging})
    endif()
    set_property(TARGET ${CONTENT_TARGET} APPEND PROPERTY GYO_APP_REQUIRED_FILES "${required_files}")
    set_property(TARGET ${CONTENT_TARGET} PROPERTY GYO_APP_CONTENT_STAGE_TARGET "${staging}")
    if(DEFINED CONTENT_OUT_REQUIRED_FILES)
        set(${CONTENT_OUT_REQUIRED_FILES} "${required_files}" PARENT_SCOPE)
    endif()
    if(DEFINED CONTENT_OUT_STAGE_TARGET)
        set(${CONTENT_OUT_STAGE_TARGET} "${staging}" PARENT_SCOPE)
    endif()
endfunction()
