include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/GyoRuntimeDeployment.cmake")

function(_gyo_package_quote value output)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()

function(_gyo_package_array variable output)
    set(array "[]")
    set(index 0)
    foreach(value IN LISTS ${variable})
        _gyo_package_quote("${value}" quoted)
        string(JSON array SET "${array}" ${index} "${quoted}")
        math(EXPR index "${index}+1")
    endforeach()
    set(${output} "${array}" PARENT_SCOPE)
endfunction()

function(gyo_add_app_package_check)
    if(NOT GYO_ENABLE_PACKAGING)
        return()
    endif()
    cmake_parse_arguments(PARSE_ARGV 0 CHECK "GPU" "NAME;TIMEOUT" "COMMAND;ENVIRONMENT;PROFILES;PLATFORMS")
    _gyo_register_package_check()
endfunction()

# Read the parsed variables in the caller's scope. Forwarding them through a
# second argument parser would lose empty argv entries and escaped semicolons.
function(_gyo_register_package_check)
    if(CHECK_UNPARSED_ARGUMENTS OR CHECK_KEYWORDS_MISSING_VALUES OR
       NOT CHECK_NAME MATCHES "^[a-z][a-z0-9_-]*$" OR NOT CHECK_COMMAND)
        message(FATAL_ERROR "Invalid package check declaration for '${GYO_CURRENT_APP}'")
    endif()
    get_property(manifest GLOBAL PROPERTY GYO_APP_${GYO_CURRENT_APP}_PACKAGE)
    if(NOT manifest)
        message(FATAL_ERROR "Register ${GYO_CURRENT_APP}'s package before adding checks")
    endif()
    if(NOT DEFINED CHECK_TIMEOUT)
        set(CHECK_TIMEOUT 30)
    endif()
    if(NOT CHECK_TIMEOUT MATCHES "^[1-9][0-9]*$" OR CHECK_TIMEOUT GREATER 3600)
        message(FATAL_ERROR "Package check timeout must be an integer between 1 and 3600 seconds")
    endif()
    if(NOT CHECK_PROFILES)
        set(CHECK_PROFILES quick release)
    endif()
    if(NOT CHECK_PLATFORMS)
        set(CHECK_PLATFORMS windows-x64 linux-x64 macos-arm64)
    endif()
    foreach(profile IN LISTS CHECK_PROFILES)
        if(NOT profile MATCHES "^(quick|release)$")
            message(FATAL_ERROR "Unknown package check profile: ${profile}")
        endif()
    endforeach()
    foreach(platform IN LISTS CHECK_PLATFORMS)
        if(NOT platform MATCHES "^(windows-x64|linux-x64|macos-arm64)$")
            message(FATAL_ERROR "Unknown package check platform: ${platform}")
        endif()
    endforeach()
    set(check "{}")
    _gyo_package_quote("${CHECK_NAME}" quoted)
    string(JSON check SET "${check}" name "${quoted}")
    foreach(pair "command|COMMAND" "environment|ENVIRONMENT" "profiles|PROFILES" "platforms|PLATFORMS")
        string(REPLACE "|" ";" pair "${pair}")
        list(GET pair 0 field)
        list(GET pair 1 argument)
        _gyo_package_array(CHECK_${argument} array)
        string(JSON check SET "${check}" "${field}" "${array}")
    endforeach()
    string(JSON check SET "${check}" timeout "${CHECK_TIMEOUT}")
    if(CHECK_GPU)
        string(JSON check SET "${check}" gpu true)
    else()
        string(JSON check SET "${check}" gpu false)
    endif()
    string(JSON count LENGTH "${manifest}" checks)
    if(count GREATER 0)
        math(EXPR last "${count}-1")
        foreach(index RANGE 0 ${last})
            string(JSON name GET "${manifest}" checks ${index} name)
            if(name STREQUAL CHECK_NAME)
                message(FATAL_ERROR "Duplicate package check ${GYO_CURRENT_APP}/${CHECK_NAME}")
            endif()
        endforeach()
    endif()
    string(JSON manifest SET "${manifest}" checks ${count} "${check}")
    set_property(GLOBAL PROPERTY GYO_APP_${GYO_CURRENT_APP}_PACKAGE "${manifest}")
endfunction()

function(_gyo_package_platform output)
    set(architecture "${CMAKE_SYSTEM_PROCESSOR}")
    if(MSVC AND CMAKE_CXX_COMPILER_ARCHITECTURE_ID)
        set(architecture "${CMAKE_CXX_COMPILER_ARCHITECTURE_ID}")
    elseif(APPLE AND CMAKE_OSX_ARCHITECTURES)
        set(architecture "${CMAKE_OSX_ARCHITECTURES}")
    endif()
    string(TOLOWER "${architecture}" architecture)
    if(CMAKE_SYSTEM_NAME STREQUAL Windows AND architecture MATCHES "^(x64|amd64|x86_64)$")
        set(platform windows-x64)
    elseif(CMAKE_SYSTEM_NAME STREQUAL Linux AND architecture MATCHES "^(x64|amd64|x86_64)$")
        set(platform linux-x64)
    elseif(CMAKE_SYSTEM_NAME STREQUAL Darwin AND architecture MATCHES "^(arm64|aarch64)$")
        set(platform macos-arm64)
    else()
        message(FATAL_ERROR "No package platform for ${CMAKE_SYSTEM_NAME}/${architecture}; supported targets are Windows x64, Linux x64 and macOS ARM64")
    endif()
    set(${output} "${platform}" PARENT_SCOPE)
endfunction()

function(gyo_register_app_package)
    cmake_parse_arguments(PARSE_ARGV 0 APP "" "TARGET;STARTUP_TIMEOUT" "STARTUP_ARGS;STARTUP_ENVIRONMENT;REQUIRED_FILES")
    if(NOT DEFINED APP_TARGET)
        get_property(APP_TARGET DIRECTORY PROPERTY GYO_APP_MAIN_TARGET)
    endif()
    # Legacy apps register their executable through this API. Keep that normal
    # install behavior without inspecting their optional release declaration.
    gyo_install_app_target("${APP_TARGET}")
    if(NOT GYO_ENABLE_PACKAGING)
        return()
    endif()
    if(APP_UNPARSED_ARGUMENTS OR APP_KEYWORDS_MISSING_VALUES OR
       "${GYO_CURRENT_APP}" STREQUAL "" OR NOT TARGET "${APP_TARGET}")
        message(FATAL_ERROR "gyo_register_app_package requires an app context and an executable TARGET")
    endif()
    get_target_property(type "${APP_TARGET}" TYPE)
    if(NOT type STREQUAL EXECUTABLE)
        message(FATAL_ERROR "Package target ${APP_TARGET} is not an executable")
    endif()
    get_property(existing GLOBAL PROPERTY GYO_APP_${GYO_CURRENT_APP}_PACKAGE)
    if(existing)
        message(FATAL_ERROR "App ${GYO_CURRENT_APP} registered more than one package")
    endif()
    _gyo_package_platform(platform)
    set(executable "bin/$<TARGET_FILE_NAME:${APP_TARGET}>")
    set(manifest "{\"schema_version\":1,\"checks\":[],\"runtime_dependencies\":[]}")
    foreach(field app platform executable)
        if(field STREQUAL "app")
            set(value "${GYO_CURRENT_APP}")
        else()
            set(value "${${field}}")
        endif()
        _gyo_package_quote("${value}" quoted)
        string(JSON manifest SET "${manifest}" "${field}" "${quoted}")
    endforeach()
    set(files "${executable}")
    get_property(content_files TARGET "${APP_TARGET}" PROPERTY GYO_APP_REQUIRED_FILES)
    if(NOT "${content_files}" STREQUAL "")
        set(files "${files};${content_files}")
    endif()
    if(DEFINED APP_REQUIRED_FILES)
        set(files "${files};${APP_REQUIRED_FILES}")
    endif()
    set(files_json "[]")
    set(seen_paths "")
    set(file_count 0)
    foreach(path IN LISTS files)
        if(IS_ABSOLUTE "${path}" OR path MATCHES "(^|/)\\.\\.(/|$)" OR path MATCHES "\\\\")
            message(FATAL_ERROR "Package required files must use package-relative paths: ${path}")
        endif()
        # Deduplicate identities, not the CMake list representation: rebuilding
        # a list (including REMOVE_DUPLICATES) can split literal semicolons or
        # drop empty entries. Preserve first occurrence order directly in JSON.
        string(SHA256 identity "${path}")
        if(identity IN_LIST seen_paths)
            continue()
        endif()
        list(APPEND seen_paths "${identity}")
        _gyo_package_quote("${path}" quoted)
        string(JSON files_json SET "${files_json}" ${file_count} "${quoted}")
        math(EXPR file_count "${file_count}+1")
    endforeach()
    string(JSON manifest SET "${manifest}" required_files "${files_json}")
    get_property(components GLOBAL PROPERTY GYO_APP_${GYO_CURRENT_APP}_COMPONENTS)
    foreach(component IN LISTS components)
        if(component MATCHES "^SDL_" OR component STREQUAL "IMGUI")
            string(JSON manifest SET "${manifest}" runtime_dependencies "[\"SDL3\"]")
            break()
        endif()
    endforeach()
    set_property(GLOBAL PROPERTY GYO_APP_${GYO_CURRENT_APP}_PACKAGE "${manifest}")
    set_property(GLOBAL APPEND PROPERTY GYO_PACKAGE_APPS "${GYO_CURRENT_APP}")
    set(CHECK_NAME startup)
    set(CHECK_COMMAND "@EXECUTABLE@")
    if(DEFINED APP_STARTUP_ARGS)
        set(CHECK_COMMAND "${CHECK_COMMAND};${APP_STARTUP_ARGS}")
    endif()
    set(CHECK_ENVIRONMENT "${APP_STARTUP_ENVIRONMENT}")
    if(DEFINED APP_STARTUP_TIMEOUT)
        set(CHECK_TIMEOUT "${APP_STARTUP_TIMEOUT}")
    endif()
    _gyo_register_package_check()
endfunction()

function(gyo_finalize_app_packages)
    if(NOT GYO_ENABLE_PACKAGING)
        return()
    endif()
    foreach(app IN LISTS GYO_ACTIVE_APPS)
        get_property(manifest GLOBAL PROPERTY GYO_APP_${app}_PACKAGE)
        if(NOT manifest)
            message(FATAL_ERROR "Enabled app '${app}' must call gyo_register_app_package() with its installed startup test")
        endif()
        set(output "${PROJECT_BINARY_DIR}/packages/${app}/$<CONFIG>/manifest.json")
        file(GENERATE OUTPUT "${output}" CONTENT "${manifest}\n")
        install(FILES "${output}" DESTINATION "share/gyo/apps/${app}")
    endforeach()
endfunction()
