include_guard(GLOBAL)

set(GYO_KNOWN_COMPONENTS SDL_PLATFORM SDL_RENDERER SDL_GPU SDL_INPUT SDL_IMAGE SDL_TTF UFBX IMGUI)

function(gyo_validate_components)
    foreach(component IN LISTS ARGN)
        if(NOT component IN_LIST GYO_KNOWN_COMPONENTS)
            message(FATAL_ERROR "Unknown GYO component '${component}'; expected one of: ${GYO_KNOWN_COMPONENTS}")
        endif()
    endforeach()
endfunction()

# Requests are recomputed on every configure. User options are inputs, never
# overwritten with a previous consumer's effective requirements.
function(gyo_resolve_components)
    set(components ${ARGN})
    gyo_validate_components(${components})
    option(GYO_BUILD_SDL_GPU_BACKEND "Explicitly enable the SDL_GPU render backend" OFF)
    option(GYO_BUILD_SDL_IMAGE_LOADER "Explicitly enable the SDL_image texture loader" OFF)
    option(GYO_BUILD_SDL_TTF_ADAPTER "Explicitly enable the SDL_ttf text adapter" OFF)
    option(GYO_BUILD_UFBX_LOADER "Explicitly enable the ufbx model loader" OFF)
    foreach(pair "SDL_IMAGE|GYO_BUILD_SDL_IMAGE_LOADER" "SDL_TTF|GYO_BUILD_SDL_TTF_ADAPTER" "UFBX|GYO_BUILD_UFBX_LOADER")
        string(REPLACE "|" ";" pair "${pair}")
        list(GET pair 0 component)
        list(GET pair 1 option_name)
        if(${option_name})
            list(APPEND components "${component}")
        endif()
    endforeach()
    set(GYO_REQUIRE_SDL_GPU OFF)
    if("SDL_GPU" IN_LIST components)
        set(GYO_REQUIRE_SDL_GPU ON)
    endif()
    include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/GyoRenderOptions.cmake")
    if(GYO_ENABLE_SDL_GPU)
        list(APPEND components SDL_GPU)
    endif()
    if("SDL_RENDERER" IN_LIST components OR "SDL_GPU" IN_LIST components OR "SDL_INPUT" IN_LIST components)
        list(APPEND components SDL_PLATFORM)
    endif()
    set(GYO_ENABLE_SDL3 OFF)
    if("SDL_PLATFORM" IN_LIST components OR "SDL_IMAGE" IN_LIST components OR
       "SDL_TTF" IN_LIST components OR "IMGUI" IN_LIST components)
        set(GYO_ENABLE_SDL3 ON)
    endif()
    foreach(component IN LISTS GYO_KNOWN_COMPONENTS)
        set(enabled OFF)
        if(component IN_LIST components)
            set(enabled ON)
        endif()
        set(GYO_ENABLE_${component} "${enabled}" PARENT_SCOPE)
    endforeach()
    foreach(variable GYO_ENABLE_SDL3 GYO_SHADER_FORMATS GYO_DEFAULT_GPU_DRIVER)
        set(${variable} "${${variable}}" PARENT_SCOPE)
    endforeach()
endfunction()
