include_guard(GLOBAL)

function(gyo_copy_runtime_dlls target)
    if(WIN32)
        get_target_property(configured ${target} GYO_RUNTIME_DLLS_CONFIGURED)
        if(configured)
            return()
        endif()
        set_property(TARGET ${target} PROPERTY GYO_RUNTIME_DLLS_CONFIGURED TRUE)
        # copy_if_different with no input DLLs fails for backend-neutral targets.
        # The generated script preserves each path, including spaces.
        set(script "${CMAKE_CURRENT_BINARY_DIR}/${target}-runtime-$<CONFIG>.cmake")
        file(GENERATE OUTPUT "${script}" CONTENT
            "set(files [==[$<TARGET_RUNTIME_DLLS:${target}>]==])\nset(destination [==[$<TARGET_FILE_DIR:${target}>]==])\nforeach(file IN LISTS files)\n  get_filename_component(name \"\${file}\" NAME)\n  file(COPY_FILE \"\${file}\" \"\${destination}/\${name}\" ONLY_IF_DIFFERENT)\nendforeach()\n")
        add_custom_command(TARGET ${target} POST_BUILD
            COMMAND "${CMAKE_COMMAND}" -P "${script}" VERBATIM)
    endif()
endfunction()

# Installing an application is a product operation, independent of its optional
# release manifest, startup checks or test targets.
function(gyo_install_app_target target)
    if("${GYO_CURRENT_APP}" STREQUAL "" OR NOT TARGET "${target}")
        message(FATAL_ERROR "gyo_install_app_target requires an app context and an executable target")
    endif()
    get_target_property(type "${target}" TYPE)
    if(NOT type STREQUAL "EXECUTABLE")
        message(FATAL_ERROR "App install target ${target} is not an executable")
    endif()
    get_target_property(installed "${target}" GYO_APP_INSTALL_REGISTERED)
    if(installed)
        get_target_property(owner "${target}" GYO_APP_INSTALL_OWNER)
        if(NOT "${owner}" STREQUAL "${GYO_CURRENT_APP}")
            message(FATAL_ERROR "App install target ${target} already belongs to ${owner}")
        endif()
        return()
    endif()
    set_property(TARGET "${target}" PROPERTY GYO_APP_INSTALL_REGISTERED TRUE)
    set_property(TARGET "${target}" PROPERTY GYO_APP_INSTALL_OWNER "${GYO_CURRENT_APP}")
    set_property(GLOBAL APPEND PROPERTY GYO_INSTALLED_APP_TARGETS "${target}")
    install(TARGETS ${target} RUNTIME DESTINATION bin)
    gyo_copy_runtime_dlls(${target})
endfunction()

function(gyo_finalize_app_installation)
    get_property(targets GLOBAL PROPERTY GYO_INSTALLED_APP_TARGETS)
    if("${targets}" STREQUAL "")
        return()
    endif()
    set(install_sdl3 OFF)
    foreach(target IN LISTS targets)
        get_target_property(owner "${target}" GYO_APP_INSTALL_OWNER)
        get_property(components GLOBAL PROPERTY GYO_APP_${owner}_COMPONENTS)
        foreach(component IN LISTS components)
            if(component MATCHES "^SDL_" OR component STREQUAL "IMGUI")
                set(install_sdl3 ON)
                break()
            endif()
        endforeach()
    endforeach()
    if(install_sdl3 AND TARGET SDL3-shared)
        install(TARGETS SDL3-shared RUNTIME DESTINATION bin LIBRARY DESTINATION lib)
    endif()
    if(MSVC)
        include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/GyoMsvcRuntime.cmake")
        gyo_install_msvc_runtime()
    endif()
endfunction()
