include_guard(GLOBAL)

set(GYO_RENDER_DEVICE AUTO CACHE STRING "Render device implementation: AUTO, SDL_GPU, NONE")
set_property(CACHE GYO_RENDER_DEVICE PROPERTY STRINGS AUTO SDL_GPU NONE)
set(GYO_GPU_DRIVER AUTO CACHE STRING "Default GPU driver: AUTO, D3D12, VULKAN, METAL")
set_property(CACHE GYO_GPU_DRIVER PROPERTY STRINGS AUTO D3D12 VULKAN METAL)
set(GYO_SHADER_BUNDLE AUTO CACHE STRING "AUTO or semicolon-separated DXIL, SPIRV, METALLIB formats")
string(TOUPPER "${GYO_RENDER_DEVICE}" GYO_RENDER_DEVICE)
string(TOUPPER "${GYO_GPU_DRIVER}" GYO_GPU_DRIVER)
string(TOUPPER "${GYO_SHADER_BUNDLE}" _gyo_bundle)
if(NOT GYO_RENDER_DEVICE MATCHES "^(AUTO|SDL_GPU|NONE)$")
    message(FATAL_ERROR "Unsupported GYO_RENDER_DEVICE=${GYO_RENDER_DEVICE}")
endif()
if(NOT GYO_GPU_DRIVER MATCHES "^(AUTO|D3D12|VULKAN|METAL)$")
    message(FATAL_ERROR "Unsupported GYO_GPU_DRIVER=${GYO_GPU_DRIVER}")
endif()
set(GYO_ENABLE_SDL_GPU OFF)
if(GYO_RENDER_DEVICE STREQUAL "SDL_GPU" OR
   (GYO_RENDER_DEVICE STREQUAL "AUTO" AND (GYO_BUILD_OBJECT_FPS OR GYO_BUILD_SDL_GPU_BACKEND)))
    set(GYO_ENABLE_SDL_GPU ON)
elseif(GYO_RENDER_DEVICE STREQUAL "NONE" AND GYO_BUILD_SDL_GPU_BACKEND)
    message(FATAL_ERROR "GYO_RENDER_DEVICE=NONE conflicts with GYO_BUILD_SDL_GPU_BACKEND=ON")
endif()

set(GYO_SHADER_FORMATS "")
string(TOLOWER "${GYO_GPU_DRIVER}" GYO_DEFAULT_GPU_DRIVER)
if(GYO_ENABLE_SDL_GPU)
    if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
        set(_gyo_allowed_formats dxil spirv)
        set(_gyo_allowed_drivers AUTO D3D12 VULKAN)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set(_gyo_allowed_formats spirv)
        set(_gyo_allowed_drivers AUTO VULKAN)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        set(_gyo_allowed_formats metallib)
        set(_gyo_allowed_drivers AUTO METAL)
    else()
        message(FATAL_ERROR "SDL_GPU is not configured for target ${CMAKE_SYSTEM_NAME}")
    endif()
    if(NOT GYO_GPU_DRIVER IN_LIST _gyo_allowed_drivers)
        message(FATAL_ERROR "${GYO_GPU_DRIVER} is unsupported on target ${CMAKE_SYSTEM_NAME}")
    endif()
    if(_gyo_bundle STREQUAL "AUTO")
        set(GYO_SHADER_FORMATS ${_gyo_allowed_formats})
    else()
        foreach(_gyo_format IN LISTS _gyo_bundle)
            string(TOLOWER "${_gyo_format}" _gyo_format)
            if(NOT _gyo_format IN_LIST _gyo_allowed_formats)
                message(FATAL_ERROR "Shader format ${_gyo_format} is unsupported on target ${CMAKE_SYSTEM_NAME}")
            endif()
            list(APPEND GYO_SHADER_FORMATS "${_gyo_format}")
        endforeach()
        if(NOT GYO_SHADER_FORMATS)
            message(FATAL_ERROR "GYO_SHADER_BUNDLE must not be empty when SDL_GPU is enabled")
        endif()
        list(REMOVE_DUPLICATES GYO_SHADER_FORMATS)
    endif()
    if(GYO_GPU_DRIVER STREQUAL "D3D12")
        set(_gyo_required_format dxil)
    elseif(GYO_GPU_DRIVER STREQUAL "VULKAN")
        set(_gyo_required_format spirv)
    elseif(GYO_GPU_DRIVER STREQUAL "METAL")
        set(_gyo_required_format metallib)
    else()
        unset(_gyo_required_format)
    endif()
    if(DEFINED _gyo_required_format AND NOT _gyo_required_format IN_LIST GYO_SHADER_FORMATS)
        message(FATAL_ERROR "${GYO_GPU_DRIVER} requires ${_gyo_required_format} in GYO_SHADER_BUNDLE")
    endif()
endif()
message(STATUS "GYO render: target=${CMAKE_SYSTEM_NAME}, device=${GYO_RENDER_DEVICE}, SDL_GPU=${GYO_ENABLE_SDL_GPU}, driver=${GYO_GPU_DRIVER}, formats=${GYO_SHADER_FORMATS}")
