// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: runtime_v3.proto

package runtimev3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The local IPC host decodes this into product data. Match never sees protobuf,
// sessions, endpoints, or wire envelopes.
type Ready struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ArenaId               string                 `protobuf:"bytes,1,opt,name=arena_id,json=arenaId,proto3" json:"arena_id,omitempty"`
	ArenaVersion          uint32                 `protobuf:"varint,2,opt,name=arena_version,json=arenaVersion,proto3" json:"arena_version,omitempty"`
	TickRate              uint32                 `protobuf:"varint,3,opt,name=tick_rate,json=tickRate,proto3" json:"tick_rate,omitempty"`
	SnapshotIntervalTicks uint32                 `protobuf:"varint,4,opt,name=snapshot_interval_ticks,json=snapshotIntervalTicks,proto3" json:"snapshot_interval_ticks,omitempty"`
	MaxPlayers            uint32                 `protobuf:"varint,5,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_runtime_v3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_runtime_v3_proto_rawDescGZIP(), []int{0}
}

func (x *Ready) GetArenaId() string {
	if x != nil {
		return x.ArenaId
	}
	return ""
}

func (x *Ready) GetArenaVersion() uint32 {
	if x != nil {
		return x.ArenaVersion
	}
	return 0
}

func (x *Ready) GetTickRate() uint32 {
	if x != nil {
		return x.TickRate
	}
	return 0
}

func (x *Ready) GetSnapshotIntervalTicks() uint32 {
	if x != nil {
		return x.SnapshotIntervalTicks
	}
	return 0
}

func (x *Ready) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

type PlayerJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoin) Reset() {
	*x = PlayerJoin{}
	mi := &file_runtime_v3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoin) ProtoMessage() {}

func (x *PlayerJoin) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoin.ProtoReflect.Descriptor instead.
func (*PlayerJoin) Descriptor() ([]byte, []int) {
	return file_runtime_v3_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerJoin) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type PlayerLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeave) Reset() {
	*x = PlayerLeave{}
	mi := &file_runtime_v3_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeave) ProtoMessage() {}

func (x *PlayerLeave) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v3_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeave.ProtoReflect.Descriptor instead.
func (*PlayerLeave) Descriptor() ([]byte, []int) {
	return file_runtime_v3_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerLeave) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// A single immutable 1/60-second movement step. No client time or position.
type MovementCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	MoveForward   float32                `protobuf:"fixed32,2,opt,name=move_forward,json=moveForward,proto3" json:"move_forward,omitempty"`
	MoveRight     float32                `protobuf:"fixed32,3,opt,name=move_right,json=moveRight,proto3" json:"move_right,omitempty"`
	Yaw           float32                `protobuf:"fixed32,4,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch         float32                `protobuf:"fixed32,5,opt,name=pitch,proto3" json:"pitch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovementCommand) Reset() {
	*x = MovementCommand{}
	mi := &file_runtime_v3_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovementCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovementCommand) ProtoMessage() {}

func (x *MovementCommand) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v3_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovementCommand.ProtoReflect.Descriptor instead.
func (*MovementCommand) Descriptor() ([]byte, []int) {
	return file_runtime_v3_proto_rawDescGZIP(), []int{3}
}

func (x *MovementCommand) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MovementCommand) GetMoveForward() float32 {
	if x != nil {
		return x.MoveForward
	}
	return 0
}

func (x *MovementCommand) GetMoveRight() float32 {
	if x != nil {
		return x.MoveRight
	}
	return 0
}

func (x *MovementCommand) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *MovementCommand) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

// Entire unacknowledged window, strictly ordered, at most 12 commands.
type PlayerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Commands      []*MovementCommand     `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	MovementEpoch uint64                 `protobuf:"varint,3,opt,name=movement_epoch,json=movementEpoch,proto3" json:"movement_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_runtime_v3_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v3_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_runtime_v3_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerInput) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerInput) GetCommands() []*MovementCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *PlayerInput) GetMovementEpoch() uint64 {
	if x != nil {
		return x.MovementEpoch
	}
	return 0
}

type JoinResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResult) Reset() {
	*x = JoinResult{}
	mi := &file_runtime_v3_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResult) ProtoMessage() {}

func (x *JoinResult) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v3_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResult.ProtoReflect.Descriptor instead.
func (*JoinResult) Descriptor() ([]byte, []int) {
	return file_runtime_v3_proto_rawDescGZIP(), []int{5}
}

func (x *JoinResult) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *JoinResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *JoinResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PlayerState struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	PlayerId                  uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X                         float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                         float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z                         float32                `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	Yaw                       float32                `protobuf:"fixed32,5,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch                     float32                `protobuf:"fixed32,6,opt,name=pitch,proto3" json:"pitch,omitempty"`
	LastResolvedCommand       uint64                 `protobuf:"varint,7,opt,name=last_resolved_command,json=lastResolvedCommand,proto3" json:"last_resolved_command,omitempty"`
	MovementEpoch             uint64                 `protobuf:"varint,8,opt,name=movement_epoch,json=movementEpoch,proto3" json:"movement_epoch,omitempty"`
	ContiguousPendingCommands uint32                 `protobuf:"varint,9,opt,name=contiguous_pending_commands,json=contiguousPendingCommands,proto3" json:"contiguous_pending_commands,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_runtime_v3_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v3_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_runtime_v3_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerState) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerState) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerState) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *PlayerState) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *PlayerState) GetLastResolvedCommand() uint64 {
	if x != nil {
		return x.LastResolvedCommand
	}
	return 0
}

func (x *PlayerState) GetMovementEpoch() uint64 {
	if x != nil {
		return x.MovementEpoch
	}
	return 0
}

func (x *PlayerState) GetContiguousPendingCommands() uint32 {
	if x != nil {
		return x.ContiguousPendingCommands
	}
	return 0
}

type WorldSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Players       []*PlayerState         `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldSnapshot) Reset() {
	*x = WorldSnapshot{}
	mi := &file_runtime_v3_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldSnapshot) ProtoMessage() {}

func (x *WorldSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v3_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldSnapshot.ProtoReflect.Descriptor instead.
func (*WorldSnapshot) Descriptor() ([]byte, []int) {
	return file_runtime_v3_proto_rawDescGZIP(), []int{7}
}

func (x *WorldSnapshot) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *WorldSnapshot) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

type RuntimeError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeError) Reset() {
	*x = RuntimeError{}
	mi := &file_runtime_v3_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeError) ProtoMessage() {}

func (x *RuntimeError) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v3_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeError.ProtoReflect.Descriptor instead.
func (*RuntimeError) Descriptor() ([]byte, []int) {
	return file_runtime_v3_proto_rawDescGZIP(), []int{8}
}

func (x *RuntimeError) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *RuntimeError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RuntimeError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RuntimeEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*RuntimeEnvelope_Ready
	//	*RuntimeEnvelope_Join
	//	*RuntimeEnvelope_Leave
	//	*RuntimeEnvelope_Input
	//	*RuntimeEnvelope_JoinResult
	//	*RuntimeEnvelope_Error
	//	*RuntimeEnvelope_Snapshot
	Message       isRuntimeEnvelope_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeEnvelope) Reset() {
	*x = RuntimeEnvelope{}
	mi := &file_runtime_v3_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEnvelope) ProtoMessage() {}

func (x *RuntimeEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v3_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEnvelope.ProtoReflect.Descriptor instead.
func (*RuntimeEnvelope) Descriptor() ([]byte, []int) {
	return file_runtime_v3_proto_rawDescGZIP(), []int{9}
}

func (x *RuntimeEnvelope) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *RuntimeEnvelope) GetMessage() isRuntimeEnvelope_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RuntimeEnvelope) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetJoin() *PlayerJoin {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetLeave() *PlayerLeave {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Leave); ok {
			return x.Leave
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetInput() *PlayerInput {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetJoinResult() *JoinResult {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_JoinResult); ok {
			return x.JoinResult
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetError() *RuntimeError {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *RuntimeEnvelope) GetSnapshot() *WorldSnapshot {
	if x != nil {
		if x, ok := x.Message.(*RuntimeEnvelope_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

type isRuntimeEnvelope_Message interface {
	isRuntimeEnvelope_Message()
}

type RuntimeEnvelope_Ready struct {
	Ready *Ready `protobuf:"bytes,10,opt,name=ready,proto3,oneof"`
}

type RuntimeEnvelope_Join struct {
	Join *PlayerJoin `protobuf:"bytes,11,opt,name=join,proto3,oneof"`
}

type RuntimeEnvelope_Leave struct {
	Leave *PlayerLeave `protobuf:"bytes,12,opt,name=leave,proto3,oneof"`
}

type RuntimeEnvelope_Input struct {
	Input *PlayerInput `protobuf:"bytes,13,opt,name=input,proto3,oneof"`
}

type RuntimeEnvelope_JoinResult struct {
	JoinResult *JoinResult `protobuf:"bytes,14,opt,name=join_result,json=joinResult,proto3,oneof"`
}

type RuntimeEnvelope_Error struct {
	Error *RuntimeError `protobuf:"bytes,15,opt,name=error,proto3,oneof"`
}

type RuntimeEnvelope_Snapshot struct {
	Snapshot *WorldSnapshot `protobuf:"bytes,16,opt,name=snapshot,proto3,oneof"`
}

func (*RuntimeEnvelope_Ready) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Join) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Leave) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Input) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_JoinResult) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Error) isRuntimeEnvelope_Message() {}

func (*RuntimeEnvelope_Snapshot) isRuntimeEnvelope_Message() {}

var File_runtime_v3_proto protoreflect.FileDescriptor

const file_runtime_v3_proto_rawDesc = "" +
	"\n" +
	"\x10runtime_v3.proto\x12\x19object_fps_pvp.runtime.v3\"\xbd\x01\n" +
	"\x05Ready\x12\x19\n" +
	"\barena_id\x18\x01 \x01(\tR\aarenaId\x12#\n" +
	"\rarena_version\x18\x02 \x01(\rR\farenaVersion\x12\x1b\n" +
	"\ttick_rate\x18\x03 \x01(\rR\btickRate\x126\n" +
	"\x17snapshot_interval_ticks\x18\x04 \x01(\rR\x15snapshotIntervalTicks\x12\x1f\n" +
	"\vmax_players\x18\x05 \x01(\rR\n" +
	"maxPlayers\")\n" +
	"\n" +
	"PlayerJoin\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\"*\n" +
	"\vPlayerLeave\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\"\x97\x01\n" +
	"\x0fMovementCommand\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12!\n" +
	"\fmove_forward\x18\x02 \x01(\x02R\vmoveForward\x12\x1d\n" +
	"\n" +
	"move_right\x18\x03 \x01(\x02R\tmoveRight\x12\x10\n" +
	"\x03yaw\x18\x04 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x05 \x01(\x02R\x05pitch\"\x99\x01\n" +
	"\vPlayerInput\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12F\n" +
	"\bcommands\x18\x02 \x03(\v2*.object_fps_pvp.runtime.v3.MovementCommandR\bcommands\x12%\n" +
	"\x0emovement_epoch\x18\x03 \x01(\x04R\rmovementEpoch\"]\n" +
	"\n" +
	"JoinResult\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x97\x02\n" +
	"\vPlayerState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x02R\x01z\x12\x10\n" +
	"\x03yaw\x18\x05 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x06 \x01(\x02R\x05pitch\x122\n" +
	"\x15last_resolved_command\x18\a \x01(\x04R\x13lastResolvedCommand\x12%\n" +
	"\x0emovement_epoch\x18\b \x01(\x04R\rmovementEpoch\x12>\n" +
	"\x1bcontiguous_pending_commands\x18\t \x01(\rR\x19contiguousPendingCommands\"e\n" +
	"\rWorldSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12@\n" +
	"\aplayers\x18\x02 \x03(\v2&.object_fps_pvp.runtime.v3.PlayerStateR\aplayers\"Y\n" +
	"\fRuntimeError\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x91\x04\n" +
	"\x0fRuntimeEnvelope\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x128\n" +
	"\x05ready\x18\n" +
	" \x01(\v2 .object_fps_pvp.runtime.v3.ReadyH\x00R\x05ready\x12;\n" +
	"\x04join\x18\v \x01(\v2%.object_fps_pvp.runtime.v3.PlayerJoinH\x00R\x04join\x12>\n" +
	"\x05leave\x18\f \x01(\v2&.object_fps_pvp.runtime.v3.PlayerLeaveH\x00R\x05leave\x12>\n" +
	"\x05input\x18\r \x01(\v2&.object_fps_pvp.runtime.v3.PlayerInputH\x00R\x05input\x12H\n" +
	"\vjoin_result\x18\x0e \x01(\v2%.object_fps_pvp.runtime.v3.JoinResultH\x00R\n" +
	"joinResult\x12?\n" +
	"\x05error\x18\x0f \x01(\v2'.object_fps_pvp.runtime.v3.RuntimeErrorH\x00R\x05error\x12F\n" +
	"\bsnapshot\x18\x10 \x01(\v2(.object_fps_pvp.runtime.v3.WorldSnapshotH\x00R\bsnapshotB\t\n" +
	"\amessageB-Z+gyo.local/object_fps_pvp/protocol/runtimev3b\x06proto3"

var (
	file_runtime_v3_proto_rawDescOnce sync.Once
	file_runtime_v3_proto_rawDescData []byte
)

func file_runtime_v3_proto_rawDescGZIP() []byte {
	file_runtime_v3_proto_rawDescOnce.Do(func() {
		file_runtime_v3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v3_proto_rawDesc), len(file_runtime_v3_proto_rawDesc)))
	})
	return file_runtime_v3_proto_rawDescData
}

var file_runtime_v3_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_runtime_v3_proto_goTypes = []any{
	(*Ready)(nil),           // 0: object_fps_pvp.runtime.v3.Ready
	(*PlayerJoin)(nil),      // 1: object_fps_pvp.runtime.v3.PlayerJoin
	(*PlayerLeave)(nil),     // 2: object_fps_pvp.runtime.v3.PlayerLeave
	(*MovementCommand)(nil), // 3: object_fps_pvp.runtime.v3.MovementCommand
	(*PlayerInput)(nil),     // 4: object_fps_pvp.runtime.v3.PlayerInput
	(*JoinResult)(nil),      // 5: object_fps_pvp.runtime.v3.JoinResult
	(*PlayerState)(nil),     // 6: object_fps_pvp.runtime.v3.PlayerState
	(*WorldSnapshot)(nil),   // 7: object_fps_pvp.runtime.v3.WorldSnapshot
	(*RuntimeError)(nil),    // 8: object_fps_pvp.runtime.v3.RuntimeError
	(*RuntimeEnvelope)(nil), // 9: object_fps_pvp.runtime.v3.RuntimeEnvelope
}
var file_runtime_v3_proto_depIdxs = []int32{
	3, // 0: object_fps_pvp.runtime.v3.PlayerInput.commands:type_name -> object_fps_pvp.runtime.v3.MovementCommand
	6, // 1: object_fps_pvp.runtime.v3.WorldSnapshot.players:type_name -> object_fps_pvp.runtime.v3.PlayerState
	0, // 2: object_fps_pvp.runtime.v3.RuntimeEnvelope.ready:type_name -> object_fps_pvp.runtime.v3.Ready
	1, // 3: object_fps_pvp.runtime.v3.RuntimeEnvelope.join:type_name -> object_fps_pvp.runtime.v3.PlayerJoin
	2, // 4: object_fps_pvp.runtime.v3.RuntimeEnvelope.leave:type_name -> object_fps_pvp.runtime.v3.PlayerLeave
	4, // 5: object_fps_pvp.runtime.v3.RuntimeEnvelope.input:type_name -> object_fps_pvp.runtime.v3.PlayerInput
	5, // 6: object_fps_pvp.runtime.v3.RuntimeEnvelope.join_result:type_name -> object_fps_pvp.runtime.v3.JoinResult
	8, // 7: object_fps_pvp.runtime.v3.RuntimeEnvelope.error:type_name -> object_fps_pvp.runtime.v3.RuntimeError
	7, // 8: object_fps_pvp.runtime.v3.RuntimeEnvelope.snapshot:type_name -> object_fps_pvp.runtime.v3.WorldSnapshot
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_runtime_v3_proto_init() }
func file_runtime_v3_proto_init() {
	if File_runtime_v3_proto != nil {
		return
	}
	file_runtime_v3_proto_msgTypes[9].OneofWrappers = []any{
		(*RuntimeEnvelope_Ready)(nil),
		(*RuntimeEnvelope_Join)(nil),
		(*RuntimeEnvelope_Leave)(nil),
		(*RuntimeEnvelope_Input)(nil),
		(*RuntimeEnvelope_JoinResult)(nil),
		(*RuntimeEnvelope_Error)(nil),
		(*RuntimeEnvelope_Snapshot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v3_proto_rawDesc), len(file_runtime_v3_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_runtime_v3_proto_goTypes,
		DependencyIndexes: file_runtime_v3_proto_depIdxs,
		MessageInfos:      file_runtime_v3_proto_msgTypes,
	}.Build()
	File_runtime_v3_proto = out.File
	file_runtime_v3_proto_goTypes = nil
	file_runtime_v3_proto_depIdxs = nil
}
