# Runs both authority digest runners and the golden check; see CMakeLists.txt.
#
# The -O0 comparison is enforced only for the zero-angle (golden) scenarios,
# which never reach a non-trivial sin/cos. Elsewhere the optimizer may change
# how libm is called (Apple clang merges sinf and cosf of one angle into
# __sincosf_stret, whose arm64 result can differ by an ULP), so a difference
# there is listed for information and is not a failure. The formal "authority
# unchanged" proof is the same-host two-tree comparison, built alike.
foreach(name OPTIMIZED UNOPTIMIZED GOLDEN OUTPUT)
    if(NOT DEFINED ${name})
        message(FATAL_ERROR "authority_digest_check.cmake needs -D${name}")
    endif()
endforeach()
file(MAKE_DIRECTORY "${OUTPUT}")
foreach(build OPTIMIZED UNOPTIMIZED)
    execute_process(COMMAND "${${build}}" --run --out "${OUTPUT}/${build}.json" RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "${build} authority digest runner failed (${result})")
    endif()
endforeach()
file(READ "${OUTPUT}/OPTIMIZED.json" optimized)
file(READ "${OUTPUT}/UNOPTIMIZED.json" unoptimized)
string(JSON count LENGTH "${optimized}" scenarios)
string(JSON other LENGTH "${unoptimized}" scenarios)
if(NOT count EQUAL other)
    message(FATAL_ERROR "-O0 and optimized runners list different scenarios")
endif()
math(EXPR last "${count} - 1")
set(golden_differences "")
set(other_differences "")
set(compared 0)
foreach(index RANGE ${last})
    string(JSON name GET "${optimized}" scenarios ${index} name)
    string(JSON other_name GET "${unoptimized}" scenarios ${index} name)
    string(JSON is_golden GET "${optimized}" scenarios ${index} golden)
    string(JSON left GET "${optimized}" scenarios ${index} digest)
    string(JSON right GET "${unoptimized}" scenarios ${index} digest)
    if(NOT name STREQUAL other_name)
        message(FATAL_ERROR "-O0 and optimized runners list scenarios in a different order")
    endif()
    if(is_golden)
        math(EXPR compared "${compared} + 1")
        if(NOT left STREQUAL right)
            list(APPEND golden_differences "${name}")
        endif()
    elseif(NOT left STREQUAL right)
        list(APPEND other_differences "${name}")
    endif()
endforeach()
if(other_differences)
    list(JOIN other_differences "\n  " listed)
    message(STATUS "Information only: -O0 and optimized digests differ in non-zero-angle scenarios:\n  ${listed}")
endif()
set(failures "")
if(golden_differences)
    list(JOIN golden_differences "\n  " listed)
    message(STATUS "-O0 and optimized digests differ in zero-angle scenarios:\n  ${listed}")
    string(APPEND failures "-O0 and optimized digests differ in the zero-angle subset; ")
endif()
message(STATUS "-O0 comparison enforced on ${compared} zero-angle scenarios")
execute_process(COMMAND "${OPTIMIZED}" --check-golden "${GOLDEN}" RESULT_VARIABLE golden_result)
if(NOT golden_result EQUAL 0)
    string(APPEND failures "golden authority subset differs from ${GOLDEN}; ")
endif()
if(failures)
    message(FATAL_ERROR "${failures}outputs in ${OUTPUT}")
endif()
