# Runs both authority digest runners and the golden check; see CMakeLists.txt.
foreach(name OPTIMIZED UNOPTIMIZED GOLDEN OUTPUT)
    if(NOT DEFINED ${name})
        message(FATAL_ERROR "authority_digest_check.cmake needs -D${name}")
    endif()
endforeach()
file(MAKE_DIRECTORY "${OUTPUT}")
foreach(build OPTIMIZED UNOPTIMIZED)
    execute_process(COMMAND "${${build}}" --run --out "${OUTPUT}/${build}.json" RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "${build} authority digest runner failed (${result})")
    endif()
endforeach()
execute_process(COMMAND "${CMAKE_COMMAND}" -E compare_files "${OUTPUT}/OPTIMIZED.json" "${OUTPUT}/UNOPTIMIZED.json"
    RESULT_VARIABLE different)
if(different)
    message(FATAL_ERROR "-O0 and optimized authority digests differ; compare ${OUTPUT}/OPTIMIZED.json and UNOPTIMIZED.json")
endif()
execute_process(COMMAND "${OPTIMIZED}" --check-golden "${GOLDEN}" RESULT_VARIABLE golden)
if(NOT golden EQUAL 0)
    message(FATAL_ERROR "Golden authority subset differs from ${GOLDEN}")
endif()
