# Runs both authority digest runners and the golden check; see CMakeLists.txt.
# Every failure names the scenarios involved, and the golden check runs even
# when the -O0 comparison already failed, so one CI run shows both results.
foreach(name OPTIMIZED UNOPTIMIZED GOLDEN OUTPUT)
    if(NOT DEFINED ${name})
        message(FATAL_ERROR "authority_digest_check.cmake needs -D${name}")
    endif()
endforeach()
file(MAKE_DIRECTORY "${OUTPUT}")
foreach(build OPTIMIZED UNOPTIMIZED)
    execute_process(COMMAND "${${build}}" --run --out "${OUTPUT}/${build}.json" RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "${build} authority digest runner failed (${result})")
    endif()
endforeach()
set(failures "")
execute_process(COMMAND "${CMAKE_COMMAND}" -E compare_files "${OUTPUT}/OPTIMIZED.json" "${OUTPUT}/UNOPTIMIZED.json"
    RESULT_VARIABLE different)
if(different)
    file(READ "${OUTPUT}/OPTIMIZED.json" optimized)
    file(READ "${OUTPUT}/UNOPTIMIZED.json" unoptimized)
    string(JSON count LENGTH "${optimized}" scenarios)
    math(EXPR last "${count} - 1")
    set(names "")
    foreach(index RANGE ${last})
        string(JSON name GET "${optimized}" scenarios ${index} name)
        string(JSON golden GET "${optimized}" scenarios ${index} golden)
        string(JSON left GET "${optimized}" scenarios ${index} digest)
        string(JSON right GET "${unoptimized}" scenarios ${index} digest)
        if(NOT left STREQUAL right)
            if(golden)
                list(APPEND names "${name} [golden subset]")
            else()
                list(APPEND names "${name} [non-zero angles]")
            endif()
        endif()
    endforeach()
    list(JOIN names "\n  " listed)
    message(STATUS "-O0 and optimized digests differ in:\n  ${listed}")
    string(APPEND failures "-O0 and optimized authority digests differ (see the scenario list above); ")
endif()
execute_process(COMMAND "${OPTIMIZED}" --check-golden "${GOLDEN}" RESULT_VARIABLE golden)
if(NOT golden EQUAL 0)
    string(APPEND failures "golden authority subset differs from ${GOLDEN}; ")
endif()
if(failures)
    message(FATAL_ERROR "${failures}outputs in ${OUTPUT}")
endif()
