// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: client_v4.proto

package clientv4

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShotRejection int32

const (
	ShotRejection_REJECTION_NONE              ShotRejection = 0
	ShotRejection_REJECTION_INVALID_REFERENCE ShotRejection = 1
	ShotRejection_REJECTION_EXPIRED           ShotRejection = 2
	ShotRejection_REJECTION_COOLDOWN          ShotRejection = 3
)

// Enum value maps for ShotRejection.
var (
	ShotRejection_name = map[int32]string{
		0: "REJECTION_NONE",
		1: "REJECTION_INVALID_REFERENCE",
		2: "REJECTION_EXPIRED",
		3: "REJECTION_COOLDOWN",
	}
	ShotRejection_value = map[string]int32{
		"REJECTION_NONE":              0,
		"REJECTION_INVALID_REFERENCE": 1,
		"REJECTION_EXPIRED":           2,
		"REJECTION_COOLDOWN":          3,
	}
)

func (x ShotRejection) Enum() *ShotRejection {
	p := new(ShotRejection)
	*p = x
	return p
}

func (x ShotRejection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShotRejection) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v4_proto_enumTypes[0].Descriptor()
}

func (ShotRejection) Type() protoreflect.EnumType {
	return &file_client_v4_proto_enumTypes[0]
}

func (x ShotRejection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShotRejection.Descriptor instead.
func (ShotRejection) EnumDescriptor() ([]byte, []int) {
	return file_client_v4_proto_rawDescGZIP(), []int{0}
}

type ShotHitKind int32

const (
	ShotHitKind_HIT_MISS   ShotHitKind = 0
	ShotHitKind_HIT_WORLD  ShotHitKind = 1
	ShotHitKind_HIT_PLAYER ShotHitKind = 2
)

// Enum value maps for ShotHitKind.
var (
	ShotHitKind_name = map[int32]string{
		0: "HIT_MISS",
		1: "HIT_WORLD",
		2: "HIT_PLAYER",
	}
	ShotHitKind_value = map[string]int32{
		"HIT_MISS":   0,
		"HIT_WORLD":  1,
		"HIT_PLAYER": 2,
	}
)

func (x ShotHitKind) Enum() *ShotHitKind {
	p := new(ShotHitKind)
	*p = x
	return p
}

func (x ShotHitKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShotHitKind) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v4_proto_enumTypes[1].Descriptor()
}

func (ShotHitKind) Type() protoreflect.EnumType {
	return &file_client_v4_proto_enumTypes[1]
}

func (x ShotHitKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShotHitKind.Descriptor instead.
func (ShotHitKind) EnumDescriptor() ([]byte, []int) {
	return file_client_v4_proto_rawDescGZIP(), []int{1}
}

// This remote-client contract is independent of runtime_v4.proto.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_client_v4_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_client_v4_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_client_v4_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MatchId       uint64                 `protobuf:"varint,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	TickRate      uint32                 `protobuf:"varint,3,opt,name=tick_rate,json=tickRate,proto3" json:"tick_rate,omitempty"`
	SnapshotRate  uint32                 `protobuf:"varint,4,opt,name=snapshot_rate,json=snapshotRate,proto3" json:"snapshot_rate,omitempty"`
	ArenaId       string                 `protobuf:"bytes,5,opt,name=arena_id,json=arenaId,proto3" json:"arena_id,omitempty"`
	ArenaVersion  uint32                 `protobuf:"varint,6,opt,name=arena_version,json=arenaVersion,proto3" json:"arena_version,omitempty"`
	CombatRules   *CombatRules           `protobuf:"bytes,7,opt,name=combat_rules,json=combatRules,proto3" json:"combat_rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_client_v4_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_client_v4_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_client_v4_proto_rawDescGZIP(), []int{1}
}

func (x *Welcome) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Welcome) GetMatchId() uint64 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

func (x *Welcome) GetTickRate() uint32 {
	if x != nil {
		return x.TickRate
	}
	return 0
}

func (x *Welcome) GetSnapshotRate() uint32 {
	if x != nil {
		return x.SnapshotRate
	}
	return 0
}

func (x *Welcome) GetArenaId() string {
	if x != nil {
		return x.ArenaId
	}
	return ""
}

func (x *Welcome) GetArenaVersion() uint32 {
	if x != nil {
		return x.ArenaVersion
	}
	return 0
}

func (x *Welcome) GetCombatRules() *CombatRules {
	if x != nil {
		return x.CombatRules
	}
	return nil
}

// A single immutable 1/60-second movement step. No client time or position.
type MovementCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	MoveForward   float32                `protobuf:"fixed32,2,opt,name=move_forward,json=moveForward,proto3" json:"move_forward,omitempty"`
	MoveRight     float32                `protobuf:"fixed32,3,opt,name=move_right,json=moveRight,proto3" json:"move_right,omitempty"`
	Yaw           float32                `protobuf:"fixed32,4,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch         float32                `protobuf:"fixed32,5,opt,name=pitch,proto3" json:"pitch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovementCommand) Reset() {
	*x = MovementCommand{}
	mi := &file_client_v4_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovementCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovementCommand) ProtoMessage() {}

func (x *MovementCommand) ProtoReflect() protoreflect.Message {
	mi := &file_client_v4_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovementCommand.ProtoReflect.Descriptor instead.
func (*MovementCommand) Descriptor() ([]byte, []int) {
	return file_client_v4_proto_rawDescGZIP(), []int{2}
}

func (x *MovementCommand) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MovementCommand) GetMoveForward() float32 {
	if x != nil {
		return x.MoveForward
	}
	return 0
}

func (x *MovementCommand) GetMoveRight() float32 {
	if x != nil {
		return x.MoveRight
	}
	return 0
}

func (x *MovementCommand) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *MovementCommand) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

// Entire unacknowledged window, strictly ordered, at most 12 commands.
type PlayerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*MovementCommand     `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	MovementEpoch uint64                 `protobuf:"varint,2,opt,name=movement_epoch,json=movementEpoch,proto3" json:"movement_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_client_v4_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_client_v4_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_client_v4_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerInput) GetCommands() []*MovementCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *PlayerInput) GetMovementEpoch() uint64 {
	if x != nil {
		return x.MovementEpoch
	}
	return 0
}

type PlayerState struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	PlayerId                  uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X                         float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                         float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z                         float32                `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	Yaw                       float32                `protobuf:"fixed32,5,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch                     float32                `protobuf:"fixed32,6,opt,name=pitch,proto3" json:"pitch,omitempty"`
	LastResolvedCommand       uint64                 `protobuf:"varint,7,opt,name=last_resolved_command,json=lastResolvedCommand,proto3" json:"last_resolved_command,omitempty"`
	MovementEpoch             uint64                 `protobuf:"varint,8,opt,name=movement_epoch,json=movementEpoch,proto3" json:"movement_epoch,omitempty"`
	ContiguousPendingCommands uint32                 `protobuf:"varint,9,opt,name=contiguous_pending_commands,json=contiguousPendingCommands,proto3" json:"contiguous_pending_commands,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_client_v4_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_client_v4_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_client_v4_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerState) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerState) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerState) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *PlayerState) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *PlayerState) GetLastResolvedCommand() uint64 {
	if x != nil {
		return x.LastResolvedCommand
	}
	return 0
}

func (x *PlayerState) GetMovementEpoch() uint64 {
	if x != nil {
		return x.MovementEpoch
	}
	return 0
}

func (x *PlayerState) GetContiguousPendingCommands() uint32 {
	if x != nil {
		return x.ContiguousPendingCommands
	}
	return 0
}

type WorldSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Players       []*PlayerState         `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Combat        []*CombatState         `protobuf:"bytes,3,rep,name=combat,proto3" json:"combat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldSnapshot) Reset() {
	*x = WorldSnapshot{}
	mi := &file_client_v4_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldSnapshot) ProtoMessage() {}

func (x *WorldSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_client_v4_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldSnapshot.ProtoReflect.Descriptor instead.
func (*WorldSnapshot) Descriptor() ([]byte, []int) {
	return file_client_v4_proto_rawDescGZIP(), []int{5}
}

func (x *WorldSnapshot) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *WorldSnapshot) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *WorldSnapshot) GetCombat() []*CombatState {
	if x != nil {
		return x.Combat
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_client_v4_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_client_v4_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_client_v4_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ActionBatch struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Shots               []*ShotRequest         `protobuf:"bytes,1,rep,name=shots,proto3" json:"shots,omitempty"`
	AcknowledgedThrough uint64                 `protobuf:"varint,2,opt,name=acknowledged_through,json=acknowledgedThrough,proto3" json:"acknowledged_through,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ActionBatch) Reset() {
	*x = ActionBatch{}
	mi := &file_client_v4_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionBatch) ProtoMessage() {}

func (x *ActionBatch) ProtoReflect() protoreflect.Message {
	mi := &file_client_v4_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionBatch.ProtoReflect.Descriptor instead.
func (*ActionBatch) Descriptor() ([]byte, []int) {
	return file_client_v4_proto_rawDescGZIP(), []int{7}
}

func (x *ActionBatch) GetShots() []*ShotRequest {
	if x != nil {
		return x.Shots
	}
	return nil
}

func (x *ActionBatch) GetAcknowledgedThrough() uint64 {
	if x != nil {
		return x.AcknowledgedThrough
	}
	return 0
}

type ActionResults struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RetiredThrough uint64                 `protobuf:"varint,1,opt,name=retired_through,json=retiredThrough,proto3" json:"retired_through,omitempty"`
	Decisions      []*ShotDecision        `protobuf:"bytes,2,rep,name=decisions,proto3" json:"decisions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActionResults) Reset() {
	*x = ActionResults{}
	mi := &file_client_v4_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResults) ProtoMessage() {}

func (x *ActionResults) ProtoReflect() protoreflect.Message {
	mi := &file_client_v4_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResults.ProtoReflect.Descriptor instead.
func (*ActionResults) Descriptor() ([]byte, []int) {
	return file_client_v4_proto_rawDescGZIP(), []int{8}
}

func (x *ActionResults) GetRetiredThrough() uint64 {
	if x != nil {
		return x.RetiredThrough
	}
	return 0
}

func (x *ActionResults) GetDecisions() []*ShotDecision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

type CombatRules struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MaximumHp             uint32                 `protobuf:"varint,1,opt,name=maximum_hp,json=maximumHp,proto3" json:"maximum_hp,omitempty"`
	ShotDamage            uint32                 `protobuf:"varint,2,opt,name=shot_damage,json=shotDamage,proto3" json:"shot_damage,omitempty"`
	CooldownTicks         uint64                 `protobuf:"varint,3,opt,name=cooldown_ticks,json=cooldownTicks,proto3" json:"cooldown_ticks,omitempty"`
	ShotRange             float32                `protobuf:"fixed32,4,opt,name=shot_range,json=shotRange,proto3" json:"shot_range,omitempty"`
	MaximumReferenceAgeMs uint32                 `protobuf:"varint,5,opt,name=maximum_reference_age_ms,json=maximumReferenceAgeMs,proto3" json:"maximum_reference_age_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CombatRules) Reset() {
	*x = CombatRules{}
	mi := &file_client_v4_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatRules) ProtoMessage() {}

func (x *CombatRules) ProtoReflect() protoreflect.Message {
	mi := &file_client_v4_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatRules.ProtoReflect.Descriptor instead.
func (*CombatRules) Descriptor() ([]byte, []int) {
	return file_client_v4_proto_rawDescGZIP(), []int{9}
}

func (x *CombatRules) GetMaximumHp() uint32 {
	if x != nil {
		return x.MaximumHp
	}
	return 0
}

func (x *CombatRules) GetShotDamage() uint32 {
	if x != nil {
		return x.ShotDamage
	}
	return 0
}

func (x *CombatRules) GetCooldownTicks() uint64 {
	if x != nil {
		return x.CooldownTicks
	}
	return 0
}

func (x *CombatRules) GetShotRange() float32 {
	if x != nil {
		return x.ShotRange
	}
	return 0
}

func (x *CombatRules) GetMaximumReferenceAgeMs() uint32 {
	if x != nil {
		return x.MaximumReferenceAgeMs
	}
	return 0
}

type CombatState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlayerId            uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Hp                  uint32                 `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`
	NextAllowedShotTick uint64                 `protobuf:"varint,3,opt,name=next_allowed_shot_tick,json=nextAllowedShotTick,proto3" json:"next_allowed_shot_tick,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CombatState) Reset() {
	*x = CombatState{}
	mi := &file_client_v4_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatState) ProtoMessage() {}

func (x *CombatState) ProtoReflect() protoreflect.Message {
	mi := &file_client_v4_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatState.ProtoReflect.Descriptor instead.
func (*CombatState) Descriptor() ([]byte, []int) {
	return file_client_v4_proto_rawDescGZIP(), []int{10}
}

func (x *CombatState) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *CombatState) GetHp() uint32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *CombatState) GetNextAllowedShotTick() uint64 {
	if x != nil {
		return x.NextAllowedShotTick
	}
	return 0
}

type ShotRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ActionId              uint64                 `protobuf:"varint,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	ObservedAuthorityTick uint64                 `protobuf:"varint,2,opt,name=observed_authority_tick,json=observedAuthorityTick,proto3" json:"observed_authority_tick,omitempty"`
	Yaw                   float32                `protobuf:"fixed32,3,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch                 float32                `protobuf:"fixed32,4,opt,name=pitch,proto3" json:"pitch,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ShotRequest) Reset() {
	*x = ShotRequest{}
	mi := &file_client_v4_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShotRequest) ProtoMessage() {}

func (x *ShotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v4_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShotRequest.ProtoReflect.Descriptor instead.
func (*ShotRequest) Descriptor() ([]byte, []int) {
	return file_client_v4_proto_rawDescGZIP(), []int{11}
}

func (x *ShotRequest) GetActionId() uint64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *ShotRequest) GetObservedAuthorityTick() uint64 {
	if x != nil {
		return x.ObservedAuthorityTick
	}
	return 0
}

func (x *ShotRequest) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *ShotRequest) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

type ShotDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      uint64                 `protobuf:"varint,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	ResolvedTick  uint64                 `protobuf:"varint,2,opt,name=resolved_tick,json=resolvedTick,proto3" json:"resolved_tick,omitempty"`
	Accepted      bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejection     ShotRejection          `protobuf:"varint,4,opt,name=rejection,proto3,enum=object_fps_pvp.client.v4.ShotRejection" json:"rejection,omitempty"`
	HitKind       ShotHitKind            `protobuf:"varint,5,opt,name=hit_kind,json=hitKind,proto3,enum=object_fps_pvp.client.v4.ShotHitKind" json:"hit_kind,omitempty"`
	TargetId      uint64                 `protobuf:"varint,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Damage        uint32                 `protobuf:"varint,7,opt,name=damage,proto3" json:"damage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShotDecision) Reset() {
	*x = ShotDecision{}
	mi := &file_client_v4_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShotDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShotDecision) ProtoMessage() {}

func (x *ShotDecision) ProtoReflect() protoreflect.Message {
	mi := &file_client_v4_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShotDecision.ProtoReflect.Descriptor instead.
func (*ShotDecision) Descriptor() ([]byte, []int) {
	return file_client_v4_proto_rawDescGZIP(), []int{12}
}

func (x *ShotDecision) GetActionId() uint64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *ShotDecision) GetResolvedTick() uint64 {
	if x != nil {
		return x.ResolvedTick
	}
	return 0
}

func (x *ShotDecision) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ShotDecision) GetRejection() ShotRejection {
	if x != nil {
		return x.Rejection
	}
	return ShotRejection_REJECTION_NONE
}

func (x *ShotDecision) GetHitKind() ShotHitKind {
	if x != nil {
		return x.HitKind
	}
	return ShotHitKind_HIT_MISS
}

func (x *ShotDecision) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ShotDecision) GetDamage() uint32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

var File_client_v4_proto protoreflect.FileDescriptor

const file_client_v4_proto_rawDesc = "" +
	"\n" +
	"\x0fclient_v4.proto\x12\x18object_fps_pvp.client.v4\",\n" +
	"\x05Hello\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\"\x8d\x02\n" +
	"\aWelcome\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x19\n" +
	"\bmatch_id\x18\x02 \x01(\x04R\amatchId\x12\x1b\n" +
	"\ttick_rate\x18\x03 \x01(\rR\btickRate\x12#\n" +
	"\rsnapshot_rate\x18\x04 \x01(\rR\fsnapshotRate\x12\x19\n" +
	"\barena_id\x18\x05 \x01(\tR\aarenaId\x12#\n" +
	"\rarena_version\x18\x06 \x01(\rR\farenaVersion\x12H\n" +
	"\fcombat_rules\x18\a \x01(\v2%.object_fps_pvp.client.v4.CombatRulesR\vcombatRules\"\x97\x01\n" +
	"\x0fMovementCommand\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12!\n" +
	"\fmove_forward\x18\x02 \x01(\x02R\vmoveForward\x12\x1d\n" +
	"\n" +
	"move_right\x18\x03 \x01(\x02R\tmoveRight\x12\x10\n" +
	"\x03yaw\x18\x04 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x05 \x01(\x02R\x05pitch\"{\n" +
	"\vPlayerInput\x12E\n" +
	"\bcommands\x18\x01 \x03(\v2).object_fps_pvp.client.v4.MovementCommandR\bcommands\x12%\n" +
	"\x0emovement_epoch\x18\x02 \x01(\x04R\rmovementEpoch\"\x97\x02\n" +
	"\vPlayerState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x02R\x01z\x12\x10\n" +
	"\x03yaw\x18\x05 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x06 \x01(\x02R\x05pitch\x122\n" +
	"\x15last_resolved_command\x18\a \x01(\x04R\x13lastResolvedCommand\x12%\n" +
	"\x0emovement_epoch\x18\b \x01(\x04R\rmovementEpoch\x12>\n" +
	"\x1bcontiguous_pending_commands\x18\t \x01(\rR\x19contiguousPendingCommands\"\xa3\x01\n" +
	"\rWorldSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12?\n" +
	"\aplayers\x18\x02 \x03(\v2%.object_fps_pvp.client.v4.PlayerStateR\aplayers\x12=\n" +
	"\x06combat\x18\x03 \x03(\v2%.object_fps_pvp.client.v4.CombatStateR\x06combat\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"}\n" +
	"\vActionBatch\x12;\n" +
	"\x05shots\x18\x01 \x03(\v2%.object_fps_pvp.client.v4.ShotRequestR\x05shots\x121\n" +
	"\x14acknowledged_through\x18\x02 \x01(\x04R\x13acknowledgedThrough\"~\n" +
	"\rActionResults\x12'\n" +
	"\x0fretired_through\x18\x01 \x01(\x04R\x0eretiredThrough\x12D\n" +
	"\tdecisions\x18\x02 \x03(\v2&.object_fps_pvp.client.v4.ShotDecisionR\tdecisions\"\xcc\x01\n" +
	"\vCombatRules\x12\x1d\n" +
	"\n" +
	"maximum_hp\x18\x01 \x01(\rR\tmaximumHp\x12\x1f\n" +
	"\vshot_damage\x18\x02 \x01(\rR\n" +
	"shotDamage\x12%\n" +
	"\x0ecooldown_ticks\x18\x03 \x01(\x04R\rcooldownTicks\x12\x1d\n" +
	"\n" +
	"shot_range\x18\x04 \x01(\x02R\tshotRange\x127\n" +
	"\x18maximum_reference_age_ms\x18\x05 \x01(\rR\x15maximumReferenceAgeMs\"o\n" +
	"\vCombatState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x0e\n" +
	"\x02hp\x18\x02 \x01(\rR\x02hp\x123\n" +
	"\x16next_allowed_shot_tick\x18\x03 \x01(\x04R\x13nextAllowedShotTick\"\x8a\x01\n" +
	"\vShotRequest\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\x04R\bactionId\x126\n" +
	"\x17observed_authority_tick\x18\x02 \x01(\x04R\x15observedAuthorityTick\x12\x10\n" +
	"\x03yaw\x18\x03 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x04 \x01(\x02R\x05pitch\"\xaa\x02\n" +
	"\fShotDecision\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\x04R\bactionId\x12#\n" +
	"\rresolved_tick\x18\x02 \x01(\x04R\fresolvedTick\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\x12E\n" +
	"\trejection\x18\x04 \x01(\x0e2'.object_fps_pvp.client.v4.ShotRejectionR\trejection\x12@\n" +
	"\bhit_kind\x18\x05 \x01(\x0e2%.object_fps_pvp.client.v4.ShotHitKindR\ahitKind\x12\x1b\n" +
	"\ttarget_id\x18\x06 \x01(\x04R\btargetId\x12\x16\n" +
	"\x06damage\x18\a \x01(\rR\x06damage*s\n" +
	"\rShotRejection\x12\x12\n" +
	"\x0eREJECTION_NONE\x10\x00\x12\x1f\n" +
	"\x1bREJECTION_INVALID_REFERENCE\x10\x01\x12\x15\n" +
	"\x11REJECTION_EXPIRED\x10\x02\x12\x16\n" +
	"\x12REJECTION_COOLDOWN\x10\x03*:\n" +
	"\vShotHitKind\x12\f\n" +
	"\bHIT_MISS\x10\x00\x12\r\n" +
	"\tHIT_WORLD\x10\x01\x12\x0e\n" +
	"\n" +
	"HIT_PLAYER\x10\x02B,Z*gyo.local/object_fps_pvp/protocol/clientv4b\x06proto3"

var (
	file_client_v4_proto_rawDescOnce sync.Once
	file_client_v4_proto_rawDescData []byte
)

func file_client_v4_proto_rawDescGZIP() []byte {
	file_client_v4_proto_rawDescOnce.Do(func() {
		file_client_v4_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_v4_proto_rawDesc), len(file_client_v4_proto_rawDesc)))
	})
	return file_client_v4_proto_rawDescData
}

var file_client_v4_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_client_v4_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_client_v4_proto_goTypes = []any{
	(ShotRejection)(0),      // 0: object_fps_pvp.client.v4.ShotRejection
	(ShotHitKind)(0),        // 1: object_fps_pvp.client.v4.ShotHitKind
	(*Hello)(nil),           // 2: object_fps_pvp.client.v4.Hello
	(*Welcome)(nil),         // 3: object_fps_pvp.client.v4.Welcome
	(*MovementCommand)(nil), // 4: object_fps_pvp.client.v4.MovementCommand
	(*PlayerInput)(nil),     // 5: object_fps_pvp.client.v4.PlayerInput
	(*PlayerState)(nil),     // 6: object_fps_pvp.client.v4.PlayerState
	(*WorldSnapshot)(nil),   // 7: object_fps_pvp.client.v4.WorldSnapshot
	(*Error)(nil),           // 8: object_fps_pvp.client.v4.Error
	(*ActionBatch)(nil),     // 9: object_fps_pvp.client.v4.ActionBatch
	(*ActionResults)(nil),   // 10: object_fps_pvp.client.v4.ActionResults
	(*CombatRules)(nil),     // 11: object_fps_pvp.client.v4.CombatRules
	(*CombatState)(nil),     // 12: object_fps_pvp.client.v4.CombatState
	(*ShotRequest)(nil),     // 13: object_fps_pvp.client.v4.ShotRequest
	(*ShotDecision)(nil),    // 14: object_fps_pvp.client.v4.ShotDecision
}
var file_client_v4_proto_depIdxs = []int32{
	11, // 0: object_fps_pvp.client.v4.Welcome.combat_rules:type_name -> object_fps_pvp.client.v4.CombatRules
	4,  // 1: object_fps_pvp.client.v4.PlayerInput.commands:type_name -> object_fps_pvp.client.v4.MovementCommand
	6,  // 2: object_fps_pvp.client.v4.WorldSnapshot.players:type_name -> object_fps_pvp.client.v4.PlayerState
	12, // 3: object_fps_pvp.client.v4.WorldSnapshot.combat:type_name -> object_fps_pvp.client.v4.CombatState
	13, // 4: object_fps_pvp.client.v4.ActionBatch.shots:type_name -> object_fps_pvp.client.v4.ShotRequest
	14, // 5: object_fps_pvp.client.v4.ActionResults.decisions:type_name -> object_fps_pvp.client.v4.ShotDecision
	0,  // 6: object_fps_pvp.client.v4.ShotDecision.rejection:type_name -> object_fps_pvp.client.v4.ShotRejection
	1,  // 7: object_fps_pvp.client.v4.ShotDecision.hit_kind:type_name -> object_fps_pvp.client.v4.ShotHitKind
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_client_v4_proto_init() }
func file_client_v4_proto_init() {
	if File_client_v4_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_v4_proto_rawDesc), len(file_client_v4_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_v4_proto_goTypes,
		DependencyIndexes: file_client_v4_proto_depIdxs,
		EnumInfos:         file_client_v4_proto_enumTypes,
		MessageInfos:      file_client_v4_proto_msgTypes,
	}.Build()
	File_client_v4_proto = out.File
	file_client_v4_proto_goTypes = nil
	file_client_v4_proto_depIdxs = nil
}
